### PR TITLE
plutus-tutorial: switch to asciidoctor

### PR DESCRIPTION
**Pull request by michaelpj**
- Converts all the tutorials to asciidoc.
    - Various minor structural changes to reflect it being one document.
- Source files (mostly) display on Github too.
- Produces single HTML file and images dir.
    - We can chunk it later if we want.
- Literate Haskell processing with `unlit` works, although I had to patch it.

I haven't figured out what to do with the Haskell tutorials, though.

### CODE REVIEW

**Comment by michaelpj** [comment]
Also, we can now use [callouts](https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks) for some of the explanation of code, which is nice.

**Comment by j-mueller** [comment]
Awesome!

**Comment by mchakravarty** [comment]
What's wrong with markdown?

**Comment by michaelpj** [comment]
See discussion on https://github.com/input-output-hk/plutus/issues/827.

Callouts, better handling of multiple documents, cross-references, navigation and TOC, epub output.

**Pull request merged**
