### PR TITLE
Plutus core/add spec examples

### PR DESCRIPTION
**Pull request by vmchale**
This adds the examples from the written text; and will have corrections to the written text where necessary.

### CODE REVIEW

**Comment by michaelpj** [comment]
Why not use `\input` to include the very same files as the examples in the spec? That way we're sure they won't get out of sync in future.

**Comment by kwxm** [comment]
If nobody objects I'll merge this later today in order to move things forward.  I like Michael's suggestion about using \include because that'd make it a lot easier to check that the examples typecheck and run; we can do that later though.

**Comment by michaelpj** [comment]
Well, is this done? It still says `WIP`.

**Comment by vmchale** [comment]
@kwxm @michaelpj  unfortunately we need slightly different form in the spec, so we cannot use `\include` or the like.

**Comment by michaelpj** [comment]
What do we need that's different? Is it just that we want to display terms not wrapped in a `Program`? That's easy enough to handle in the tests (and we would probably want to put these in a separate directory anyway to avoid us accidentally changing them).

I think there's a lot of benefit to machine-checking exactly the thing that's in the spec, so I think it's worth spending some effort on.

**Comment by vmchale** [comment]
No, we want it to match the surrounding text. Free variables need `$` around them.

**Comment by vmchale** [comment]
In any case, this can be fixed later - nominally these pull requests were not supposed to need review.

**Comment by michaelpj** [comment]
Sure, but we're also improving it, and making it machine checkable seems like a pretty big improvement to me :)

Anyway, if you don't want to do it now, then okay.

**Pull request merged**
