### PR TITLE
wallet-api: Cabal file

### PR DESCRIPTION
**Pull request by j-mueller**
Rewrite wallet-api.cabal in the style of plutus-tx.cabal.

Just putting this up for a test.

### CODE REVIEW

**Comment by michaelpj** [comment]
You need to also add the bits I added in `nix/overlays/required.nix`. Note that that includes turning off the Haddock for now, although I think I know how to fix it. So you might not want to do this until I figure it out.

**Comment by j-mueller** [comment]
Thanks. I remember now. I'll get back to this at a later stage because I would like the wallet API haddocks to be up to date.

**Comment by michaelpj** [comment]
Sorry, I was completely off-base with this: it's having an internal library that breaks Haddock. You should reopen this!

**Comment by michaelpj** [comment]
You do need the thing in `nix/overlays/required.nix` though.

**Comment by j-mueller** [comment]
ok, cool!

**Comment by michaelpj** [comment]
(and it conflicts)

**Comment by michaelpj** [comment]
`wallet-api` has no doctests now?

**Comment by michaelpj** [comment]
i.e. now the tutorial has moved I don't think this does anything.

**Pull request merged**
