### PR TITLE
[Builtins] Update 'BuiltinRuntime' to store the costing function strictly

### PR DESCRIPTION
**Pull request by effectfully**
Since the HOAS evaluator is gone, we don't need that laziness anymore.

### CODE REVIEW

**Comment by effectfully** [comment]
-2.59% on average. Some free speedup right there. Thanks to @bezirg for bringing it up.

**Review by bezirg — APPROVED** [review]

**Comment by michaelpj** [comment]
The tests that run the CK machine fail now.

**Comment by michaelpj** [comment]
Speedup looks good, though!

**Comment by effectfully** [comment]
> The tests that run the CK machine fail now.

Ah, I forgot that it wasn't doing any costing too. I'll do something about it, perhaps introduce some kind of dummy costing or whatever.

**Comment by effectfully** [comment]
> > The tests that run the CK machine fail now.
> 
> Ah, I forgot that it wasn't doing any costing too. I'll do something about it, perhaps introduce some kind of dummy costing or whatever.

Done.

**Review by kwxm — APPROVED** [review]
Looks fine.

**Comment by kwxm** [comment]
FYI I've got an issue to store actual functions for costing, rather than objects containing parameters that have to be looked up an used to calculate the cost every time (I assume) that the costing function is called.  I keep getting distracted from that though.

**Comment by effectfully** [comment]
> FYI I've got an issue to store actual functions for costing, rather than objects containing parameters that have to be looked up an used to calculate the cost every time (I assume) that the costing function is called. I keep getting distracted from that though.

I was going to look into that too. Let me first try to optimize the existing stuff, maybe it's fine to have objects containing parameters as long as we don't need to match on them every time.

**Pull request merged**
