### PR TITLE
StateMachine step and initialise with additional constraints and lookups

### PR DESCRIPTION
**Pull request by anton-k**
we have nice function  `submitTxConstraintsWith` that allows to pass additional constraints and lookups.
It would be great to have the same counterpart for StateMachine.

* **problem**:

We have useful functions for SM transitions: `runStep` and `runInitialise`.
But I've found that they are often not enough because we want to supply additional constraints and lookups 
for transaction that relies on SM. For `runStep` we can make a workaround with `mkStep`, but for `runInitialise` there is no such way.

* **solution**:

With this PR we can define functions similar to `submitTxConstraintsWith` that allow SM-user to pass additional constraints and lookups. They are called `runStepWith`, `runInitialiseWith`.

### CODE REVIEW

**Review by ak3n — CHANGES_REQUESTED** [review]
I would redefine `runInitialise`, `runStep` and `runGuardedStep` via their `With` versions passing empty lookups and constraints to avoid code duplication and possible divergence in logic.

Not sure if it's okay to pass custom lookups and constraints though.

**Comment by j-mueller** [comment]
The idea makes sense, there isn't currently a way to change the initialising transaction. 

Another way to achieve this would be for `runInitialise`, `runStep` etc to return the constraints and lookups that are needed for the transition, and then caller could add their own constraints to that (or submit them without any changes). Maybe this would be nicer. Right now `submitTxConfirmed` is buried in the other functions.

**Comment by anton-k** [comment]
Updated `runStep` & others to work on top of `runXxxWith` variants

**Review by ak3n — APPROVED** [review]

**Comment by anton-k** [comment]
Actually this test also fails on the tip of the origin/master

**Comment by ak3n** [comment]
@j-mueller I agree, it might be nicer, but it might cause a major refactoring. I suggest to merge the PR as it is, to extend the existing functionality a bit.

@anton-k yeah, hydra fails sometimes. Please, rebase the branch again to run the CI again.

**Comment by michaelpj** [comment]
I restarted the flaky job.

**Comment by ak3n** [comment]
@michaelpj Thanks!

**Comment by anton-k** [comment]
Thanks guys! I use it alot!

**Pull request merged**
