### PR TITLE
SCP 2364 Add time tracing for profiling

### PR DESCRIPTION
**Pull request by thealmarty**
Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by thealmarty** [comment]
\benchmark

**Comment by michaelpj** [comment]
This looks plausible to me!

**Comment by michaelpj** [comment]
I think the remaining bit to do would be to enhance the argument that we pass to `runCek` (https://github.com/input-output-hk/plutus/blob/master/plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs#L775) to something more expressive than a bool, so that we can express `NoEmit | Emit | EmitWithTimestamp`.

**Comment by thealmarty** [comment]
I ran `cabal bench benchmark:nofib` on my branch and compared it with master. See the results [here](https://gist.github.com/thealmarty/1baab37c6a3238a3d854ee8098c22750). It doesn't seem like my changes make things slower.

**Pull request closed without merging**
