### PR TITLE
Change the formatter fixing scripts to use find again

### PR DESCRIPTION
**Pull request by michaelpj**
Some time ago, I changed them to use `fd`, which is significantly
faster. However, `fd` recently changed its behaviour: it used to be that
it matched `find`, whereby it would keep going if any individual `exec`
command failed. Now it stops. This interacts badly with our formatters,
which don't like all the files in our repo, and occasionally fail on one
or the other. We would prefer this not to stop them formatting the rest
of the files!

So we switch back to using `find`, which is slower but does what we
want.

I also shared the fixing script between the shell function and the CI
check, so they will line up better.

(Annals of failed changes: originally this PR included a change to use `execdir`, because if `stylish-haskell` is run from the file's directory instead of the project root then it will read the language extensions from the cabal file and we don't need them in `.stylish-haskell.yaml`. However, we *do* still need them because HLS runs the formatter from the root, so this didn't gain us anything and I reverted it :upside_down_face: )

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Hm... I guess I could also have just made it call `stylish-haskell {} || true`, not sure why I didn't do that. `find` is quite slow...

**Comment by gilligan** [comment]
> Hm... I guess I could also have just made it call `stylish-haskell {} || true`, not sure why I didn't do that. `find` is quite slow...

I am not too happy that our solution is sucking up non-zero exit codes like that but as long as stylish-haskell is going to fail on completely valid Haskell code i see no other option.

**Review by gilligan — APPROVED** [review]
I don't know if you want to switch to the `|| true` as mentioned in your comment or not - but i'm fine with either i guess

**Comment by michaelpj** [comment]
Updated to the dumber solution, and checked, should work reasonably well now.

**Pull request merged**
