### PR TITLE
Exports Data&ExBudget from Api.Common

### PR DESCRIPTION
**Pull request by bezirg**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by bezirg** [comment]
I guess I have to release to ChaP , so the cardano-ledger can see it?

**Review by michaelpj — APPROVED** [review]
LGTM. Maybe worth doing a quick check of the ledger codebase to see if there's anything else they're importing from somewhere other than `PlutusLedgerApi`?

And yes, we'll need to do a release. Good opportunity for you to check whether the instructions make sense :)

**Comment by aniketd** [comment]
> Maybe worth doing a quick check of the ledger codebase to see if there's anything else they're importing from somewhere other than PlutusLedgerApi?

We seem to use `CostModelInterface (CostModelApplyWarn)` and `PlutusPrelude.enumerate` in addition to the ones already added, AFAICT. :slightly_smiling_face:

**Comment by michaelpj** [comment]
> PlutusPrelude.enumerate

this is just a re-export from `extra`, I suggest you get it from there.

**Pull request merged**
