### PR TITLE
restoring metatheory proofs after typechecking related refactoring

### PR DESCRIPTION
**Pull request by jmchapman**
What needs fixing:

- [x] algorithmic renaming/substitution
- [x] algorithmic reduction/evaluation
- [x] declarative syntax
- [ ] declarative renaming/reduction
- [ ] correspondence between declarative/algorithmic syntax.
- [ ] correspondence of the above with erasure to untyped syntax.

What's already working:
Extrinsic evaluation and type checking that produces an intrinsically typed (algorithmic) term as evidence of success. And things which depend on these things.

### CODE REVIEW

**Comment by jmchapman** [comment]
I am wondering whether this is becoming too awful. Roman suggested separating the names from the types/terms. I could try to do this with a skeleton (a *naming*) that has the same structure as the types/terms but contains only bound variable names. I initially thought that this would mean i would have to lift tons of operations to work on pairs of namings and terms, but perhaps this is worth it if I can isolate a large chunk that can use nameless syntax without having to worry about names at all. I changed the intrinsically typed syntax to suit the typechecker but perhaps I should instead change the typechecker. I might then not have to butcher the metatheory so badly.

**Comment by jmchapman** [comment]
I am going to abandon this pull request.

**Comment by jmchapman** [comment]
created a branch jmchapman/alphaequality. going to store this experiment there before trying something else.

**Comment by effectfully** [comment]
> I could try to do this with a skeleton (a naming) that has the same shape as the type/term but contains only bound variable names. 

Sounds quite complicated to me. I'm not sure it'd simplify anything. Your De Bruijn indices are well-scoped/well-typed, right? You could just require a name for each context entry regardless of whether it's actually used as a variable or not.

Have you tried using the locally nameless representation? I'm not sure if it's going to help either, but might be worth investigating.

**Comment by jmchapman** [comment]
I will look into locally nameless stuff, thanks. My hope is that I can preserve the current nameless stuff which is quite nice. The type checker has to do some additional work to preserve the users names, but this is isolated and doesn't pollute everything. My current representation is well-scoped and typed. I have added names (strings) at binding sites (e.g, lambda). The problem is then that you when you want to reason about types or terms you cannot use propositional equality which is a huge pain. Lots of stuff relies on the fact that you can use propositional equality.

**Comment by effectfully** [comment]
> The problem with this is that you when you want to reason about types or terms you cannot use propositional equality which is a huge pain. Lots of stuff relies on the fact that you can use propositional equality.

Yeah, I remember what the problem is. I'm just curious whether supplying names for each of the context entries via an environment might solve this problem. That solution seems simpler than storing names in a structure of the same shape as a particular type/term. But I'm of course not sure if it's going to work.

**Pull request merged**
