### PR TITLE
[Builtins] Added a lazy version of 'withEmit'

### PR DESCRIPTION
**Pull request by effectfully**
Our current logging machinery only returns something when the program finishes. But people may want to use logging for debugging programs that hang. And it's just natural to see something immediately after you've logged it. This PR adds a lazy version of `withEmit` that allows to stream emitted elements lazily. I do not include tests, because it's unclear how a sensible test should look like (and because I do not have much time), but I did run some not very sensible tests and they show that indeed emitted elements are streamed lazily and everything behaves correctly for the non-hanging case. The new function is not used by anything, it's just there in case someone would ever need it. However it's rather unsafe (not to mention how horrible it is) and results in thread leakage being called on a program that runs indefinitely. I tried to fix that, but it appears to be surprisingly tricky. Anyway, this version might be helpful to someone.

### CODE REVIEW

**Comment by effectfully** [comment]
I again do not see the output of CI. Why does it fail?

**Comment by michaelpj** [comment]
Click `Details`, then it says "1 out of 12 constituent builds failed", then click on `Constituents`, and you can see that stylish-haskell failed.

FWIW I'm not planning to use this and I don't think we're going to be able to debug hanging things in the playgrounds - they'll just get killed by a timeout most likely.

**Comment by effectfully** [comment]
Oh, thank you, that's a very useful advice.

Feel free to close the PR. I think it's nice to have this, even in a closed PR.

**Comment by michaelpj** [comment]
Okay, I think it's useful to have this recorded, but I'm not sure we want to maintain it until we need it. So let's leave it here for now.

**Pull request closed without merging**
