### PR TITLE
WIP update plutus-metatheory documentation

### PR DESCRIPTION
**Pull request by jmchapman**
By documentation I mean the clickable html rendering of the Agda code mostly.

The aim of this PR is to fix these problems
1. The README is out of date
2. I am not taking advantage of the support for .lagda.md to make nice looking clickable content that looks similar to the https://plfa.github.io/. Only a few files use this format and there is little commentary in the agda files.
3. This is also an opportunity for some general tidying. Especially using `variable` to cleanup type sigs a lot.

Plan:
1. Update README and turn it into installation instructions and a summary.
2. Turn the Everything.lagda file into a table of contents with an explanation of the structure.
3. Start to add to inline commentary in each agda file and convert files to .lagda.md format.

Current approach:
Get Agda to generate markdown files where the code blocks have been marked up (i.e., converted to html) but the rest hasn't. Use jekyll to generate a static html site from the markdown files. Use gh-pages to serve the site.
- Jekyll site source: https://github.com/input-output-hk/plutus-metatheory/tree/jekyll
- generated site source: https://github.com/input-output-hk/plutus-metatheory/tree/gh-pages
- Rendered output: https://input-output-hk.github.io/plutus-metatheory/

Alternative/approved approaches:
There is no particular reason to use jekyll to generate html from markdown. Some other tool could be used or I think gh-pages could do this step itself. Or perhaps readthedocs/sphinx could be used instead.

Progress:
- [x] Manually generate nice html from .lagda.md style literate agda
- [x] Update README
- [x] Update Table of Contents
- [x] Update Types
- [x] Update builtins
- [x] Update Declarative Terms

For another PR:
- [ ] Automate

To be done when these files are touched for other reasons:
- [ ] Update Normal types (might delay until eta question is resolved)
- [ ] Update Algorithmic Terms
- [ ] Update Well-scoped terms
- [ ] Update Untyped terms
- [ ] Update type checker
- [ ] Update plc-agda

### CODE REVIEW

**Comment by michaelpj** [comment]
We can probably set up a nice nix expression for this and stick it somewhere. I'm not sure how much the Jeykll site adds: you can just put raw HTML on GH pages, which I think would probably look better than the awkward blog frontend.

**Comment by jmchapman** [comment]
> We can probably set up a nice nix expression for this and stick it somewhere. 

That would be great! This was just a first step.

> I'm not sure how much the Jeykll site adds: you can just put raw HTML on GH pages.

My intention was to just using jekyll as to generate .html files from .md files with the default theme. I am serving raw html on gh pages.

> which I think would probably look better than the awkward blog frontend.

I guess there are other jekyll themes I could use or I am happy to use some other tool to generate html from markdown. Phil and Wen's book looks pretty nice I think: https://plfa.github.io/Induction/.

**Comment by michaelpj** [comment]
Hm okay, I guess I don't know how the HTML gets generated normally. Don't you need to do some generation in order to get the clickable links etc working?

**Comment by jmchapman** [comment]
> Hm okay, I guess I don't know how the HTML gets generated normally. Don't you need to do some generation in order to get the clickable links etc working?

You start with a literate Agda file `MyFile.lagda.md`. Agda can convert this to `MyFile.md` which converts the code blocks to html with clickable links and leaves the surrounding commentary intact. You can then convert this to html with some other tool (e.g., jekyll).

**Comment by michaelpj** [comment]
Huh, it actually generates markdown rather than HTML? Interesting. We do then have to decide what we do with it to get the markdown then, I guess.

**Comment by jmchapman** [comment]
rather annoyed I forgot to remove "WIP" from the title before merging :(

**Pull request merged**
