### PR TITLE
Get current git revision using IFD if we are not on Hydra

### PR DESCRIPTION
**Pull request by michaelpj**
This is much more reliable than looking inside `.git`, which can be in
weird states and is best not to make assumptions about.

Wonderfully, since Nix is lazy, we can do this despite IFD being
disallowed on Hydra: in that case we'll have `declInput` so we'll never
evaluate the bit that needs IFD.

XXX: does not work for worktrees yet

### CODE REVIEW

**Comment by michaelpj** [comment]
> Perhaps there is a way to override when using work trees or alternatively just wait until someone tries to use a worktree and it fails and then think about fixing it.

I use worktrees but I don't build the playground server so often so I can live with it. Could also do an override.

**Comment by michaelpj** [comment]
Okay, I think this now works.

I am a bit aware of the downsides: every PR (including doc-only PRs) will now rebuild the playground jobs (which are slow!) on every commit. I wonder if we could somehow only apply the overlay when we're building them for the docker images?

**Comment by shmish111** [comment]
this is essential in the deployed versions as well I think

**Comment by michaelpj** [comment]
Sure, I just want a "deployed version" derivation that's only referenced from those rather than from every time we do anything.

**Comment by michaelpj** [comment]
I guess that would actually work fine - i.e. we can do the derivation overriding that we do in the overlay separately. We'd need it in the overlay if there were packages that depended on the playground packages, but there aren't.

**Comment by michaelpj** [comment]
But that can be future work.

**Comment by shmish111** [comment]
agreed, I was just typing something similar.

**Pull request merged**
