### PR TITLE
Wide word array

### PR DESCRIPTION
**Pull request by michaelpj**
Just for benchmarking atm.

### CODE REVIEW

**Comment by michaelpj** [comment]
Holy shit wow.

**Comment by kwxm** [comment]
Nice. We should merge this immediately.

**Comment by michaelpj** [comment]
?????

I swear I tried this when I did this originally and it was worse. WTF.

**Comment by bezirg** [comment]
Why this is closed? it does not work in the end?

**Comment by michaelpj** [comment]
It had terrible performance and we already merged the primarray version.

**Pull request closed without merging**
