### PR TITLE
plutus-tx: split out plutus-tx-plugin

### LINKED ISSUE #1790: Isolate `ghc` dependency
This is problematic in a cross setting. We only need it for the plugin, and the plugin will be provided otherwise when doing cross.

So the plan is:
- Split out `plutus-tx-plugin`.
- Wrangle the dependencies so it *only* contains the plugin stuff.
- Make all the `plutus-tx-plugin` dependencies conditional on `impl(ghcjs) && os(ghcjs)`.

### PR DESCRIPTION
**Pull request by michaelpj**
Fixes #1790.

This pulls out the compiler plugin into its own package that just has
the stuff that depends on `ghc` in it (so: the compiler and the plugin
itself).

The dependencies on `plutus-tx-plugin` are gated by "not compiling with
GHCJS". This is important for cross-compilation: the plugin really needs
to be provided as a native dependency and won't work when
cross-compiled. So we need another mechanism for supplying it (which
Moritz has), and we need to *not* try and provide it the normal way.

All the stuff that doesn't depend on `ghc` is in `plutus-tx`, so `plutus-tx-plugin` also
depends on `plutus-tx`. As a nice side-effect, this means that many
things don't actually depend on the plugin, improving our build
parallelism a bit.

(Another bonus: now `plutus-tx` doesn't have an internal library any
more, which is what was causing the issue with the package occasionally
appearing as hidden in the playground interpreter. So we can delete a
FIXME.)

### CODE REVIEW

**Comment by michaelpj** [comment]
This should be ready to go, just waiting for Moritz to have a look and check if it does what he wants.

**Comment by luite** [comment]
Looks like a good idea to split the plugin from the library, but I haven't tested this change myself yet.

Note that due to limitations of the GHC Hooks we actually still need the name `plutus-tx-plugin:Language.PlutusTx.Plugin.plugin` to be available in the packages for our (cross compiled) target. The only thing it is used for is avoiding the "not found" error, the compiler then tries to load the name name from the build platform package db.

I hope we can soon get rid of this requirement by making the appropriate changes in upstream ghc, but it will take a while before that's generally usable.

An alternative would be to conditionally swap the plugin for a "stub" plugin. GHCJS does have a `ghc` package that just provides a `Plugins` module to allow `Language.PlutusTx.Plugin.plugin` to be defined with the correct type, but doesn't have anything else.

**Comment by angerman** [comment]
I think we should just for the time being nuke the ghc-stub then and add a plugin-stub which explicilty mentiones that it's there fore plugin finding reasons. The stub should be part of #1749, not this PR. So I'm good with this!

**Comment by luite** [comment]
sounds good. I'm trying to recall why I went the ghc-stub route, rather than limiting the plugin. I think it was really just for ease of rebasing.

I do think that eventually moving the plugin out to a separate package is the nicest way to fix it. Shall we make the plugin-stub first and come back to this and make the bigger changes once we have a way to test it?

**Comment by michaelpj** [comment]
Plugin-stub sounds good - much smaller and easier to stub out than `ghc`!

I'd prefer to do this now since it's disruptive. If the approach seems sound then hopefully we can iron out the wrinkles later.

**Pull request merged**
