### PR TITLE
Kwxm/more spec improvements

### PR DESCRIPTION
**Pull request by kwxm**
Let's try that again...

### CODE REVIEW

**Comment by michaelpj** [comment]
Are you using sandboxing? If not it might be picking up stuff from your system. Maybe you have other latex packages installed somewhere?

**Comment by kwxm** [comment]
Ah, it seems not to be finding the `float` package.  I'll look into this sandboxing business.

**Comment by michaelpj** [comment]
You probably need to figure out which texlive collection it's in and add that to `default.nix`. If I remember correctly Texlie makes it amazingly difficult to find out what collections a package is in...

**Comment by kwxm** [comment]
Yes, I'm just discovering that.

**Comment by kwxm** [comment]
I added collection-latexrecommended to plutus-core-spec/default.nix because latexmk wasn't finding the `float` package.  This didn't help: it apparently still couldn't find it despite the fact that the log file showed that it had seen `float.sty`.  Here's an attempt at adding `float.sty` directly to the spec source directory to see if that does any good.

**Comment by kwxm** [comment]
Nope, no good.  The log file shows that it found `./float.sty`instead of the global one, but it still doesn't realise that it's supposed to be using the new `float` command.

**Comment by kwxm** [comment]
After reinstalling texlive, it transpires that I get the same error with texlive 2018, but didn't get it with texlive 2014.  I'll look into this tomorrow.

**Comment by kwxm** [comment]
I think this is fixed now.  I', using the `float` package which provides an `[H]` option to force figures to be placed exactly where the `\begin{figure}[H]` command appears.  You're not supposed to use `H` with any of the other placement specifiers like `!`, `h`, `t` etc, but I'd accidentally done that when I was fiddling with placements.  This didn't cause a problem with older versions of texlive, but it does with the current one.  I've fixed that and the document now compiles in CI.  I'm going to merge it before anything else goes wrong.

**Pull request merged**
