### PR TITLE
Fix `lt` and `gt` for `Value`s

### LINKED ISSUE #4707: Wrong semantics for `PlutusLedgerApi.V1.Value.gt` and `lt`
### Summary

I stumbled upon this bug while working on Hachi's [dynamic analysis toolkit for Plutus Core](https://blog.hachi.one/post/an-overview-of-hachi-s-security-toolkit-for-plutus-core/). Thank you @sjoerdvisscher for the very quick confirmation!

Everything is in the title. The implementations of `gt` and `lt` lead to curious behaviours where:
- `gt` is *not* the same as ~`not leq` or~ `geq and not eq` (edit: scratch `not leq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))
- `lt` is *not* the same as ~`not geq` or~ `leq and not eq` (edit: scratch `not geq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))
- `gt` and `lt` can change behaviour when adding zeroes in their `Value`s

I have not tried, but I feel it might actually lead to validators written in a defensive way (eg. “if the value is lower than this threshold then raise an error”) accepting values which they really should not as long as these values mention additional currencies at 0. I'll try to come up with a toy example at some point.

### Steps to reproduce the behavior

```haskell
$ nix-shell --run 'cabal repl plutus-ledger-api:plutus-ledger-api'
> :set -XOverloadedStrings
> import PlutusLedgerApi.V1.Value
> import PlutusTx.AssocMap qualified as Map
> cs1 = CurrencySymbol "CS1"
> cs2 = CurrencySymbol "CS2"
> tn1 = TokenName "TN1"
> tn2 = TokenName "TN2"
> v1 = Value $ Map.singleton cs1 $ Map.singleton tn1 33
> v1' = Value $ Map.fromList [(cs1, Map.singleton tn1 33), (cs2, Map.singleton tn2 0)]
> v1 == v1'
True
> v2 = Value $ Map.singleton cs1 $ Map.singleton tn1 22
> v1 `gt` v2
True
> v1' `gt` v2
False                                  -- here!
> v1' `geq` v2 && not (v1' == v2)
True
```

### Actual Result

- `v1` is equal to `v1'` as expected,
- `v1` is greater than `v2` as expected,
- but `v1'` is *not* greater than `v2`.

### Expected Result

`v1'` is equal to `v1` and should therefore behave in the same way. In this case, it should probably also be greater than `v2`. `gt` should also be logically equivalent ~to `not leq` and~ to `geq and not eq`.  (edit: scratch `not leq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))

### Describe the approach you would take to fix this

The issue comes from the fact that `gt` (and similarly `lt`): https://github.com/input-output-hk/plutus/blob/1877215dff03ceaf2c6d5882dd9e0fff8edab143/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L348-L352 relies on `checkBinRel`: https://github.com/input-output-hk/plutus/blob/1877215dff03ceaf2c6d5882dd9e0fff8edab143/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L330-L340 which “[checks] whether a binary relation holds for value pairs of two `Value` maps, supplying 0 where a key is only present in one of them.” In the case where a key is present in only one of them, bound to a value of `0`, the binary relation will then be checked on `0` and `0`. For `(<)` and `(>)`, this will then trivially fail.

I see three approaches to fix it:
1. `gt` could simply be defined ~as `not leq` or~ as `geq and not eq`,  (edit: scratch `not leq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))
2. `gt` could eliminate all bindings leading to `0` before calling `checkBinRel`, or
3. `gt` could rely on an alternative version of `checkBinRel` that does not call its predicate argument in case of `This 0`, `That 0` and `These 0 0`.

### System info

OS: NixOS unstable
Commit: tested on last commit on `master` as we speak: 1877215dff03ceaf2c6d5882dd9e0fff8edab143

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Fixes #4707

It would be nice to have a testcase that generates values, adds a currency with amount 0, and checks that the comparisons still have the same value. But since there isn't a generator for Values (right?) I skipped this.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
Yes, it would be great to have a better test suite for `Value`, ideally with property-based tests. I won't ask you to do that, though, unless you want to :)

**Review by michaelpj — APPROVED** [review]

**Comment by michaelpj** [comment]
Once this is merged, would you mind opening a backport PR cherry-picking it to `release/1.0.0`?

**Comment by sjoerdvisscher** [comment]
@michaelpj I tried, but "The push was rejected by the remote server because a required status check has not been satisfied."

**Comment by michaelpj** [comment]
I think you did what I wanted you to do; what did you try to do that didn't work?

**Comment by sjoerdvisscher** [comment]
I missed the "PR" part initially and tried to push directly to the release branch.

**Comment by michaelpj** [comment]
Branch protection working as intended :)

**Comment by Niols** [comment]
For reference, the PR that cherry-picked this to `release/1.0.0` is https://github.com/input-output-hk/plutus/pull/4711.

**Pull request merged**
