### PR TITLE
[Builtins] Introduce 'HiddenValueOf'

### PR DESCRIPTION
**Pull request by effectfully**
A rebase of #4243, which was based on #4200.

### CODE REVIEW

**Comment by effectfully** [comment]
So the best I can do here is 0-2% speedup, it seems. Not sure if it's worth the additional complexity. But having that `HiddenValueOf` is more flexible than what we have currently, e.g. it's quite easy to extend `HiddenValueOf` with budgeting info to optimize costing of lists etc.

**Comment by michaelpj** [comment]
> But having that HiddenValueOf is more flexible than what we have currently, e.g. it's quite easy to extend HiddenValueOf with budgeting info to optimize costing of lists etc.

I'm not quite sure I follow. You mean so we can have a cached memory usage computation in the value? but couldn't we do that arleady?

I'm not sure I want flexibility that we don't currently use, and this is _quite_ a bit more complicated...

**Comment by effectfully** [comment]
> I'm not quite sure I follow. You mean so we can have a cached memory usage computation in the value? but couldn't we do that arleady?

We can, but in a much less convenient way. Currently if you want to attach something to a type, you have to create a new type and put that one into the universe (and remove the old one). This is due to constants being stored in `Some (ValueOf uni)` with `ValueOf` being

```haskell
data ValueOf uni = forall a. ValueOf !(uni a) !a
```

i.e. any value of a built-in type has to be stored as is without any annotations and the type of that value has to appear in the unvierse.

With the current PR "what we can support" and "how things are represented" are decoupled, so it's easy to change the representation of a type without touching the universe at all. This is quite more flexible and allows us to change the internals without breaking any API.

**Comment by thealmarty** [comment]
I vote to keep things simple unless we *need* the flexibility now. (Yes I'm a YAGNI person)

**Comment by effectfully** [comment]
Let's close that for now, it conflicts with everything anyway.

**Pull request closed without merging**
