### PR TITLE
PLT-355: Add hlint to CI

### PR DESCRIPTION
**Pull request by zliu41**
Currently only one hint is enabled: Unused LANGUAGE pragma, and it only checks against PlutusCore.* modules, because we have too many unused pragmas to fix in one PR.

### CODE REVIEW

**Review by effectfully — APPROVED** [review]
Not too many of them actually!

**Comment by michaelpj** [comment]
I think normally we would set this up as a test that runs in Nix, but I see that the action has some nice effects in terms of how it presents the results, so I guess I'm fine with it.

Did you want to tell it to sometimes fail, so that it actually acts as a gate?

Also, you should update `CONTRIBUTING`.

**Comment by zliu41** [comment]
> Did you want to tell it to sometimes fail, so that it actually acts as a gate?

It fails if there are one or more hints. I don't know whether failure blocks merging or not; I don't have access to the merge settings of this repo.

**Comment by michaelpj** [comment]
Oh I see. Why not use https://github.com/rwe/actions-hlint-run? That puts the hints in as github annotations, and has a configurable `fail-on` field.

**Comment by zliu41** [comment]
> Why not use https://github.com/rwe/actions-hlint-run?

It doesn't seem to support specifying the `--hint` argument, which means it would use `./.hlint.yaml` :unamused:

**Comment by michaelpj** [comment]
You can do that by setting `hlint-bin`, see e.g. https://github.com/haskell/haskell-language-server/blob/master/.github/workflows/hlint.yml

**Comment by zliu41** [comment]
> You can do that by setting hlint-bin

Oh, good to know!

**Pull request merged**
