### PR TITLE
[Builtins] Use '-fpedantic-bottoms' for costing

### PR DESCRIPTION
**Pull request by effectfully**
I've found the right flag finally.

### CODE REVIEW

**Comment by michaelpj** [comment]
Needs a note, obviously. But interesting!

**Comment by effectfully** [comment]
+0.5% (i.e. noise). I don't like it. `-fpedantic-bottoms` works until it doesn't (while calls to `lazy` are reliable), generates loads of annoyingly asymmetrical Core and doesn't give us any speedup. I'll mention it in the docs, but I'm going to keep the current solution.

**Comment by effectfully** [comment]
Not doing. Mentioned in #4626.

**Pull request closed without merging**
