### PR TITLE
Various post 19.09 improvements

### PR DESCRIPTION
**Pull request by michaelpj**
- Use niv for managing pins.
   - I've wanted to use this for a while, it should make updating things simpler.
   - Also gets rid of the `nativePkgs` nonsense.
   - We have a remaining JSON spec for nixpkgs due to https://github.com/input-output-hk/iohk-nix/pull/215.
- Move various bits that override stuff into overlays.
- Clean up `purty`, we can now get it from the main haskell packages with a bit of overriding.
    - Could someone on macOS confirm I haven't broken it?
- Slightly improve asciidoctor stuff, annoyingly I can't quite use the upstream because of a patch.

There's this deployment nixpkgs copy lying around that it would be nice to get rid of. @shmish111, given we're following an upstream nixpkgs 19.09 commit with cached stuff, would it be okay to use the same pin now, or do you want it on a controlled pin that you advance separately?

### CODE REVIEW

**Comment by michaelpj** [comment]
Gonna see if hydra likes this, then I'll probably try and sneak in a stackage snapshot bump too.

**Comment by shmish111** [comment]
This all looks really nice. I can't think of a reason that the deployment nixpkgs should be different, only if we wanted to upgrade the machines more quickly than we're upgrading everything else however since we haven't done this so far I don't think we need to worry about that.

**Comment by michaelpj** [comment]
> I can't think of a reason that the deployment nixpkgs should be different, only if we wanted to upgrade the machines more quickly than we're upgrading everything else

Or more slowly! We might not want to upgrade e.g. terraform. I'll leave it as is for now.

**Comment by shmish111** [comment]
me too, I forgot, I'm up to `1/143/146 built`. Good for us to both test since we seem to have had different issues in the past.

**Comment by michaelpj** [comment]
Hang on, aren't you getting cache hits? It should be building stuff on darwin.

**Comment by shmish111** [comment]
sorry forget that, I was on the wrong branch and now I see this branch is on your repo @michaelpj so I won't be able to push anything if there are issues

**Comment by michaelpj** [comment]
> I was on the wrong branch and now I see this branch is on your repo @michaelpj so I won't be able to push anything if there are issues

You should be able to push to it, I think, I have the "allow edits from maintainers" button ticked.

**Comment by shmish111** [comment]
```
diff --git a/nix/purescript.nix b/nix/purescript.nix
index c64449c85..24488d7b2 100644
--- a/nix/purescript.nix
+++ b/nix/purescript.nix
@@ -25,7 +25,7 @@ let
   };
   nodeSassBinDarwin = fetchurl {
     url = "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-64_binding.node";
-    sha256 = "04m3lpqapsx1nsaz7xr6k0yr64car1447v5gf6x6sfiszmshvjw2";
+    sha256 = "1p5gz1694vxar81hbrrbdmmr2wjw3ksfvfgwh0kzzgjkc2dpk5pa";
   };
   webCommon = pkgs.copyPathToStore webCommonPath;
 

```

**Comment by michaelpj** [comment]
Weird that it built on hydra with that wrong.

**Comment by michaelpj** [comment]
Ah, we only build the client on linux, that's why.

**Pull request merged**
