### PR TITLE
Expose ExBudgetingDefaults

### PR DESCRIPTION
**Pull request by nc6**
Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Why? The idea is that everything that you need should be exported from `Plutus.V1.Ledger.Api`. If you need something else, let's re-export it from there.

**Comment by nc6** [comment]
It's only used in testing, but I'm happy if you'd rather export it from the API

**Comment by michaelpj** [comment]
Yes please. I want to keep a _really_ close eye on what we expose.

**Comment by michaelpj** [comment]
Here, please: https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs#L13

In fact, I think it should be there, I think Kenneth may have lost it recently!

**Comment by kwxm** [comment]
> In fact, I think it should be there, I think Kenneth may have lost it recently!

In #3179 I made it so that the stuff in`ExBudgetingDefaults` was exported from `PlutusCore` instead at @michaelpj 's suggestion.  In this PR Examples.hs now has 

```
 import qualified PlutusCore                                        as PLC
 import           PlutusCore.Evaluation.Machine.ExBudgetingDefaults (defaultCostModelParams)
```

so I think it should be possible to use `PLC.defaultCostModelParams` instead of importing `ExBudgetingDefaults`.  

Some of the stuff that was previously in `ExBudgetingDefaults` may also have moved to `PlutusCore.Evaluation.Machine.CostModelInterface`, which is also imported in `Api.hs`.

Sorry about the confusion.  I had to do some refactoring because of cyclic imports, but I hope this stuff won't change so much from now on.

**Comment by nc6** [comment]
Closing this since it seems this isn't the issue!

**Pull request closed without merging**
