### PR TITLE
SCP-3838: Add a type let test

### PR DESCRIPTION
**Pull request by zliu41**

### CODE REVIEW

**Review by effectfully — APPROVED** [review]
Yup, our `let`s are not transparent, i.e. a type variable bound by `let` must never escape its scope, even that variable is just a simple alias that would be easy to expand. Think how fancy a `let`-bound data type definition would have to look if we allowed the escaping. And if we decided to forbid escaping of data types, but allow escaping of type aliases, that would be rather inconsistent.

We've discussed this to death, I [personally](https://github.com/input-output-hk/plutus/pull/2061#issuecomment-1104496368) lean towards transparent `let`s (by means of viewing `let`-expressions as implicitly creating modules), but I also agree they're somewhat weird as others pointed out in the past. But maybe I'm saying nonsense and it does make sense for us to stay on the safe side.

While you're here, could you also add a test where the lambda is applied to `con integer 1` within the `let`?

**Comment by zliu41** [comment]
> While you're here, could you also add a test where the lambda is applied to con integer 1 within the let?

Done.

> And if we decided to forbid escaping of data types, but allow escaping of type aliases, that would be rather inconsistent.

I think the idea of allowing escaping of type aliases is so that we can perform more beta transformations, potentially allowing using the same logic optimize `Apply` and `TyInst`. This PR is part of SCP-2570. But your point of allowing data types to escape is an interesting one; it seems like it would lead to ill-typed programs, but if not then it may be worth doing.

**Comment by effectfully** [comment]
> This PR is part of SCP-2570.

Ah, I did not realize this was a part of a task (I wasn't even aware it existed), I thought you stumbled upon unexpected behavior and wrote a test for it.

OK then, it all makes sense.

**Comment by zliu41** [comment]
Added ticket number to the PR.

**Comment by michaelpj** [comment]
> And if we decided to forbid escaping of data types, but allow escaping of type aliases, that would be rather inconsistent.

Yeah, I'm proposing to become a bit inconsistent in this way!

**Comment by michaelpj** [comment]
Good tests!

**Pull request merged**
