### PR TITLE
Single-occurrence inlining mk IV

### PR DESCRIPTION
**Pull request by michaelpj**
Finally, we've got rid of all the issues it turned up, and it now
appears to work fine.

I also added a little bit of type inlining on the basis of similar
heuristics to terms: trivial types or single-occurrence types.

This does make things a bit slower, the Marlowe validator goes from
taking 1.7s to 3.4s. This *isn't* due to the type inlining, I tried
turning that off, it's just that we're inlining more stuff generally
now. We could still make the inliner faster (or be cleverer with
renaming), but it's not a catastrophic increase (and much lower than it
was before when we were unconditionally inlining all the types!).

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by ak3n** [comment]
I may try to profile the branch to get the flamegraph if needed.

**Comment by michaelpj** [comment]
> I may try to profile the branch to get the flamegraph if needed.

My guess is that we're just doing much more inlining, and the expensive bit of inlining is renaming :D

**Review by ak3n — APPROVED** [review]

**Comment by jakzale** [comment]
> > I may try to profile the branch to get the flamegraph if needed.
> 
> My guess is that we're just doing much more inlining, and the expensive bit of inlining is renaming :D

There are two options:
- implement the actual rapier from the paper,
- do everything under a source of uniques (probably the one from GHC is slightly faster).

Frankly, as the Inliner is giving me slight PTSD, I would probably go with the latter and stick everything in an `IO` monad.

**Comment by michaelpj** [comment]
> do everything under a source of uniques (probably the one from GHC is slightly faster).

We have that: it's exactly `MonadQuote`! The question is just whether renaming every binder as we go down the program is faster or slower than renaming terms before we put them into the program.

**Comment by jakzale** [comment]
> > do everything under a source of uniques (probably the one from GHC is slightly faster).
> 
> We have that: it's exactly `MonadQuote`! The question is just whether renaming every binder as we go down the program is faster or slower than renaming terms before we put them into the program.

Our `MonadQuote` is a `StateT` over a counter. I previosly used its abstract interface, which was recently fixed by @ak3n in #3850.

From what I know, GHC has two kinds of uniques:
- `Data.Unique` from base, which is roughly the same as ours, but uses `IO` instead of `StateT`, and
- `GHC.Types.Unique.Supply`, which is a splittable unique supply using lazy trees (the apporach mentioned in the paper).

I was wondering if the latter would be faster, as the unique supply can be splitted.

**Comment by ak3n** [comment]
I think that using `IO` vars may really help. As far as I remember it improved Idris's performance a lot. Found the link https://www.type-driven.org.uk/edwinb/why-is-idris-2-so-much-faster-than-idris-1.html

**Comment by michaelpj** [comment]
Could use a `STRef` as a non-IO version. Anyway, we can try this separately!

**Pull request merged**
