### PR TITLE
Make list and data ExMemoryUsage instances strict and tail-recursive (SCP-3065)

### PR DESCRIPTION
**Pull request by kwxm**
(Don't look at this yet)

### CODE REVIEW

**Comment by kwxm** [comment]
Hmmm.  [A couple of months ago](https://github.com/input-output-hk/plutus/pull/4216#discussion_r749395366) @effectfully mentioned that it might be more efficient to make the function that works out the memory size of a list for costing strict and tail recursive.  I tried that back then and it didn't make a lot of difference.  There's been an issue to to it properly for a while so I thought I'd quickly do that today, and also fix the function that works out the size of  a`data` object.  Unfortunately this seems to make things noticeably worse.  Any ideas?  Have I done something obviously stupid?

**Comment by michaelpj** [comment]
Looks reasonable to me, I guess it just doesn't matter much?

**Comment by kwxm** [comment]
> Looks reasonable to me, I guess it just doesn't matter much?

I might leave it unmerged then, since it seems to make things worse.  It's only 1% or so, but when you have multiple changes like that it starts to mount up.  I might experiment a little more though.

**Comment by kwxm** [comment]
Yeah, didn't really think that would help.

**Comment by kwxm** [comment]
Just experimenting a bit.  Now memoryUsage for lists and Data is tail-recursive but not strict.

/benchmark

**Comment by effectfully** [comment]
I think the definition for pairs is simply not tail-recursive. I'll look into it on the weekend or so.

**Comment by kwxm** [comment]
Let's try again.

/benchmark

**Comment by kwxm** [comment]
... and again.

/benchmark

**Comment by kwxm** [comment]
Oops, I didn't save all my changes the last time.

/benchmark

**Comment by kwxm** [comment]
OK, I'm just going to give up on this.  I thought it would be straightforward, but I tried a number of things and none of them led to any improvement.  In fact mostly they made things a little worse.

@effectfully If you have any ideas, please feel free to try them out.

**Comment by effectfully** [comment]
> @effectfully If you have any ideas, please feel free to try them out.

Given [this](https://github.com/input-output-hk/plutus/pull/4216) discussion I think there's just nothing to optimize here, all overhead is negligible? In any case, I'd write it the same way as you did in this [commit](https://github.com/input-output-hk/plutus/pull/4341/commits/359c11bf8ca96ed3aa767f728bb6d6f8dab19d36) except I'd inline the `let`s, since it's enough for the accumulator to be banged.

**Comment by kwxm** [comment]
I'm going to abandon this.  PR #4366 adds a comment to explain that it didn't help.

**Pull request closed without merging**
