### PR TITLE
[Builtins] [Evaluation] Introduce 'TypeSchemeRuntime'

### PR DESCRIPTION
**Pull request by effectfully**
This adds `TypeSchemeRuntime`, which is the same thing as `TypeScheme` except properly instantiated and without evaluation-irrelevant stuff. Should be faster.

I'm not able to build the benchmarks by the way, neither `stack` nor `cabal` works. Both give me this:

```
plutus-tx-plugin> /home/effectfully/code/iohk/plutus/plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:776:41: error:
plutus-tx-plugin>     Not in scope: type constructor or class ‘GHC.GenTickish’
plutus-tx-plugin>     Perhaps you meant one of these:
plutus-tx-plugin>       ‘GHC.Tickish’ (imported from GhcPlugins),
plutus-tx-plugin>       ‘GHC.Tickish’ (imported from CoreSyn)
plutus-tx-plugin>     Neither ‘Class’, ‘CoreSyn’, ‘CostCentre’, ‘GhcPlugins’,
plutus-tx-plugin>             ‘MkId’ nor ‘PrelNames’ exports ‘GenTickish’.
plutus-tx-plugin>     |
plutus-tx-plugin> 776 | getSourceSpan :: Maybe GHC.ModBreaks -> GHC.GenTickish pass -> Maybe GHC.RealSrcSpan
plutus-tx-plugin>     | 
```

### CODE REVIEW

**Comment by effectfully** [comment]
> I'm not able to build the benchmarks by the way, neither `stack` nor `cabal` works. Both give me this: <...>

Anyway, the validation benchmarks do build.

**Comment by michaelpj** [comment]
That build failure ties into an earlier mystery, which I now believe I know the source of. But probably can't fix immediately.

**Comment by michaelpj** [comment]
If you use the GHC from nix it will work.

**Comment by michaelpj** [comment]
Seems to have broken tracing.

**Comment by effectfully** [comment]
> Seems to have broken tracing.

It did, which is how #4230 exists.

**Comment by michaelpj** [comment]
> It has, which is how #4230 exists.

Too oblique :p Does that PR fix it?

**Comment by effectfully** [comment]
> Too oblique :p Does that PR fix it?

Yup, now that I merged master in.

**Comment by michaelpj** [comment]
Maybe also slower? https://github.com/input-output-hk/plutus/pull/4244#issuecomment-979971058

I hope this is doing the right thing... I note that it might not be, since it's comparing the base of the PR with the tip, and the tip has master merged in. So if there was a regression on master I think the benchmarking job might pick it up. Better to rebase!

**Comment by effectfully** [comment]
Superseded by #4246.

**Pull request closed without merging**
