### PR TITLE
Add memory limits to playground interpreter processes

### PR DESCRIPTION
**Pull request by michaelpj**
Done by setting `GHCRTS`, which is apparently the most reliable way to do this when using `runghc`. 2GB should be enough for anyone :trollface: 

This stops my branch from OOMing these tests, instead it just takes forever, presumably because GHC is GCing furiously to stay below the limit.

Also some minor fixes to the interpreter project, most importantly the license.

### CODE REVIEW

**Comment by shmish111** [comment]
Does this affect the performance of the playground tests?

**Comment by michaelpj** [comment]
They complete fine with 1gb atm, so I doubled it to give them headroom.

**Comment by shmish111** [comment]
I mean are they fast?

**Comment by michaelpj** [comment]
I don't think they're any slower than they were...

**Comment by michaelpj** [comment]
Let me check.

**Comment by michaelpj** [comment]
Argh this stupid package db bug is really aggravating...

**Comment by michaelpj** [comment]
Takes about 30s on my machine both with this and on master. Which is too long, but that's another kettle of fish.

**Comment by shmish111** [comment]
ok, well I suppose merge this PR because it in itself isn't detrimental.

**Comment by michaelpj** [comment]
This PR is currently broken because of some variant on the stupid package db bug which I haven't figured out yet.

**Comment by michaelpj** [comment]
Okay, I now know what's wrong with this. The nixpkgs Haskell builder sets `GHC_PACKAGE_PATH` so that random invocations of GHC get the packages. This PR sets the environment for the `runghc` call, which stops it inheriting from the parent, and hence stops it getting `GHC_PACKAGE_PATH`.

This is very annoying. I'm not sure what best to do here: I could make it run a shell command instead, setting the RTS options there? Thoughts @shmish111 ?

**Comment by shmish111** [comment]
Add it in https://github.com/input-output-hk/plutus/blob/master/default.nix#L160 ? It is after all platform dependent. Not sure how you would do this with stack/cabal for local development though.

**Comment by shmish111** [comment]
if you want to be super-nasty you could create an env-var that contains all the env vars (or their values anyway) and read that in then set the proper env vars correctly in Haskell?

**Comment by michaelpj** [comment]
Hm yes, that would work except not for running the tests locally which is where I have the actual problem...

**Comment by michaelpj** [comment]
Okay, I'm using your suggestion and I'll just set it manually myself when I'm running tests, that's not too bad.

**Pull request merged**
