### PR TITLE
Update nixpkgs to 18.09 WIP

### PR DESCRIPTION
**Pull request by jbgi**
based on @michaelpj branch.
- Use `stack2nix` from nixpkgs
- Fix `doHaddockHydra` for doc output changes

The outstanding WIP is getting https://github.com/input-output-hk/nixpkgs/pull/11 merged and cached by hydra (otherwise initial build take 1 or 2 hours).

### CODE REVIEW

**Comment by michaelpj** [comment]
I don't quite understand why we depend on that being merged? Won't the CI for this PR cause hydra to build all the prerequisites, after which everything should be fast?

**Comment by jbgi** [comment]
ah right, CI should cache everything. Though it's probably best to wait for the PR to be merged to avoid master depending on a pending commit.

**Comment by michaelpj** [comment]
In what sense does it depend on a pending commit? I'm confused - does the commit this pins to not exist in the IOHK fork yet? It seems that it does, otherwise nothing would work.

**Comment by michaelpj** [comment]
I have no idea what's up with the darwin problems, though.

**Comment by jbgi** [comment]
> In what sense does it depend on a pending commit?

it is in the iohk repo but not in the main ìohk-18.09` branch yet.

**Comment by michaelpj** [comment]
Okay, I'm not sure why that matters. If we want to track `iohk-18.09` let's just change the pin to point to that.

**Comment by michaelpj** [comment]
One thing I've noticed with this which is a little annoying is that now the Haskell infrastructure builds things with profiling by default. Which amounts to compiling everything twice. This is a bit of a pain if you're using `nix` locally, but not sure what we should do about it. We could control it with an arg that you can set locally?

**Pull request closed without merging**
