### PR TITLE
Bump HLS to 1.8

### PR DESCRIPTION
**Pull request by michaelpj**
Let hydra go at this.

### CODE REVIEW

**Comment by michaelpj** [comment]
Linux built, tested locally and it works. Just waiting for darwin to build on hydra.

**Review by zeme-iohk — APPROVED** [review]

**Comment by jbgi** [comment]
I think this PR silently removed all windows jobs: https://hydra.iohk.io/eval/1284943#tabs-removed
related upstream issue: https://github.com/input-output-hk/haskell.nix/issues/1666

**Comment by jbgi** [comment]
Fix in https://github.com/input-output-hk/plutus/pull/4881/files

**Comment by michaelpj** [comment]
The `haskell.nix` bump just made things silently not work any more??? :scream:

**Pull request merged**
