### PR TITLE
[Builtins] Add an inlinable version of 'GEq'

### PR DESCRIPTION
**Pull request by effectfully**
Don't look here yet.

### CODE REVIEW

**Comment by effectfully** [comment]
-1.24% on average. Not a huge speedup, but is very cheap and removes the annoyance of seeing a clear optimization opportunity in the generated Core, so I'm going to pursue it.

**Comment by effectfully** [comment]
Actually, thinking about it... The idea is trivial, but the implementation is some pretty annoying boilerplate, plus there are three ways to implement what's in here, all subtly different, all for 1.7% speedup that we'll get anyway if we just make `ValueOf` a data family. I'm now leaning on the side of closing this one. @michaelpj what do you think?

**Comment by michaelpj** [comment]
Yeah, I'm happy to drop this.

**Pull request closed without merging**
