### PR TITLE
[Builtins] 'oneShot' 'readKnown' calls

### PR DESCRIPTION
**Pull request by effectfully**
Removes a whole bunch of redundant allocation from the generated Core.

### CODE REVIEW

**Comment by effectfully** [comment]
Interesting!

Screenshot from 2022-05-17 02-51-35

**Comment by michaelpj** [comment]
WTF

**Comment by effectfully** [comment]
OK, so the thing is, without `oneShot` GHC thinks that a part of a builtin can be reused and generates stuff like this:

```haskell
lvl44_r3XaC
  = \ x_a3bJw ->
      case x_a3bJw of {
        __DEFAULT -> lvl43_r3XaB;
        VCon val_a3cx4 ->
          case val_a3cx4 `cast` <Co:8> of { ValueOf uniAct_s3Qqz x1_s3QqA ->
          case $fGCompareTYPEDefaultUni_$cgeq
                 $WDefaultUniBool (uniAct_s3Qqz `cast` <Co:8>)
          of {
            Nothing ->
              Left
                (KnownTypeUnliftingError
                   (typeMismatchError
                      ($fGShowTYPEDefaultUni_$cshowsPrec `cast` <Co:6>)
                      ($WDefaultUniBool `cast` <Co:9>)
                      uniAct_s3Qqz));
            Just ds1_a3bJr ->
              case ds1_a3bJr of { Refl co8_a3bJu ->
              Right
                ((\ x2_a3bJE ->
                    let {
                      lvl289_s3QqB
                        = case x2_a3bJE of dt28_X3aHR { __DEFAULT ->
                          MakeKnownSuccess dt28_X3aHR
                          } } in
                    Right
                      ((\ x3_a3bJO ->
                          Right
                            ((Lazy
                                (case x1_s3QqA `cast` <Co:3> of {
                                   False -> $WMakeKnownSuccess x3_a3bJO;
                                   True -> lvl289_s3QqB
                                 }))
                             `cast` <Co:15>))
                       `cast` <Co:34>))
                 `cast` <Co:64>)
              }
          }
          }
      }
```

Note the 

```haskell
                ((\ x2_a3bJE ->
                    let {
                      lvl289_s3QqB
                        = case x2_a3bJE of dt28_X3aHR { __DEFAULT ->
                          MakeKnownSuccess dt28_X3aHR
                          } } in
```

part.

With `oneShot` it's

```haskell
lvl46_r2GIM
  = \ v_a20Fz ->
      case v_a20Fz of {
        __DEFAULT -> lvl45_r2GIL;
        VCon val_a21pg ->
          case val_a21pg `cast` <Co:8> of { ValueOf uniAct_s2BNj x_s2BNk ->
          case $fGCompareTYPEDefaultUni_$cgeq
                 $WDefaultUniBool (uniAct_s2BNj `cast` <Co:8>)
          of {
            Nothing ->
              Left
                (KnownTypeUnliftingError
                   (typeMismatchError
                      ($fGShowTYPEDefaultUni_$cshowsPrec `cast` <Co:6>)
                      ($WDefaultUniBool `cast` <Co:9>)
                      uniAct_s2BNj));
            Just ds1_a20FP ->
              case ds1_a20FP of { Refl co8_a20FT ->
              Right
                ((\ v1_a20FS ->
                    Right
                      ((\ v2_a20FW ->
                          Right
                            (case x_s2BNk `cast` <Co:3> of {
                               False -> ($WMakeKnownSuccess v2_a20FW) `cast` <Co:15>;
                               True -> ($WMakeKnownSuccess v1_a20FS) `cast` <Co:15>
                             }))
                       `cast` <Co:34>))
                 `cast` <Co:64>)
              }
          }
          }
      }
```

which doesn't create the pointless thunk.

However as the numbers above indicate the thunk may not be pointless. Maybe something useful gets cached?

I've looked into the validation programs and the only three functions that have these thunks in the game contract are `Trace`, `IfThenElse` and `ChooseList`. However in the actual programs all of them are fully saturated, so how could any caching occur if all partial applications get fully saturated right away and immediately disposed afterwards?

Maybe I missed something though. We can tweak the CEK machine to keep track of individual partial applications to see if any of them are reused to debug this further.

But maybe something gets pulled to the top-level and this is what `oneShot` prevents? I'm not too excited about going fishing in 22k lines of Core with loads of irrelevant crap in it, so I'm going to solve the latter problem first.

**Comment by effectfully** [comment]
@michaelpj does the Plutus Tx compiler always eta-expand built-in functions?

**Comment by michaelpj** [comment]
No.

**Comment by effectfully** [comment]
> However as the numbers above indicate the thunk may not be pointless. Maybe something useful gets cached?

Partial builtin applications don't get reused in the validation contracts (see #4629), so we don't get any useful caching there.

It's probably the case that something gets lifted to the top level. Will investigate this further once it's not such a pain to debug produced GHC Core.

**Comment by effectfully** [comment]
> It's probably the case that something gets lifted to the top level.

Not the case either. Deferred unlifting causes the same slowdown while lifting closures exactly the same way as with immediate unlifting. At this point it seems to be an issue unrelated to the code. Maybe something's wrong with the building infrastructure, maybe with benchmarks, maybe with something else.

**Comment by effectfully** [comment]
So #4661 didn't help (I rebased on `master)`, we still have a weird slowdown here.

**Comment by effectfully** [comment]
> Deferred unlifting causes the same slowdown while lifting closures exactly the same way as with immediate unlifting.

Not that I compared 5k lines of Core though. It just does the same thing in the places that I checked. Hm... but deferred unlifting has that bang, which immediate unlifting doesn't have. Gonna experiment more.

**Comment by effectfully** [comment]
^ if we don't touch `toImmediateF`, we don't get the slowdown.

**Comment by effectfully** [comment]
So changing must be influencing something indeed.

**Comment by effectfully** [comment]
^

> Hm... but deferred unlifting has that bang, which immediate unlifting doesn't have. Gonna experiment more.

No slowdown with the right bang!

**Comment by effectfully** [comment]
> No slowdown with a bang in the right place!

Err, I should go get some sleep, not touching anything also doesn't give us a slowdown.

**Comment by effectfully** [comment]
`oneShot`-ing denotations of builtins doesn't cause the slowdown. I now hear the voice of Moss from The IT crowd saying "yeah, sure, why not".

**Pull request closed without merging**
