### PR TITLE
Kwxm/plc spec/fix zigzag

### PR DESCRIPTION
**Pull request by kwxm**
@christianschmitz pointed out in #5038 that the definition of the zigzag encoding was wrong for negative integers. This should fix it.

### CODE REVIEW

**Comment by michaelpj** [comment]
Can we bin the PDF? We should be able to get it from hydra in just the same way that we do for the other one.

**Review by michaelpj — APPROVED** [review]

**Comment by kwxm** [comment]
> Can we bin the PDF? We should be able to get it from hydra in just the same way that we do for the other one.

Can I have a link?  I'm never able to find these things.  Also, is the location likely to change any time soon?

**Comment by michaelpj** [comment]
But there is no way we need a checked in PDF any more!

**Comment by kwxm** [comment]
I still don't know where to find it!

**Comment by michaelpj** [comment]
Click here: 
image

**Comment by kwxm** [comment]
I don't understand.

**Comment by kwxm** [comment]
I'm going to merge this.  We can look at removing the PDF in a separate PR.

**Pull request merged**
