### PR TITLE
Remove circular symlink from language-plutus-core

### PR DESCRIPTION
**Pull request by michaelpj**
Tested and this works fine with:
- `cabal test`
- `stack test`
- `nix build`

### CODE REVIEW

**Comment by reactormonk** [comment]
Option c) Add some TH magic so it can detect HIE. Takes too long IMO.

**Comment by michaelpj** [comment]
I don't understand what goes wrong with HIE. Can you elaborate? If it doesn't build when it works with both stack and cabal that's IMO a bug in HIE.

**Comment by reactormonk** [comment]
Yeah, it's a bug. I reported it here: https://github.com/fpco/th-utilities/issues/10 May also be a HIE bug. But as bugs go, it's fairly easy to work around.

**Comment by michaelpj** [comment]
Okay, well there's no point having the file-embed stuff then.

**Comment by michaelpj** [comment]
Fixed.

**Comment by reactormonk** [comment]
> Okay, well there's no point having the file-embed stuff then.

It helps a tiny bit, but that's about it.

**Pull request merged**
