### PR TITLE
Unrestricted force

### PR DESCRIPTION
**Pull request by michaelpj**
Don't look here yet. This is an experiment I've wanted to do for a
while, just looking to get some benchmark numbers.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by L-as** [comment]
Rather than doing this as a post-hoc optimisation, why not omit emitting unnecessary delays and forces? That seems like a simpler thing to do.

**Comment by L-as** [comment]
You could in PIR make one constructor for both type abstractions and lambdas of arbitrary (type) parameters, which would seemingly allow you to emit more optimised UPLC.

**Comment by michaelpj** [comment]
> Rather than doing this as a post-hoc optimisation, why not omit emitting unnecessary delays and forces? That seems like a simpler thing to do.

I disagree with this as a compiler design principle. IME (and I think this is the standard wisdom) it's almost always better to make code-gen as dumb as possible and then optimize away the bad stuff. That makes your code gen simpler (which is important since it's almost always pretty complicated anyway), and your optimizations will benefit you in other places.

**Comment by michaelpj** [comment]
Pretty modest tbh, slightly disappointing.

**Pull request closed without merging**
