### PR TITLE
usecases: Crowdfunding tweaks

### PR DESCRIPTION
**Pull request by j-mueller**
* Add contributor's public key to required signatures
  (This causes a WalletAPIError if the contributor's key
  is different from the that of the wallet that submits it)
* Use a proper datatype instead of a tuple for the contribution

### CODE REVIEW

**Comment by michaelpj** [comment]
> This causes a WalletAPIError if the contributor's key
is different from the that of the wallet that submits it

Is this a problem? It's a bit weird if I designate someone other than myself to be the recipient of the refund, but it doesn't seem *wrong* per se.

**Comment by j-mueller** [comment]
No it's good because it catches the mismatch sooner (otherwise you'd only see it in the failed transaction)

You can still send the funds whereever you want, but the tx has to be signed by that public key.

**Comment by j-mueller** [comment]
Ideally the refund would be tokenised and we wouldn't have to worry about public keys anymore ;)

**Comment by michaelpj** [comment]
> No it's good because it catches the mismatch sooner (otherwise you'd only see it in the failed transaction)

So the goal is to protect against someone just accidentally putting someone else's key in there? I feel like we normally do that kind of error checking at a higher level. At the contract level it seems fine to put down whoever you want as the refund recipient, and

> You can still send the funds whereever you want, but the tx has to be signed by that public key.

makes that very difficult.

**Comment by michaelpj** [comment]
But ultimately it doesn't really matter much, and depends what you want the contract to do, so up to you :)

**Comment by j-mueller** [comment]
@kris and I were debugging a tract with this contract and we realized that the tuple `(PubKey, Value)` as an argument for `contribute` is a bit misleading because it's not clear what the `PubKey` argument is for - is it the campaign owner, or the contributor? So I just added the `Contribution` type to clarify. 

> So the goal is to protect against someone just accidentally putting someone else's key in there?

Yes, in particular to protect against someone putting in the campaign owner's key

> makes that very difficult.

Sorry, when I wrote "that" public key I meant the contributor's public key. You can still add any public key outputs you want as additional output to the unsigned transaction that claims the refund

**Comment by j-mueller** [comment]
Also, if we leave the `requiredSignatures` field empty, and the public key is *not* one of the signatories of the transaction, then the tx gets submitted but the script fails. So it seems like an appropriate use of the `requiredSignatures` field.

**Pull request merged**
