### PR TITLE
Reduce the number of `removeDeadBindings` calls

### PR DESCRIPTION
**Pull request by ak3n**
Profiling the pir compiler demonstrated that a lot of time is spent during deadcode optimisations. This PR reduces the multiple number of `removeDeadBindings` calls to only two:
1. before `simplifyTerm` in `compileToReadable`
2. before `simplifyTerm` in `compileReadableToPlc`

### Results

Before this change:

image

After this change:

image

---

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
Time to build `marlowe` on hydra:
Before: 16m 57s
After: 9m 35s

:+1:

**Comment by michaelpj** [comment]
Has conflicts, which is a bit surprising?

**Review by michaelpj — APPROVED** [review]

**Comment by michaelpj** [comment]
Ugh, probably because of the changes to the prettyprinter output or something :/

**Comment by ak3n** [comment]
Hmmm, is this test fragile?

```
equality does not survive renaming without marking:          FAIL (0.10s)
      common/PlcTestUtils.hs:87:
      expected: False
       but got: True
```

**Comment by michaelpj** [comment]
Yes, extremely rarely. Should do something about that, but for now I restarted the job.

**Pull request merged**
