### PR TITLE
Simplifying an unifying some common frontend code.

### PR DESCRIPTION
**Pull request by krisajenkins**

### CODE REVIEW

**Comment by michaelpj** [comment]
Possibly dumb question that I've been wondering for a bit: how feasible would it be for the generated code/`web-common` to be "real" javascript packages and to wire them in as dependencies, rather than having to copy them into the source tree during the build?

**Comment by michaelpj** [comment]
Doesn't purescript have a workflow where you have multiple "local" packages? So `web-common` could be a local package? And then presumably we could wire up the nix to supply it appropriately.

Basically, it seems like we can handle this case for e.g. shared Haskell code in local packages, I'm surprised if we can't do it in purescript.

**Comment by michaelpj** [comment]
That's what we'd want we were passing in the *source*. Shouldn't there be some way to pass it around as a "built" dependency that we can feed to spago or whatever?

**Comment by michaelpj** [comment]
> That wouldn't be through Spago. The PS toolchain always assumes dependencies are source files.

But e.g. the ones you get from NPM get magically stitched into `node_modules` for you, so you don't have to copy them around. (I know we're not really using `mkYarnPackage` how you're supposed to, but maybe things will be nicer in the future.) I guess I mean: could `web-common` be like the NPM deps?

**Comment by shmish111** [comment]
@michaelpj I think the question is what would it buy us? It is a bit weird at the moment and somehow feels wrong but distributing it as another module would make development _slightly_ more difficult and for what?

**Comment by michaelpj** [comment]
IDK, hygiene? I'm mostly asking because it made my life harder last time I tried to modify `purescript.nix`, but it's not a big deal.

**Pull request merged**
