### PR TITLE
[Builtins] Made 'choose'-like builtins receives its argument of the built-in type first

### PR DESCRIPTION
**Pull request by effectfully**

### CODE REVIEW

**Comment by jmchapman** [comment]
Is it better to do it this way around?

Fold takes it data type arg last, if-then-else takes its bool arg first.

Is there an ease of compilation/execution time/code size advantage to first or last?

**Comment by michaelpj** [comment]
I think the metaphor I was going for is that it's like a "weak" pattern matcher. And for those we tend to take the datatype value first. I don't think there's any practical reason.

**Comment by effectfully** [comment]
> I don't think there's any practical reason.

I'm not aware of any either.

**Review by jmchapman — APPROVED** [review]
LGTM, seems only to move the pieces are in the tests/examples.

**Pull request merged**
