### PR TITLE
[CGP-356] Added type synthesis tests

### PR DESCRIPTION
**Pull request by effectfully**
This adds type synthesis tests and immediately disables them, because there are bugs.

One kind of bug:

```
              Expected type
                '(fix self (fun self (fun a b)))',
              found type
                '(fix self [(lam a (type) (fun self a)) (fun a b)])'
```

It seems we do not normalize something properly. I'll take a look and if I won't be able to track this down, I'll ask Vanessa.

Another kind of bug is due to historical reasons where we have `integer :: type` as opposed to `integer :: size -> type` (this was the case, right?), so stdlib were written with having the former in mind. I'll fix the stdlib in another PR.

### CODE REVIEW

**Comment by mchakravarty** [comment]
> This adds type synthesis tests and immediately disables them, because there are bugs.

What do you think about add a list of all disabled tests to the `README.md` of the package? This makes them more visible, so we don't forget to fix them eventually.

**Comment by effectfully** [comment]
> What do you think about add a list of all disabled tests to the `README.md` of the package? This makes them more visible, so we don't forget to fix them eventually.

I think the common thing is to have a folder of failing tests that are not supposed to fail.

Most of the tests from this PR already pass. There are a couple of tests which don't pass, but I plan to work on this on the next week and there is already a related YouTrack ticket (CGP-363), so this is kinda WIP and I do not bother with making those fails explicit to the reader.

**Comment by mchakravarty** [comment]
@effectfully Well, then let's have a link to the folder with failing test cases. I think, it is good to make this visible. It is too easy to just forget stuff put into a folder down in the hierarchy.

**Comment by effectfully** [comment]
> Well, then let's have a link to the folder with failing test cases. I think, it is good to make this visible. It is too easy to just forget stuff put into a folder down in the hierarchy.

Sounds good to me. I'll do this.

**Pull request merged**
