### PR TITLE
playground: Better crowdfunding example

### PR DESCRIPTION
**Pull request by j-mueller**
* Gets rid of the "NegativeNumber" error that appears occasionally in the logs
* Uses wallet ID (int) instead of wallet public key to identify campaign owner

### CODE REVIEW

**Comment by j-mueller** [comment]
The problems that this deals with only occur in the playground - in `plutus-use-cases` we can enter the correct public key as a parameter and we also don't run the risk of producing a transaction that causes a `NegativeValue` error because we always select the correct currency that corresponds to `Ada`. 

So the only reason to also update `plutus-use-cases` is for greater consistency

**Comment by michaelpj** [comment]
> So the only reason to also update plutus-use-cases is for greater consistency

Seems like a good reason :) The more these two drift from each other the more annoying they are to update!

**Comment by j-mueller** [comment]
The crowdfunding contract is now exactly the same in `plutus-use-cases` and `plutus-playground-server`

**Comment by dorin100** [comment]
I am not 100% sure that this ticket created the below UI changes, but it seems the most relevant to me, so I will add the comments here (the sl-plutus has > 70 members). 

So while trying to check if this ticket was deployed on dev environment (https://kris.plutus.iohkdev.io/) I observed that for the Crowdfunding contract, the main field names are no longer displayed. Check the below picture.

crowdfunding changes

My concern is that it makes the workflow much less intuitive - you don't know anymore what each value represents in the context of the contract.

**Pull request merged**
