### PR TITLE
Redo UPLC purity analysis to match PIR

### PR DESCRIPTION
**Pull request by michaelpj**
This is the UPLC counterpart of the PIR work. Broadly small improvements.

The new logic _almost_ entirely subsumes the old `delayAndVarIsPure` logic. There is one exception: we would effectively propagate the "forcing" context through several steps of evaluation, which is quite tricky, and the current code does not try to do. Now we only go into the body of a delay if it is _immediately_ enclosed by a force. I don't think this is a huge loss, though.

Also this finally fixes the broken testcase (it's still weird, but now it's just GHC's fault).

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [x] Targeting master unless this is a cherry-pick backport
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
(I think this is covered by the previous changelog entry)

**Review by zliu41 — COMMENTED** [review]
I don't think the `<>` short circuits once it hits the first `Unknown` does it? It could build a much longer DList than needed, which then needs to be converted to a regular list in linear time, before it can be inspected.

**Comment by michaelpj** [comment]
There's a test in the PIR version that the whole thing is lazy enough: it successfully processes a term with an `undefined` subterm, which it couldn't do if it was too strict. Note that it also can't be creating the "spine" of the DList, since knowing what the spine looks like requires analyzing later terms, which we know it doesn't.

Which reminds me, I should port the tests over too.

**Review by zliu41 — APPROVED** [review]
> Note that it also can't be creating the "spine" of the DList, since knowing what the spine looks like requires analyzing later terms, which we know it doesn't.

Yeah, you are right.

**Pull request merged**
