### PR TITLE
[Builtins] Stop constructing 'BuiltinApp' for the result

### PR DESCRIPTION
**Pull request by effectfully**
It was nice, but stupid. Don't review yet.

### CODE REVIEW

**Comment by michaelpj** [comment]
I'd be quite shocked if this made a difference given that `evalBuiltinApp` is marked as `INLINE` :thinking:

**Comment by effectfully** [comment]
Which does make sense. I'll probably write a post about this.

**Comment by effectfully** [comment]
-3.71%. Weird! How come it's faster than the baseline, but slower than #4581? Maybe constructing a `BuiltinRuntime` and then forcing it immediately is generally better than not constructing it when it's not needed, but delaying the forcing otherwise? Gonna experiment more.

I'll also rerun the benchmarks on #4581 once the machine is available.

**Comment by effectfully** [comment]
-4.37% now vs -3.71% before. Not sure if noise or not, but in any case worse than the competitor (#4581) giving us -6.3%. Given that the competitor is also more explicit and safer, I'm going to go with it.

**Comment by effectfully** [comment]
Ah, yeah, it's ab absolute mystery for me why #4581 is faster given that this one seems to have fewer indirections and I'm not able to spot anything else.

**Pull request closed without merging**
