### PR TITLE
Kwxm/core spec updates

### PR DESCRIPTION
**Pull request by kwxm**
Let's try merging that again...

### CODE REVIEW

**Comment by michaelpj** [comment]
Is this meant to do nothing except change the date? Also, let's just get rid of the date, I don't think it adds anything.

**Comment by kwxm** [comment]
> Is this meant to do nothing except change the date? Also, let's just get rid of the date, I don't think it adds anything.

Yes.  It's fixing an error in the CK rules and adding a reference to the compilation paper in the bit about `ifix`.

The date's mostly there because I have various printed copies lying about and it's useful to be able to see which is which (although I suppose I could just write the date on it with a pen).  We used to have "Version 1.0 (RC5,.2)" which was even less helpful.

**Comment by michaelpj** [comment]
If you look at the diff it doesn't change anything except the date.

IMO the date will just get out of date and/or hint at how long it's been since we changed anything!

**Comment by kwxm** [comment]
There are four separate commits here, doing different things; it just occurred to me that I should change the date after I'd done the rest. Things may have become confused because I reverted the merge because I thought it'd broken the build; a subsequent commit (https://buildkite.com/input-output-hk/plutus/builds/3036) caused the same error though, so I don't think it's my fault after all.

As for the date, I suggest leaving it there until the document has stabilised (which I hope will happen soon) and then change it to version 2.0 or something.

**Comment by michaelpj** [comment]
> There are four separate commits here, doing different things; it just occurred to me that I should change the date after I'd done the rest.

Look at the diff. The total effect of this PR is to just change the date. Maybe you discarded your changes when you did the merge?

**Comment by michaelpj** [comment]
I don't see the point of having a version in the spec either tbh.

**Comment by michaelpj** [comment]
Hm, when I look locally I see something different. Not sure what's going on, I recommend rebasing on master.

**Comment by kwxm** [comment]
> I don't see the point of having a version in the spec either tbh.

For one thing, if we're talking about it then it makes it easier to make sure that everyone's talking about the same version.  We could require everyone to rebuild from the latest github version every time, but someone will always forget.

**Comment by kwxm** [comment]
I can see the earlier change if I click on the `Commtis` tab and look at the diffs there. I'll try rebasing and see if that improves things though.  Any idea what's going on with the buildkite error?

**Comment by michaelpj** [comment]
> I can see the earlier change if I click on the Commtis tab and look at the diffs there.

Yes, but later things can reverse earlier changes, so you need to look at the overall change. Which appears to be missing most of the changes.

**Comment by michaelpj** [comment]
Ignore the buildkite thing, it's on my list.

**Comment by kwxm** [comment]
I'm going to close this and try again with a new branch.

**Pull request closed without merging**
