### PR TITLE
Document constructors

### PR DESCRIPTION
**Pull request by zmrocze**
### description
PR documents and changes constructors of some of the types mentioned in [#4476](https://github.com/input-output-hk/plutus/issues/4476).

It touches:
  - hash types: `PubKeyHash`, `DatumHash`, `RedeemerHash`, `ScriptHash`, `ValidatorHash`, `MintingPolicyHash`, `StakeValidatorHash`.
  - `TokenName`, `CurrencySymbol`

First two commits only add documentation.
Third commit renames constructors to `Unsafe[...]` and adds constructors verifying lengths.
Still values can be constructed using instances of `IsString`, here I added comment that this uses hex encoding.

### CODE REVIEW

**Review by gege251 — APPROVED** [review]
Looking good to me!

**Comment by thealmarty** [comment]
Thank you for your effort. As [mentioned](https://github.com/input-output-hk/plutus/issues/4476#issuecomment-1213185470), we aren’t committed to checking invariants. And I will be adding and updating Haddock for these functions. I will let you know once that PR is ready so you can give us input there. Thanks again.

**Comment by L-as** [comment]
I can't see how this PR is in conflict with "checking invariants".

**Comment by L-as** [comment]
The comments look very reasonable.

**Comment by thealmarty** [comment]
If you look at the third commit, you can see that it includes some checks. If desired, with the third commit reverted I can merge this. Just bear in mind that I will still be opening a PR and change/update those parts quite soon.

**Pull request closed without merging**
