### PR TITLE
plutus-ledger: lock outputs with pubkey hashes instead of the keys

### LINKED ISSUE #1575: ledger: Pay-to-pubkey outputs should be locked by hash of public key
They are currently locked by the public key but they should be locked by the hash of the public key.

### PR DESCRIPTION
**Pull request by michaelpj**
Fixes #1575.

This generally strips down on the amount of information we put on inputs
and outputs to bring it more in line with the spec. In particular, we
use the *hashes* of pubkeys instead of the keys themselves for locking
outputs.

This has many cascading effects throughout the libraries, particularly
given that we don't want to support `publicKeyHash :: PubKey ->
PubKeyHash` in Plutus Tx.

One notable change is that rather than providing the witnesses as they
are in `PendingTx`, we instead:
- Use hashes instead of keys
- Only provide a list of signatories instead of including the signature
  (the signature will have been verified by the node, there's no point
  passing it in again)

We still put too much information on script inputs: the validator and
data values should be segregated. However, this would require quite a
lot of changes to how we construct script inputs (since they'd also need
to add to the segregated witnesses of the transaction), so I've left
that for now. It should be much easier after
https://github.com/input-output-hk/plutus/pull/1796.

Another notable thing is that the rendering of outputs etc now talks
about the hashes of keys instead of keys themselves. I *think* this is
fine, since we'll be fairly consistently talking about the hashes.

### CODE REVIEW

**Comment by j-mueller** [comment]
> given that we don't want to support publicKeyHash :: PubKey -> PubKeyHash in Plutus Tx.

Maybe we don't need the hash primitive at all?

**Comment by michaelpj** [comment]
> Maybe we don't need the hash primitive at all?

Yeah, unclear. The main issue isn't so much the idea of doing hashing on chain, it's:
- Making sure the hashing is *exactly* the same as whatever is done off-chain. This will get even harder if we start using  the real ledger representation of things.
- Matching up the off-chain hashing primitives with the on-chain ones.

Overall I feel like it's just easier to pass the hashes in.

**Comment by michaelpj** [comment]
@krisajenkins I had to hack around with the rollup and the frontend to make this work, I'd appreciate a look over. Basically, we have to use pubkey hashes in a bunch more places, since that's the information we actually have about e.g. outputs.

**Comment by michaelpj** [comment]
Okay, let's go.

**Pull request merged**
