### PR TITLE
spec improvements to section 3

### PR DESCRIPTION
**Pull request by jmchapman**

### CODE REVIEW

**Comment by jmchapman** [comment]
Shouldn't the a 'typing' rule for size `s`:

G valid
-------------
G |- S :: (size)

?

**Comment by jmchapman** [comment]
I would like to get rid of of the `Gamma \ni J` judgement altogether.

**Comment by kwxm** [comment]
> Shouldn't the a 'typing' rule for size `s`?
> 
> ```
> G valid
> -------------
> G |- s :: (size)
> ```

Yes, presumably.

**Comment by kwxm** [comment]
> I would like to get rid of of the `Gamma \ni J` judgement altogether.

Feel free!

**Comment by kwxm** [comment]
It might be worth trying to get the various bits of description next to the things they're talking about.  This would require some tex fiddling though (I can do that) and might be a bit fragile, so it might be sensible to leave it until the end.

In general this looks like the kind of stuff that we want.  Once it's all done (and I still have more to do) I suppose we can ask for other people to review the whole thing.

**Comment by jmchapman** [comment]
I would like to draw a line and merge this in advance of the forthcoming bigger changes to the spec

**Comment by kwxm** [comment]
I've now resolved some conflicts and fiddled with the spacing a bit.  I'll merge this when the tests finish.

**Comment by kwxm** [comment]
... plus the text looks fine.  We'll have further opportunities to refine it later, but let's merge this now so that we can move on to a new version without sizes.

**Comment by kwxm** [comment]
Final version of spec before removal of sizes.

**Pull request merged**
