### PR TITLE
PLT-1312 Create executable library and use it in plc-ada

### PR DESCRIPTION
**Pull request by mjaskelioff**
`plc-agda` would benefit from reusing files from `plutus-core/executables`. This PR creates a library `plutus-core-execlib` which exposes modules `PlutusCore.Executable.Common` and `PlutusCore.Executable.Parsers`. The library is used by the executables `pir`, `plc`, `uplc`, and `plc-agda`.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [X] Commit sequence broadly makes sense
    - [X] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [X] Relevant tickets are mentioned in commit messages
    - [X] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [X] Targeting master unless this is a cherry-pick backport
    - [X] Self-reviewed the diff
    - [X] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by kwxm** [comment]
I can't get this to build.  I get this:
```
$ cabal build plutus-core-execlib
Warning: Requested index-state 2022-10-24T00:00:00Z is newer than
'cardano-haskell-packages'! Falling back to older state
(2022-10-21T19:15:20Z).
Resolving dependencies...
Build profile: -w ghc-9.2.4 -O1
In order, the following will be built (use -v for more details):
 - plutus-core-1.1.1.0 (lib:plutus-core-execlib) (first run)
Preprocessing library 'plutus-core-execlib' for plutus-core-1.1.1.0..
Building library 'plutus-core-execlib' for plutus-core-1.1.1.0..
/nix/store/jfkmqz20q8fsaqizcml86adxqyzlwllx-binutils-2.38/bin/ld: cannot find [redacted]/plutus/plutus/dist-newstyle/build/x86_64-linux/ghc-9.2.4/plutus-core-1.1.1.0/l/plutus-core-execlib/build/plutus-core-execlib/PlutusCore/Executable/Parsers.dyn_o: No such file or directory
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```
I get a similar message when I try `cabal run plc-agda` and other things.  I'm not sure what the problem is: maybe there's something missing in the cabal file? The error message isn't very helpful...

**Review by kwxm — APPROVED** [review]
This looks OK and appears to work properly, and has the bonus of cleaning up the cabal stuff for `uplc` and other things. Win-win!

**Comment by kwxm** [comment]
I see that `cabal build pir` doesn't work.  I think `pir` needs to depend on `plutus-core-testlib` in the cabal file.

**Comment by mjaskelioff** [comment]
I did a `cabal clean` and `cabal build pir` and it worked without problems. What is the problem you are having @kwxm ?

**Comment by kwxm** [comment]
> I did a cabal clean and cabal build pir and it worked without problems. 

Oh, it works for me now.  I think the problem maybe happened when I merged `master` with a branch of my own and then had trouble building it, but I forgot that I wasn't in the main branch.  Apologies for that!

**Pull request merged**
