### PR TITLE
[Evaluation] Fixed the performance issue introduced by the handle pattern PR

### PR DESCRIPTION
**Pull request by effectfully**
Here we go.

### CODE REVIEW

**Comment by effectfully** [comment]
Compared to the version of the CEK machine that we had before the handle pattern PR this one is 0.1-2.5% faster for me. @kwxm could you also check the numbers?

If we put everything into one file, it'd be about 1% slower due to GHC not be able to perform the worker/wrapper transformation for some reason.

This PR is just to fix the latest problem. Apparently, there are more problems, so I'll create more PRs.

**Review by kwxm — APPROVED** [review]
That's a good bit of detection there.  I'm afraid I laughed when saw what the solution was!  This is a very useful thing to know though.

**Comment by kwxm** [comment]
Here are the results of the validation benchmarks compared with the first column in the table [here](https://github.com/input-output-hk/plutus/pull/2852#issuecomment-798711573), ie the times for the master branch before merging the earlier handle pattern PR.  The new figures are a bit better than the old ones (maybe by 1-2% in general), but the problem introduced by the earlier PR has definitely gone away.  I'll add the results for `nofib` later.

```
crowdfunding/1           5.323 ms	5.217 ms    -2.0%
crowdfunding/2           5.401 ms	5.351 ms    -0.9%
crowdfunding/3           5.375 ms	5.347 ms    -0.5%
crowdfunding/4           3.328 ms	3.318 ms    -0.3%
crowdfunding/5           3.329 ms	3.322 ms    -0.2%
future/1                 3.234 ms	3.197 ms    -1.1%
future/2                 6.299 ms	6.134 ms    -2.6%
future/3                 6.274 ms	6.142 ms    -2.1%
future/4                 8.598 ms	8.404 ms    -2.3%
future/5                 10.04 ms	9.916 ms    -1.2%
future/6                 8.555 ms	8.718 ms    +1.9%
future/7                 10.00 ms	9.977 ms    -0.2%
multisigSM/1             6.245 ms	6.337 ms    +1.5%
multisigSM/2             6.370 ms	6.357 ms    -0.2%
multisigSM/3             6.517 ms	6.464 ms    -0.8%
multisigSM/4             6.556 ms	6.512 ms    -0.7%
multisigSM/5             7.561 ms	7.495 ms    -0.9%
multisigSM/6             6.344 ms	6.302 ms    -0.7%
multisigSM/7             6.328 ms	6.387 ms    +0.9%
multisigSM/8             6.539 ms	6.422 ms    -1.8%
multisigSM/9             6.531 ms	6.522 ms    -0.1%
multisigSM/10            7.562 ms	7.490 ms    -1.0%
vesting/1                5.352 ms	5.343 ms    -0.2%
vesting/2                4.803 ms	4.763 ms    -0.8%
vesting/3                5.360 ms	5.343 ms    -0.3%
marlowe/trustfund/1      17.73 ms	17.46 ms    -1.5%
marlowe/trustfund/2      14.01 ms	13.99 ms    -0.1%
marlowe/zerocoupon/1     18.10 ms	17.65 ms    -2.5%
marlowe/zerocoupon/2     12.83 ms	13.04 ms    +1.6%

**Comment by kwxm** [comment]
Here are the results of the validation benchmarks compared with the first column in the table [here](https://github.com/input-output-hk/plutus/pull/2852#issuecomment-798711573), ie the times for the master branch before merging the earlier handle pattern PR.  The new figures are a bit better than the old ones (maybe by 1-2% in general), but the problem introduced by the earlier PR has definitely gone away.  I'll add the results for `nofib` later.

```
crowdfunding/1           5.323 ms	5.217 ms    -2.0%
crowdfunding/2           5.401 ms	5.351 ms    -0.9%
crowdfunding/3           5.375 ms	5.347 ms    -0.5%
crowdfunding/4           3.328 ms	3.318 ms    -0.3%
crowdfunding/5           3.329 ms	3.322 ms    -0.2%
future/1                 3.234 ms	3.197 ms    -1.1%
future/2                 6.299 ms	6.134 ms    -2.6%
future/3                 6.274 ms	6.142 ms    -2.1%
future/4                 8.598 ms	8.404 ms    -2.3%
future/5                 10.04 ms	9.916 ms    -1.2%
future/6                 8.555 ms	8.718 ms    +1.9%
future/7                 10.00 ms	9.977 ms    -0.2%
multisigSM/1             6.245 ms	6.337 ms    +1.5%
multisigSM/2             6.370 ms	6.357 ms    -0.2%
multisigSM/3             6.517 ms	6.464 ms    -0.8%
multisigSM/4             6.556 ms	6.512 ms    -0.7%
multisigSM/5             7.561 ms	7.495 ms    -0.9%
multisigSM/6             6.344 ms	6.302 ms    -0.7%
multisigSM/7             6.328 ms	6.387 ms    +0.9%
multisigSM/8             6.539 ms	6.422 ms    -1.8%
multisigSM/9             6.531 ms	6.522 ms    -0.1%
multisigSM/10            7.562 ms	7.490 ms    -1.0%
vesting/1                5.352 ms	5.343 ms    -0.2%
vesting/2                4.803 ms	4.763 ms    -0.8%
vesting/3                5.360 ms	5.343 ms    -0.3%
marlowe/trustfund/1      17.73 ms	17.46 ms    -1.5%
marlowe/trustfund/2      14.01 ms	13.99 ms    -0.1%
marlowe/zerocoupon/1     18.10 ms	17.65 ms    -2.5%
marlowe/zerocoupon/2     12.83 ms	13.04 ms    +1.6%

**Comment by kwxm** [comment]
... and here are the `nofib` times (lhs = pre-handle times from [this table](https://github.com/input-output-hk/plutus/pull/2852#issuecomment-798770193):

```
clausify/formula1        260.1 ms	237.0 ms      -8.9%
clausify/formula2        321.2 ms	293.8 ms      -8.5%
clausify/formula3        0.8971 s	0.8112 s      -9.6%
clausify/formula4        1.173 s	1.105 s       -5.8%
clausify/formula5        5.908 s	5.315 s      -10.0%
knights/4x4              622.6 ms	574.9 ms      -7.7%
knights/6x6              1.863 s	1.704 s       -8.5%
knights/8x8              3.181 s	2.910 s       -8.5%
primetest/05digits       404.0 ms	366.2 ms      -9.4%
primetest/08digits       744.8 ms	672.5 ms      -9.7%
primetest/10digits       1.075 s	0.9449 s     -12.1%
primetest/20digits       2.275 s	1.880 s      -17.4%
primetest/30digits       3.295 s	2.728 s      -17.2%
primetest/40digits       4.479 s	3.975 s      -11.3%
primetest/50digits       4.735 s	3.601 s      -23.9%
queens4x4/bt             107.4 ms	98.13 ms      -8.6%
queens4x4/bm             141.4 ms	127.0 ms     -10.2%
queens4x4/bjbt1          128.4 ms	121.0 ms      -5.8%
queens4x4/bjbt2          136.0 ms	129.5 ms      -4.8%
queens4x4/fc             299.8 ms	307.2 ms      +2.5%
queens5x5/bt             1.448 s	1.321 s       -8.8%
queens5x5/bm             1.621 s	1.439 s      -11.2%
queens5x5/bjbt1          1.666 s	1.548 s       -7.1%
queens5x5/bjbt2          1.739 s	1.634 s       -6.0%
queens5x5/fc             3.829 s	3.944 s       +3.0%
```

**Comment by michaelpj** [comment]
By the same logic... what happens if we stop exporting `runCekM`? I suspect that inlining it won't make *that* much difference, but you never know...

**Review by michaelpj — APPROVED** [review]

**Comment by effectfully** [comment]
@kwxm 

> Here are the results of the validation benchmarks compared with the first column in the table here, ie the times for the master branch before merging the earlier handle pattern PR. 

I've got a bit more consistent results on my machine (all are negative), but in the same spirit.

> ... and here are the nofib times (lhs = pre-handle times from this table):

Thanks, I haven't checked `nofib`. It's a decent improvement over what we had before the handle pattern PR...

@michaelpj 

> By the same logic... what happens if we stop exporting runCekM? I suspect that inlining it won't make that much difference, but you never know...

I think nothing, because `runCekM` is already small enough and non-recursive and so should be inlined regardless of whether it's exported or not. I've now removed it from the export list, but I don't care enough to run the benchmarks yet again to check if that makes any difference.

**Comment by effectfully** [comment]
>  Tests / nix-instantiate (macos-10.15) (pull_request) Queued — Waiting to run this check...

What's up with this test?

**Comment by michaelpj** [comment]
Supposed to be quicker than waiting for the hydra eval, doesn't seem to be. I'm ignoring it.

**Pull request merged**
