### PR TITLE
SCP-1707: Rename plutus-scb to plutus-pab

### PR DESCRIPTION
**Pull request by j-mueller**
Let's get this out of the way now.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [x] `$(nix-build default.nix -A plutus.updateMaterialized)` to update the materialized Nix files
   - [x] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
   - [x] `$(nix-shell shell.nix --run fix-stylish-haskell)` to fix any formatting issues
- If you changed any Purescript files:
   - [x] `$(nix-shell shell.nix --run fix-purty)` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by michaelpj — APPROVED** [review]
:shipit:

**Comment by michaelpj** [comment]
Ack, sorry, conflicts with the shell fix I just merged.

**Comment by michaelpj** [comment]
I should have held off until we got this in.

**Comment by j-mueller** [comment]
No problem, I forgot a few changes in this one anyway (module names, types, ...)

**Pull request merged**
