### PR TITLE
updated HIE bios

### PR DESCRIPTION
**Pull request by reactormonk**
Forgot this one. And also, this signs the previous PR (#1658)

### CODE REVIEW

**Comment by michaelpj** [comment]
Hm, if HaRE didn't work before, how did it get past CI if the CI builds `hie`?

**Comment by reactormonk** [comment]
Timeline:
- test dirs broken (committed)
- updated HIE to newest version where HaRe fails (not committed)
- fixed HaRe and now test dirs work (not committed in previous PR)
^ intermediate message missing.

**Comment by reactormonk** [comment]
Huh, github approvals don't get reset after you make changes.

**Comment by michaelpj** [comment]
That's right - you can re-request a review, but it would be a bit tedious if they all reset.

The CI statuses do rerun, of course.

**Pull request merged**
