### PR TITLE
[Builtins] Drop 'CekValEnv' from 'VBuiltin'

### PR DESCRIPTION
**Pull request by effectfully**
Theorem: `dischargeCekValue` is safe without `VBuiltin` storing an environment.

Proof by induction: `CekValue` has fours constructors:

1. `VCon`: doesn't require an environment for discharging
2. `VDelay`: requires an environment, but keeps one for itself
3. `VLamAbs`: requires an environment, but keeps one for itself
4. `VBuiltin`:
4.1 when initially constructed, doesn't require an environment, because it's only a `Builtin () fun` inside
4.2 within `forceEvaluate` the term inside is grown with `Force ()` which preserves the lack of need for an environment
4.3 within `applyEvaluate` the term inside is grown with `flip (Apply ()) (dischargeCekValue arg)` which preserves the lack of need for an environment as long as `dischargeCekValue arg` does, which is indeed the case by the induction hypothesis

Conclusion: by induction `VBuiltin` doesn't need to hold an environment.

### CODE REVIEW

**Comment by effectfully** [comment]
The results are too shaky, gonna rerun.

**Comment by effectfully** [comment]
OK, so you're telling me that `multisig-sm-2` and `multisig-sm-7` are 5+% faster, but everything else is basically the same? Why???

Anyways, despite apparently not giving us any speedup, this is still worth merging provided others agree with my reasoning justifying the change.

**Review by michaelpj — APPROVED** [review]
I agree with your argument, but I think it would be good to record this: maybe put a comment at each place we put a term into `VBuiltin` with the reasoning for why it's fully-discharged.

I think we should do this regardless of the weird benchmark. It clearly makes the code simpler; if we're getting to the point where we have random benchmark wobbles when we do that, I'm not too fussed, I think overall making things simpler has to help us.

**Comment by effectfully** [comment]
> I agree with your argument, but I think it would be good to record this: maybe put a comment at each place we put a term into `VBuiltin` with the reasoning for why it's fully-discharged.

Done. Merging.

**Review by kwxm — COMMENTED** [review]
Sorry for being late, but I'm pretty sure this is safe.  We're not supposed to be discharging on the chain anyway, so it shouldn't be problematic (if you believe the comment about why it was there in the first place!).

**Pull request merged**
