### PR TITLE
fix regex that failed for multiline mkFunctions and add a test

### PR DESCRIPTION
**Pull request by shmish111**

### CODE REVIEW

**Comment by michaelpj** [comment]
I think we could have a shorter test! This one will be some work to keep compiling if we change things!

All we need is to split the `mkFunctions` call over multiple lines, right?

**Comment by shmish111** [comment]
Yes however I thought it would be good to work in some of @brunjlar exploratory testing. Perhaps plutus isn't stable enough for this yet though?

**Comment by michaelpj** [comment]
The libraries are changing a lot at the moment. It's enough work keeping all of Lars' real examples working!

**Comment by shmish111** [comment]
ok, I'll remove and change one of the other examples to be on multiple lines. I feel like at some point in the future we should put these types of example back in to tests though.

**Comment by michaelpj** [comment]
> I feel like at some point in the future we should put these types of example back in to tests though.

What about testing the examples in the book that are supposed to go into the playgrounds? Lots of them are like that.

**Comment by shmish111** [comment]
Yeah, presumably at some point the book should be tested so it is kept up to date and to provide feedback about what sort of impact changes will have on users

**Pull request merged**
