### PR TITLE
Add workflow to run the cost model benchmark.

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
Draft pending https://github.com/input-output-hk/plutus/actions/runs/6098181769/job/16547457361

**Comment by shlevy** [comment]
Looks like @kwxm cancelled the run to free up the bench machine, so let's just assume the process will work.

**Comment by michaelpj** [comment]
Do we not need to test that this won't exceed the size limit for uploaded artifacts? I thought that was the worry?

**Comment by kwxm** [comment]
@shlevy I'll run this over the weekend to check that it works (plus the numbers would be useful to us).

**Pull request merged**
