### PR TITLE
type checking

### PR DESCRIPTION
**Pull request by jmchapman**
- [x] kind inference
- [x] type inference
- [x] integrating into `plc-agda`

**tests**

- [x] unitval : (all a (type) (fun a a))
- [x] true : (all a (type) (fun a (fun a a)))
- [x] false : (all a (type) (fun a (fun a a)))
- [x] churchZero : (all r (type) (fun r (fun (fun r r) r)))
- [x] churchSucc : (fun (all r (type) (fun r (fun (fun r r) r))) (all r (type) (fun r (fun (fun r r) r))))
- [x] overapplication : (con integer)
- [x] factorial : (con integer)
- [x] fibonacci : (con integer)
- [x] NatRoundTrip : (con integer)
- [x] ListSum : (con integer)
- [x] IfIntegers : (con integer)
- [x] ApplyAdd1 : (con integer)
- [x] ApplyAdd2 : (con integer)

### CODE REVIEW

**Comment by jmchapman** [comment]
all failing examples are failing in type equality checking

**Comment by jmchapman** [comment]
adding better error handling allowed me to find the really stupid bug that I missed the case for comparing pi types for equality so `all a K A` was never equal to `all a K' A'`. But now I have the more significant problem that I have been trying to get away with being very strict on the users chosen bound variables names. These had to be the exactly the same for things to be considered equal. I think this is a case for irrelevant arguments perhaps...

**Comment by jmchapman** [comment]
I actually only need the names for pretty printing as I am using de Bruijn indices which gives unique representatives for alpha-equivalence. But I want to keep the names around, I can mark them irrelevant which means that any `all "x" (type) 0` will be equal to `all "y" (type) 0`.

**Comment by jmchapman** [comment]
I implemented irrelevance. It works in the sense it now all the examples are type checked correctly. But, it also throws away all the names... Back to the drawing board.

**Comment by jmchapman** [comment]
the type checker is working (the test pass and it outputs types with the correct names). But, I have broken the intrinsically typed evaluator by changing the algorithmic syntax to work with the name ignoring notion of type equality

**Comment by jmchapman** [comment]
I am tempted to disable the intrinsically typed evaluator and merge this already quite large pull request. And then open a new one. The intrinsically typed evaluator is not yet used in `plc-agda`. Having a working typechecker opens the door to using it in `plc-agda`.

**Comment by michaelpj** [comment]
Sounds reasonable.

**Pull request merged**
