### PR TITLE
Staking credential needs to differentiate between pubkeys and scripts

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Oh shit. This is the point at which things get really annoying. We now depend on the Alonzo bit of `cardano-ledger-specs` which won't build with this change, because they use this type. I'm actually not sure how we sort this out :see_no_evil:

**Review by j-mueller — APPROVED** [review]

**Comment by j-mueller** [comment]
I think the way to resolve this is:
- submit a PR to `cardano-ledger-specs` that changes the plutus dependency to use this branch
- then change this PR's `cardano-ledger-specs` dep. to use that PR (or master if they let us merge it)
- then this PR should build and we can merge it
- then another PR to `cardano-ledger-specs` to change their `plutus` dep. to a commit from our `master` branch

**Comment by j-mueller** [comment]
Ourobouros, the snake that eats itself, manifested in our `cabal.project` files...

**Comment by sjoerdvisscher** [comment]
Not being able to create a PR on `cardano-ledger-specs` directly makes this extra annoying...

**Comment by michaelpj** [comment]
Ask in #ledger, you should be able to get permisions.

**Comment by sjoerdvisscher** [comment]
Argh, now cardano-api is no longer compatible with the latest version of cardano-ledger-specs!

**Comment by sjoerdvisscher** [comment]
So to make this work I rebased https://github.com/input-output-hk/cardano-ledger-specs/pull/2333 to the version of cardano-ledger-specs that cardano-node is based on. This also means that that PR cannot be merged until cardano-node is updated to the latests cardano-ledger-specs.

**Comment by j-mueller** [comment]
FYI: cardano-node has been updated, I'm currently rebasing this PR. Just in case anyone else looking at this has the same idea

**Comment by michaelpj** [comment]
I also bumped the ledger recently, so it's pretty up-to-date.

**Comment by j-mueller** [comment]
Now I just need to get this PR's changes to `plutus-ledger-api` into `cardano-ledger-specs`

**Comment by j-mueller** [comment]
the `cardano-ledger-specs` dependency now points to the latest commit on `cardano-ledger-specs/plutus-staging`

**Pull request merged**
