### PR TITLE
[Test] Add forgotten budget golden files

### PR DESCRIPTION
**Pull request by effectfully**
Guess who forgot a `git add .`.

### CODE REVIEW

**Comment by effectfully** [comment]
Not waiting for a review or even requesting one, since this just adds missing golden files.

**Comment by thealmarty** [comment]
The CI didn't complain?

**Comment by effectfully** [comment]
I think it doesn't complain about missing golden files and just creates them silently instead.

**Comment by thealmarty** [comment]
Right! That's not ideal. Not sure how to improve this though.

**Pull request merged**
