### PR TITLE
Bump stackage and nixpkgs

### PR DESCRIPTION
**Pull request by michaelpj**
For some reason I thought this wouldn't work but it did. Gets us to 8.6.5, nice to at least be on the latest 8.6.

Inspired by following https://raw.githubusercontent.com/input-output-hk/cardano-prelude/cb54482c7e3d45f6c1aac490dc937ed835de0333/snapshot.yaml, since we may want to add some Cardano libs as dependencies, so good to be on the same snapshot atm.

Putting this up mainly so Hydra will build things for me.

### CODE REVIEW

**Comment by michaelpj** [comment]
I'm having trouble with the musl build of 8.6.5 for the Marlowe lambda. Not entirely sure why or what we can do about it...

**Comment by michaelpj** [comment]
Hooray, it all works now.

**Comment by reactormonk** [comment]
Could you kindly wait for #1755 ? Won't take much longer...

**Comment by michaelpj** [comment]
Has stylish-haskell working with deriving via, includes appropriate changes.

**Comment by michaelpj** [comment]
Okay, let's do this.

**Pull request merged**
