### PR TITLE
makePrimitiveMap: use TupleSections (hlint warning).

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by michaelpj** [comment]
:-1: I left it like that deliberately, I don't think this is any better.

**Comment by jbgi** [comment]
I can revert and add the hlint ignore pragma instead in a following PR?

**Comment by michaelpj** [comment]
It's okay, I'm working pretty heavily on this code atm anyway. I'm not sure why you got it showing up as a warning when usually leftover hlints that aren't ignored fail the build.

**Comment by jbgi** [comment]
That's because I am working on the bazel branch based on nixpkgs 18.09 which provide a more recent version of hlint with this new lint.

**Pull request merged**
