### PR TITLE
PAB Wallet Emulator: make wallet number more consistent

### PR DESCRIPTION
**Pull request by kk-hainq**
I feel like this is not the correct fix, but without it there's a bug in the wallet config of PAB.
In that if we select the `Wallet 1`:
```
walletServerConfig:
  baseUrl: http://localhost:9081
  wallet:
    getWallet: 1
```
We end up using `Wallet 10`.

With
```
walletServerConfig:
  baseUrl: http://localhost:9081
  wallet:
    getWallet: 2
```
We end up using `Wallet 1`, etc.

Does anyone know the best fix for this issue? I'm ready to dig deeper with some guidance. Or without one next week.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [x] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by j-mueller** [comment]
> We end up using Wallet 10.

What does this mean in practice? As far as I know, `walletPrivKey` is the only place where we index into the list of private keys directly. So I don't think it is necessary that `Wallet 1` gets the first key from `knownPrivateKeys`.

**Comment by kk-hainq** [comment]
The issue is happening on the PAB Client. For example with the current config where we should act with Wallet 1, when we pay to Wallet 2.
image

We'd get an `Insufficient Funds` error:
image

Even though we should have 1 million ADA.

Now when we use the `prism-mirror` contract:
image

It suggests that we're acting with Wallet 10!
image

Similarly if we change the config to `getWallet: 2` we'd end up acting as `Wallet 1`.

I thought fixing this in the client makes more sense but didn't have enough time to investigate so ended up moving on with this temporary fix. I also saw the `privateKey` values being counted from 1 in the source code so maybe this fix makes sense after all. And yeah, I'm not familiar enough to know all the affected places yet...

**Comment by j-mueller** [comment]
Ok that makes sense, thanks for the info. Yeah I'm not sure where the mismatch comes from, `walletPrivKey` should be the only place where we convert wallets to keys.

I'm happy to accept your fix also, looks like the test failure is just from the hashes changing, which is expected (to repair that, delete all the .txt files from `plutus-use-cases/spec` and run the tests again)

**Comment by kk-hainq** [comment]
Thank you for the guidance, @j-mueller! I've updated the hashes and all checks have passed now.

**Comment by kk-hainq** [comment]
@j-mueller I've rebased to fix the conflicts.

**Comment by j-mueller** [comment]
Great. Thank you!

**Pull request merged**
