### PR TITLE
plutus-playground-server: drop test with ghc dependency

### PR DESCRIPTION
**Pull request by gilligan**
**Summary**
Drop a test that introduced a runtime dependency to ghc & dependenciesin PSGenerator (servant code generator for purescript).

**Details**
`PSGenerator` should only create the purescript sources that are actually required without carrying out integration tests. In this case this introduces a runtime dependency on a huge ghc closure with plutus dependencies. This also impacts some packaging glue code for the playground client. Last but not least it also impacted some ghc upgrade where the ghc failed on macOS.

---

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by merivale — COMMENTED** [review]
I agree in principle that it would be nicer not to have the PSGenerator create JSON for tests. But the tests need this JSON to come from somewhere, and I don't want to lose those tests. As things stand, it would be very easy for the Haskell and PureScript encoding instances to get out of sync and break the playground (this did actually happen once at the end of last year when all the tests were briefly not working).

I think there is a good way forward, but it will require a chunk of work... I think what we need to do is weed out all the types in the codebase that have custom encoding instances, and just use generic ones everywhere. And make sure the PureScript code is always using the generated types wherever there's communication. Then we will no longer need any tests like these.

I am optimistic this is doable. There were obviously reasons for the custom encoding instances when they were created, but PureScript (and purescript-bridge) have come on a way since then. Straightening this out is high up on the list of things I want to do after this month (when the initial Marlowe Run release is behind us and I can catch my breath again :sweat_smile: ). So unless you have a better plan for the tests, I would rather leave this here in the meantime.

**Comment by michaelpj** [comment]
Is the problem partly that we want to check whether a simulation response can be decoded, but we do so by *actually running a simulation*. Could we instead generate some example instances of the datatype directly and do the round-tripping on those?

**Comment by gilligan** [comment]
@merivale I'm happy to refactor/extract/(re)-implement or just generally come up with something that provides the guarantees that you are looking for.

At the moment, PSGenerator does the following:
1. Create Purescript code
1. Write json test data
1. Perform integration tests with the test data calling ghc

What it _should_ do is just _1_ and nothing else. If _3_ fails it doesn't even provide good readable visual feedback and it's not obvious to anyone that a test just failed. The Purescript code generation failed. But because too many different things are involved it's not even clear what the actual source or error was.

So what are our options?
- A nixos vm test that uses the *output* of PSGenerator to test something
- Create playground integration tests that use the *output* of PSGenerator to run tests
- Create some playground-server unit test (maybe not ideal because it isn't really a unit test and would only work when executed via nix)

Of course we should also nail down **what exactly needs to be tested** to think about specifics of how to implement/assert this. The "tests" in the PSGenerator are really not very explicit at all - it just tries to compile something which might fail.

@merivale @michaelpj WDYT?

**Comment by merivale** [comment]
AFAIK the PSGenerator isn't _intended_ to perform any integration tests, I think it's only running the simulator in order to get the JSON. So @michaelpj you might be on to something.

The integration tests themselves are in the Plutus playground client: [plutus-playground-client/test/JsonEncodingTests.purs](https://github.com/input-output-hk/plutus/blob/master/plutus-playground-client/test/JsonEncodingTests.purs). So that's the second of the three options you mention @gilligan. If we can generate some JSON for these tests some other way, I'll be happy - at least until, as I say, we can weed out all the custom encoding instances and avoid the need for these tests altogether.

**PS** @gilligan, the communication problems I've been having lately are between the PAB and the new Marlowe Run client, and aren't related to anything covered by these tests.

**Comment by gilligan** [comment]
closing this until i've moved the test elsewhere

**Pull request closed without merging**
