### PR TITLE
Empty commit for benchmark experiments

### PR DESCRIPTION
**Pull request by kwxm**
This is a follow-up to #4248.  I'm pretty sure I benchmarked the same commit on two different days and one lot of results was consistently 2-3% faster than the other.  I'm going to run the benchmarks multiple times on this branch to see if I can reproduce that.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by kwxm** [comment]
Running this a minute or two after the previous one.

/benchmark

**Comment by kwxm** [comment]
^ There was a terminal with an ssh connection to the server running `top` during this last one.

**Comment by kwxm** [comment]
> So it seems like the moral of the story is that changes of <1% are probably noise?

The story isn't finished yet...

But yes, I think we've been assuming that if we see results like those above, with small differences of both signs, then any difference is insignificant.  

I'm still looking at this though: I think that maybe you sometimes get different answers if you're doing things directly on the machine. but it's tricky to do that when buildkite can start running benchmark jobs without warning.

**Comment by michaelpj** [comment]
> I think that maybe you sometimes get different answers if you're doing things directly on the machine, but it's tricky to do that when buildkite can start running benchmark jobs without warning when you're logged in.

Yeah, the buildkite queue works to make sure that no jobs get scheduled simultaneously, but there's not much we can do at the moment about collisions with people running ad-hoc jobs. You'll just have to keep announcing in Slack when you're using the machine.

**Comment by kwxm** [comment]
I've been running the validation benchmarks occasionally since the end of November last year.  As the figures above show, the benchmarks apparently return very consistent results when run using `/benchmark`.  I also ran them many times from an ssh terminal on the benchmarking machine (sometimes reaming logged in, sometimes using `nohup`), checking that nothing else was running using `top` first.  The results are a bit odd. The first few runs took about 50%  longer than the figures obtained by running the benchmarks here, but then between 12:00 and 13:45 on the 5th of December they started to take the same amount of time: see the attached graph, where the red line shows the execution time for the `auction_1-1` script, the first one in the tables above.  I have no explanation for this.

bm-times

**Comment by kwxm** [comment]
In fact, the numerous automated benchmark results above aren't as consistent as they look. I originally started looking at this because I thought I'd run identical sets of benchmarks on two different days and seen uniform increases or decreases of 1%-3%, which might be taken to be statistically significant.  A closer look at the results above shows that this _was_ actually happening.  For example, below there's a comparison between the first column of [the table for the 7th of December](https://github.com/input-output-hk/plutus/pull/4257#issuecomment-987533419) and the first column of [the table for the 9th of December](https://github.com/input-output-hk/plutus/pull/4257#issuecomment-990329274).  The second lot of results are in general a little slower than the first, and we see a similar pattern for the second columns.  Comparisons between other runs shows similar differences. I think that what happening here is that there are small systematic differences between execution times from day to day (Who knows why? Maybe the room containing the machine's a bit warmer or cooler on some days or something), but these are over a sufficiently large timescale that they don't show up if you benchmark two branches in quick succession, which is exactly what the automated benchmarking process does.  So I think that we can trust what's happening with benchmarks that we run from GitHub, but we have to be a little more careful if we're doing things manually with big gaps between benchmark runs.x 

```Script                              7th Dec      9th Dec       Change
----------------------------------------------------------------------------------
auction_1-1                        406.5  μs    407.6  μs      +0.3%
auction_1-2                        1.196  ms    1.197  ms      +0.1%
auction_1-3                        1.200  ms    1.199  ms      -0.1%
auction_1-4                        538.5  μs    540.5  μs      +0.4%
auction_2-1                        407.1  μs    409.6  μs      +0.6%
auction_2-2                        1.189  ms    1.197  ms      +0.7%
auction_2-3                        1.496  ms    1.511  ms      +1.0%
auction_2-4                        1.196  ms    1.202  ms      +0.5%
auction_2-5                        538.3  μs    542.0  μs      +0.7%
crowdfunding-success-1             482.4  μs    485.9  μs      +0.7%
crowdfunding-success-2             482.4  μs    485.6  μs      +0.7%
crowdfunding-success-3             482.8  μs    485.0  μs      +0.5%
currency-1                         489.6  μs    491.5  μs      +0.4%
escrow-redeem_1-1                  748.4  μs    752.0  μs      +0.5%
escrow-redeem_1-2                  749.3  μs    750.6  μs      +0.2%
escrow-redeem_2-1                  856.7  μs    856.9  μs      +0.0%
escrow-redeem_2-2                  857.4  μs    855.4  μs      -0.2%
escrow-redeem_2-3                  858.5  μs    856.2  μs      -0.3%
escrow-refund-1                    357.3  μs    357.7  μs      +0.1%
future-increase-margin-1           490.5  μs    491.5  μs      +0.2%
future-increase-margin-2           1.081  ms    1.083  ms      +0.2%
future-increase-margin-3           1.081  ms    1.084  ms      +0.3%
future-increase-margin-4           980.1  μs    981.6  μs      +0.2%
future-increase-margin-5           1.432  ms    1.434  ms      +0.1%
future-pay-out-1                   489.4  μs    493.0  μs      +0.7%
future-pay-out-2                   1.077  ms    1.085  ms      +0.7%
future-pay-out-3                   1.081  ms    1.087  ms      +0.6%
future-pay-out-4                   1.430  ms    1.439  ms      +0.6%
future-settle-early-1              490.2  μs    492.6  μs      +0.5%
future-settle-early-2              1.080  ms    1.083  ms      +0.3%
future-settle-early-3              1.077  ms    1.083  ms      +0.6%
future-settle-early-4              1.133  ms    1.130  ms      -0.3%
game-sm-success_1-1                826.5  μs    822.9  μs      -0.4%
game-sm-success_1-2                459.2  μs    458.8  μs      -0.1%
game-sm-success_1-3                1.214  ms    1.212  ms      -0.2%
game-sm-success_1-4                533.8  μs    535.6  μs      +0.3%
game-sm-success_2-1                825.1  μs    826.6  μs      +0.2%
game-sm-success_2-2                458.3  μs    459.8  μs      +0.3%
game-sm-success_2-3                1.213  ms    1.212  ms      -0.1%
game-sm-success_2-4                533.2  μs    536.3  μs      +0.6%
game-sm-success_2-5                1.212  ms    1.210  ms      -0.2%
game-sm-success_2-6                532.9  μs    535.8  μs      +0.5%
multisig-sm-1                      825.6  μs    826.3  μs      +0.1%
multisig-sm-2                      816.6  μs    816.7  μs      +0.0%
multisig-sm-3                      823.1  μs    826.6  μs      +0.4%
multisig-sm-4                      831.5  μs    836.1  μs      +0.6%
multisig-sm-5                      1.072  ms    1.082  ms      +0.9%
multisig-sm-6                      824.7  μs    833.0  μs      +1.0%
multisig-sm-7                      815.5  μs    822.3  μs      +0.8%
multisig-sm-8                      822.4  μs    830.2  μs      +0.9%
multisig-sm-9                      828.3  μs    835.6  μs      +0.9%
multisig-sm-10                     1.074  ms    1.080  ms      +0.6%
ping-pong-1                        683.2  μs    687.9  μs      +0.7%
ping-pong-2                        683.8  μs    688.9  μs      +0.7%
ping-pong_2-1                      439.8  μs    442.1  μs      +0.5%
prism-1                            380.3  μs    382.3  μs      +0.5%
prism-2                            883.7  μs    887.1  μs      +0.4%
prism-3                            762.5  μs    767.2  μs      +0.6%
pubkey-1                           324.9  μs    326.6  μs      +0.5%
stablecoin_1-1                     1.696  ms    1.696  ms       0.0%
stablecoin_1-2                     448.8  μs    449.4  μs      +0.1%
stablecoin_1-3                     1.943  ms    1.948  ms      +0.3%
stablecoin_1-4                     474.2  μs    478.3  μs      +0.9%
stablecoin_1-5                     2.480  ms    2.495  ms      +0.6%
stablecoin_1-6                     590.2  μs    594.8  μs      +0.8%
stablecoin_2-1                     1.693  ms    1.698  ms      +0.3%
stablecoin_2-2                     446.7  μs    450.5  μs      +0.9%
stablecoin_2-3                     1.938  ms    1.944  ms      +0.3%
stablecoin_2-4                     473.7  μs    477.5  μs      +0.8%
token-account-1                    389.4  μs    390.9  μs      +0.4%
token-account-2                    682.2  μs    685.1  μs      +0.4%
uniswap-1                          767.0  μs    768.0  μs      +0.1%
uniswap-2                          472.9  μs    474.0  μs      +0.2%
uniswap-3                          3.134  ms    3.142  ms      +0.3%
uniswap-4                          770.5  μs    774.3  μs      +0.5%
uniswap-5                          2.264  ms    2.260  ms      -0.2%
uniswap-6                          737.8  μs    738.6  μs      +0.1%
vesting-1                          697.1  μs    697.4  μs      +0.0%
```

**Comment by kwxm** [comment]
OK, I think I've found out what I wanted here.

**Pull request closed without merging**
