### PR TITLE
Add untyped examples to plc command (SCP-1752)

### PR DESCRIPTION
**Pull request by kwxm**
By default the `plc` command now works with untyped PLC, but the `example` command was producing typed examples.  This PR makes it produce untyped examples by default (you can still say `plc example -a --typed` to get the typed ones).  The untyped examples are just got by erasing the typed ones; it might be good to have some genuine untyped examples.  See also SCP-1453.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by kwxm** [comment]
Looks as if this has broken the Agda stuff.

**Comment by jmchapman** [comment]
that shouldn't be hard to fix, I'll have a look

**Comment by jmchapman** [comment]
I think I've fixed the tests `plutus-metatheory` so that they work with the typed examples now. But, I think the are now some tests which are actually failing - I wonder if they were 'passing' before as the outputs being compared were the same parse error...

> that shouldn't be hard to fix, I'll have a look

Famous last words.

**Comment by jmchapman** [comment]
That's strange. It seems to pass CI but fails locally for me on some with some evaluations using the extrinsically typed evaluator failing.

**Comment by jmchapman** [comment]
I updated the list of modules. I hope this should make the warning go away and I hoped it might fix @kwxm's local linker error.

I don't think this PR should be held up by these flaky tests in plutus-metatheory anyway. I should revisit them in a seperate PR.

**Review by jmchapman — APPROVED** [review]

**Comment by kwxm** [comment]
James' contributions seem to have fixed the Agda issues.  I still get some local test failures with `cabal v2-test plutus-metatheory`, but it'd passing CI so I'm not sure what the difference is.  This shouldn't affect anything else, so I'll go ahead and merge it to get it out of the way.

**Pull request merged**
