### PR TITLE
no-op: fix typos in technical documentation

### PR DESCRIPTION
**Pull request by kk-hainq**
This fixes a small typo in the ledger documentation.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by j-mueller — APPROVED** [review]

**Comment by j-mueller** [comment]
Thank you!

**Comment by kk-hainq** [comment]
@j-mueller We are a team of passionate developers really wanting to contribute to Plutus. Reading through every single word of the documentation is one of our starting points and we've found many more typos like this. We didn't know if you'd welcome these minor changes but now that you do, should we push the rest to this branch?

**Comment by j-mueller** [comment]
@kk-hainq Yes if it's just more typos you can add them to this branch. At the moment, contributing to the project it is a bit hard because things are still changing, but it should get better as we get closer to the relase. Contributions are always welcome.

**Comment by kk-hainq** [comment]
Awesome, thanks. I've converted this PR to a draft, will add the remaining typo fixes and report back once done.

**Comment by michaelpj** [comment]
Has conflicts

**Pull request merged**
