### PR TITLE
Fix dependent-sum issue through bounding some

### PR DESCRIPTION
**Pull request by michaelpj**
- Bound some to get a newer dependent-sum
- Bump hackage and CHaP

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
This is based on Andrea's idea from https://github.com/input-output-hk/cardano-haskell-packages/pull/167#issuecomment-1482060744

I also bumped Hackage so we could actually get a newer `some` which would manifest the issue if it wasn't fixed.

**Comment by zliu41** [comment]
This could be a problem if a downstream project needs a newer `some`.
Then it would need to `allow-newer`, but then that would make cabal pick an older `dependent-sum` and fail to build which is confusing.
How about sticking an unused import in some module so that we do depend on `dependent-sum` directly?

**Comment by michaelpj** [comment]
>  How about sticking an unused import in some module so that we do depend on dependent-sum directly?

Oh yes, that's a good idea. I'll do that.

**Review by zliu41 — APPROVED** [review]

**Pull request merged**
