### PR TITLE
ledger: Semigroup instance for intervals

### PR DESCRIPTION
**Pull request by j-mueller**

### CODE REVIEW

**Comment by michaelpj** [comment]
You could also define a semigroup instance that did the opposite. That would have the advantage of being a monoid, with the zero being the unbounded interval. Not sure what you're using this for, though.

**Comment by j-mueller** [comment]
I want to merge two event triggers to get one that includes both, so I need it to be convex. But you're right there isn't a single obvious instance, maybe I should just add `hull` and `intersection` like in  [`Numeric.Interval`](https://hackage.haskell.org/package/intervals-0.9/docs/Numeric-Interval.html).

**Comment by michaelpj** [comment]
I think it's really more of a lattice, so yeah, I'd go with that.

**Comment by michaelpj** [comment]
You could even use the lattice class from http://hackage.haskell.org/package/lattices, but that's probably overkill.

**Comment by j-mueller** [comment]
Nice package, but it would only work in the off-chain bits of the code that uses intervals

**Comment by michaelpj** [comment]
Also true for the semigroup instance, no? But yeah, having the functions as straight functions also seems a good idea.

**Comment by j-mueller** [comment]
Yeah that's true...

I settled on requiring `Ord` and `Eq` for `hull` and `intersection` but I also added some functions that should work in on-chain code. `intersection` actually has to return a `Maybe (Interval a)` because we don't have empty intervals. (Unless we say `Interval (Just x) (Just x)` is empty, but then that should be also be the unit for `hull`, etc.)

**Pull request merged**
