### PR TITLE
Eval time experiment

### PR DESCRIPTION
**Pull request by michaelpj**
Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by rvl — COMMENTED** [review]
This seems like it would reduce the number of packages which Cabal needs to solve for.

And I think it would also reduce the total number of components in `hsPkgs` because only libraries and exes would remain for most packages.

From my own testing, I understand that users will need Cabal >= 3.4.0.0 to build successfully, because older versions get confused by the trick where tests and benchmarks are false except for the packages listed.

**Comment by michaelpj** [comment]
This takes it to 1000s rather than 1700s, which is better. But it might just mostly achieve the same thing as Hamish's fix. We can try it after that and see if it adds more.

**Comment by michaelpj** [comment]
I think we should merge this for now, it makes a big difference and the proper fix is going to take a while.

**Comment by michaelpj** [comment]
Turns out that's false, it isn't actually having any effect! I must have been seeing an inflated figure before somehow :thinking:

**Pull request closed without merging**
