### PR TITLE
experiment: globarray

### PR DESCRIPTION
**Pull request by bezirg**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
That looked kind of good!

**Comment by bezirg** [comment]
I didn't like it that much. It looks like it can bring some perf. benefit (for certain types of programs), 
but the overhead of applying this optimization and maintaining its code is problematic. 

Perhaps if we had a different plutus-like v3 language that had global vars as 1st class citizens, then it could be another story.

**Comment by bezirg** [comment]
Also the code here is not good to bring it in.

**Comment by michaelpj** [comment]
Right, we'd have to compare with a `validation-full` that includes the cost of running the optimization at least.

**Pull request closed without merging**
