### PR TITLE
ChainIndex CLI: continue to sync from tip

### PR DESCRIPTION
**Pull request by kk-hainq**
This adds persistent syncing to the Chain Index CLI, to continue to sync from the last tip. Previously it re-syncs from genesis on every start.

A few more ideas we'd like to add to this repo:
- Better error handling. For example, a wrong socket path isn't handled at the moment, the program doesn't even exit, just doesn't sync!
- Package the ChainIndex CLI with a Cardano Node with Docker/Nix.
- Add an extension/customization interface for dApp developers to structure their own caches/UTXO pools for faster queries and UTXO discovery.
- Write setup, customization, and API documentation.

Do tell us if you'd want us to work on anything!

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
Thank you for this PR! It looks good but I was already working on this too, see https://github.com/input-output-hk/plutus/compare/SCP-2755/chain-index-utxo-state-db-backend?expand=1 

That code goes a bit further as it supports multiple resume points (in case the tip has been rolled back for example), so I'm closing this PR in favour of that branch.

The other points you are suggesting sound good, as far as I know no one is working on those. Correct me if I'm wrong @j-mueller .

**Comment by kk-hainq** [comment]
@sjoerdvisscher Awesome thanks. Having `utxo` over `tip` is two wins in one!

**Comment by j-mueller** [comment]
@kk-hainq Thanks for the contribution and sorry that there is some overlap with what we had been doing already. But I like the list of ideas

> Better error handling

Yes any PRs for that would be much appreciated

> Package the ChainIndex CLI with a Cardano Node with Docker/Nix

That's a very good idea - we already have a docker container built with nix (`devcontainer.nix`) so you could use that as a starting point.

> Add an extension/customization interface for dApp developers to structure their own caches/UTXO pools for faster queries and UTXO discovery.

Do you have any more details on that? We can open a separate GH issue to talk about it

> Write setup, customization, and API documentation.

More documentation is also always appreciated. A good starting point would be to add swagger/openapi3 support to the chain index API, similar to https://github.com/input-output-hk/plutus/pull/3807

Our own plans for the chain index are mostly about improving performance & reducing memory consumption. We're also going to add two features in the near future: Improving pagination (the result of `UtxoAtAddress`) and adding a query for UTXOs that contain tokens of a user-defined currency (Policy ID + asset name).

**Comment by kk-hainq** [comment]
@j-mueller Thank you for the information! We'll open a Github issue to track all these plans.

**Pull request closed without merging**
