### PR TITLE
Kwxm/plutus papers/add doi info

### PR DESCRIPTION
**Pull request by kwxm**
Add DOI info for the papers, as suggested by @jmchapman.

### CODE REVIEW

**Comment by michaelpj** [comment]
I'm confused: I thought the discussion we had was bout what to do with the drafts in the `plutus-papers` repository? James [already added](https://github.com/input-output-hk/plutus/pull/1551) DOI information in this repository.

**Comment by jmchapman** [comment]
But that was in a different place, I think it's useful to have more information.

**Comment by kwxm** [comment]
> I'm confused: I thought the discussion we had was bout what to do with the drafts in the `plutus-papers` repository? James [already added](https://github.com/input-output-hk/plutus/pull/1551) DOI information in this repository.

Sorry, I missed that: it's buried in the middle of the big README file.  I don't think it'll do any harm having the DOIs here as well though.  I already added the same info in the plutus-papers repository, together with pointers to the directories here.

**Comment by michaelpj** [comment]
Okay, seems fine.

**Pull request merged**
