### PR TITLE
[WIP] Plutus core/generate well typed

### PR DESCRIPTION
**Pull request by effectfully**
This contains well-typed terms generation and tests related to naturals, lists and `fix` in the context of evaluation. I'll also type check also those terms.

### CODE REVIEW

**Comment by effectfully** [comment]
@mchakravarty, okay, this PR is huge and some stuff is complicated, so it's probably hard to review it. I'd like to add comments to one file, but other than that the PR seems to be ready to merge. I think I'd prefer to add comments in a separate PR, so the RV team can use the tests generating executable I added as soon as possible. Also I learned now very well that it's better to merge a PR when it's ready rather than when it's completely polished, because merging the recent changes in `master` was very tiresome.

**Comment by effectfully** [comment]
@mchakravarty, also please review [my additions to the readme](https://github.com/input-output-hk/plutus-prototype/blob/d829125d6ac81d08a5512129f873f308b00e7d6e/language-plutus-core/README.md#evaluation).

**Comment by effectfully** [comment]
@michaelpj, I thought I was doing a right thing by merging @vmchale's work into mine... This PR has Vanessa's changes (up to a certain point) merged and we can merge it into master, but I do not really know whether it's a sane thing to do.

Could you guys advice?

**Comment by effectfully** [comment]
Also I feel like our changes are mostly tangential, I just wanted the type checker fixes.

**Comment by michaelpj** [comment]
Well, if we merge this into master we effectively merge a partial, unreviewed version of Vanessa's work, right? You could try rebasing on master and removing the merges, but I don't know how cleanly that will go.

I also think it's bad that Vanessa's PR has been open for so long - I'd really prefer it if we used PRs for small, independent chunks of work that we can merge quickly, rather that being half done when they're opened.

**Comment by vmchale** [comment]
My branch should be merge-able at this point, since it does not introduce any errors I am aware of.

I will work with smaller-scope changes in the future - at the very least I will not again so something like putting CBOR and type-checking fixes in the same PR.

**Comment by effectfully** [comment]
> Well, if we merge this into master we effectively merge a partial, unreviewed version of Vanessa's work, right? 

True.

> My branch should be merge-able at this point, since it does not introduce any errors I am aware of.

I tried to merge yours into mine and got so many conflicts...

**Comment by effectfully** [comment]
Closed in favor of #52.

**Pull request closed without merging**
