### PR TITLE
Fix rolepayout benchmarks.

### PR DESCRIPTION
**Pull request by thealmarty**
This should fix the problem of the role payout benchmarks having bad names, as [promised](https://github.com/input-output-hk/plutus/pull/5421#issuecomment-1636000977).

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Changelog fragments have been written (if appropriate)
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [x] Targeting master unless this is a cherry-pick backport
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Review by kwxm — COMMENTED** [review]
I think this still won't work.  The awk script that does the benchmark results comparison assumes that the benchmark names don't contain any whitespace.  It [gets the benchmark names](https://github.com/input-output-hk/plutus/blob/a25bbdbd51ccb18e9650fd67149b20d398134aee/plutus-benchmark/bench-compare-markdown#L39) from the lines where Cirterion prints out "benchmarking ..." by looking at the second field (`$2)`on the line, where it regards fields as being separated by whitespace.  When I run the benchmarks locally I get things like
```
benchmarking role payout/121a0a1b12030616111f02121a0e070716090a0e031c071419121f141409031d
```
so it will think that the benchmark name is "role".  To fix this we can either allow spaces in benchmark names and modify the awk script to take the whole of the rest of the line after `benchmarking " to be the name, or change the [name](https://github.com/input-output-hk/plutus/blob/8998a16a2ddcc08ae2edfe490df58f55d871aa44/plutus-benchmark/marlowe/bench/Bench.hs#L78) to be "role-payout/xxxx..." or something.

Note also that changes like this won't immediately show up in the output of `/benchmark` because the script just takes the names from the first run of the benchmarks and ignores the names in the second run (so the benchmarks in the two runs had better match up) so even if we change the names in this branch it'll still use the old ones from `master`.  

It might also make the output more readable if we just took the first few digits from the big hex string in the script name instead of the whole thing.  Incidentally, do you know what these numbers represent? I'd assumed that they were hashes but the first few [here](https://github.com/input-output-hk/plutus/tree/thealmarty/fix-marlowe-bench-bug/plutus-benchmark/marlowe/scripts/rolepayout) surely can't be hashes.

**Comment by kwxm** [comment]
I notice that a number of the Haskell files contain [a lot of pragmas](https://github.com/input-output-hk/plutus/blob/8998a16a2ddcc08ae2edfe490df58f55d871aa44/plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/RolePayout.hs#L18) at the start and they're surely not all necessary.  Can we get rid of the extra ones, or is this some standard set of pragmas that we're inheriting from the Marlowe code?

**Comment by thealmarty** [comment]
Thanks Kenneth!

> so it will think that the benchmark name is "role". To fix this we can either allow spaces in benchmark names and modify the awk script to take the whole of the rest of the line after `benchmarking " to be the name, or change the [name](https://github.com/input-output-hk/plutus/blob/8998a16a2ddcc08ae2edfe490df58f55d871aa44/plutus-benchmark/marlowe/bench/Bench.hs#L78) to be "role-payout/xxxx..." or something.

I used your last suggestion.
> 
> Note also that changes like this won't immediately show up in the output of `/benchmark` because the script just takes the names from the first run of the benchmarks and ignores the names in the second run (so the benchmarks in the two runs had better match up) so even if we change the names in this branch it'll still use the old ones from `master`.
> 

So how do we fix this? I don't think the script should do that right? It should always check the names because we may change the code.

> It might also make the output more readable if we just took the first few digits from the big hex string in the script name instead of the whole thing. Incidentally, do you know what these numbers represent? I'd assumed that they were hashes but it seems very unlikely that he first few [here](https://github.com/input-output-hk/plutus/tree/thealmarty/fix-marlowe-bench-bug/plutus-benchmark/marlowe/scripts/rolepayout) can be hashes.

I thought they are transaction IDs, I have no idea in what form. I don't think it'll be more readable if I just cut off the first few digits but I don't know how to make it more readable.

**Comment by thealmarty** [comment]
hm...I guess I just need to merge this to see the updated names. I'll remove some more pragmas first.

**Comment by kwxm** [comment]
> So how do we fix this? I don't think the script should do that right? It should always check the names because we may change the code.

I think that would be rather difficult.  If we rename benchmarks for example then there's no way to tell which old names correspond to which new ones, so the script would just have to fail.  I think the best that we could do would be to construct a mapping from benchmark names to execution times for both sets of benchmarks (one mapping for each set of benchmarks) then check that we have exactly the same set of names for both and match up the results and print out the statistics for the matching pairs.  If some name exists in one set but not in the other then it'd have to issue an error message (so in this case we'd get an error for every role-payout example). Even doing that would add quite significant complexity to the script, and there will probably still be situations we won't be able to deal with, like if we rename benchmark A to B and B to A (which would be a silly thing to do, but I suppose it could happen).  It is pretty obvious if something has gone wrong at the moment, like if you re-order the benchmarks then the numbers you get probably just won't make sense.

What do the longitudinal benchmarks do if the benchmarks are run in a different order or if you add some new ones?

**Comment by thealmarty** [comment]
> > So how do we fix this? I don't think the script should do that right? It should always check the names because we may change the code.
> 
> I think that would be rather difficult. If we rename benchmarks for example then there's no way to tell which old names correspond to which new ones, so the script would just have to fail. I think the best that we could do would be to construct a mapping from benchmark names to execution times for both sets of benchmarks (one mapping for each set of benchmarks) then check that we have exactly the same set of names for both and match up the results and print out the statistics for the matching pairs. If some name exists in one set but not in the other then it'd have to issue an error message (so in this case we'd get an error for every role-payout example). Even doing that would add quite significant complexity to the script, and there will probably still be situations we won't be able to deal with, like if we rename benchmark A to B and B to A (which would be a silly thing to do, but I suppose it could happen). It is pretty obvious if something has gone wrong at the moment: if you re-order the benchmarks for example then the numbers you get probably just won't make sense.
> 

Good point.

> What do the longitudinal benchmarks do if the benchmarks are run in a different order or if you add some new ones?

Good question! No idea!

**Comment by thealmarty** [comment]
> The reason I mentioned that is because on my screen the table is too narrow and I have to go to the bottom and scroll horizontally to see the numbers. I don't have any good suggestions for fixing it though!

The reason I'm a little hesitant to trim it down is because then it's not really anything anymore. Right now it's a transaction ID in some form.

**Comment by thealmarty** [comment]
I've taken out a lot of the pragmas. @kwxm do you want to take another look? Thanks. After it's merged I'll try benchmarking again to make sure it's good.

**Review by kwxm — APPROVED** [review]
Yep, this all looks good.  Thanks!

**Pull request merged**
