### PR TITLE
[Names] Make 'NamedDeBruijn' strict

### PR DESCRIPTION
**Pull request by effectfully**
I'm on my "make everything on the way of evaluation strict" crusade.

### CODE REVIEW

**Comment by effectfully** [comment]
Same: -6.54%. Anybody has any idea why so good?

**Comment by michaelpj** [comment]
You are kidding me! Baffling. I have no idea why that makes a difference, maybe it does ultimately cause some unpacking now??

**Comment by effectfully** [comment]
Maybe calculating the indices now happens during deserialization rather than evaluation or something?

**Comment by effectfully** [comment]
-6.13% of total **validation** time. OK, clear win, I guess.

**Comment by bezirg** [comment]
nice, i wonder why never tried that.

**Review by bezirg — APPROVED** [review]

**Pull request merged**
