### PR TITLE
ContractResponse: enforce PABResp with PABReq

### PR DESCRIPTION
**Pull request by luigy**
in order to minimize mismatches similar to the one on https://github.com/input-output-hk/plutus/pull/3628/commits/83a1f3908117ce2e75bd403bdea7f0f574d722eb #3628 

Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Review by j-mueller — APPROVED** [review]
Makes sense!

**Comment by luigy** [comment]
@michaelpj looks like hydra failed to update the status

**Comment by michaelpj** [comment]
True, but it also has conflicts.

**Comment by silky** [comment]
@michaelpj That's my fault; I snuck in a merge between @luigy 's comment and yours :D

**Comment by luigy** [comment]
Oh looks like that just happened after my comment. I'll update which will hopefully get hydra through

**Pull request merged**
