### PR TITLE
Bump Plutus to GHC-8.10.7

### PR DESCRIPTION
**Pull request by sevanspowell**

### CODE REVIEW

**Comment by michaelpj** [comment]
Why? 

Note that this will break the [workaround](https://github.com/input-output-hk/plutus/pull/4299) for the questionable [haskell.nix patch](https://github.com/input-output-hk/haskell.nix/issues/1280), so I don't want to merge it unless that's fixed.

Also you need to update the materialized files, have a read of CONTRIBUTING.

**Comment by sevanspowell** [comment]
See thread here: https://input-output-rnd.slack.com/archives/C21UF2WVC/p1641799667005900

Long thread, so tldr:

  1. cardano-wallet wants to use some plutus libraries in it's tests.
  2. cardano-wallet then needs to depend on plutus/plutus-apps.
  3. cardano-wallet uses GHC 8.10.7 (and needs to for some M1 fixes), build of Plutus wasn't working with GHC 8.10.7 due to something around that questionable haskell.nix patch and GHC.Tickish.
  4. Tried some workarounds, no success.
  5. So then tried to upgrade Plutus to GHC 8.10.7 and solve the underlying issue/fix the questionable haskell.nix patch.
  6. In the meantime Moritz submitted a workaround for my issue, which works: https://github.com/input-output-hk/plutus/pull/4325

So the pull request isn't needed and can be closed as soon as https://github.com/input-output-hk/plutus/pull/4325 is merged.

**Comment by michaelpj** [comment]
> cardano-wallet uses GHC 8.10.7 (and needs to for some M1 fixes), build of Plutus wasn't working with GHC 8.10.7 due to something around that questionable haskell.nix patch and GHC.Tickish.

That doesn't seem like it should be true. The GHC 8.10.7 in haskell.nix *also* has that patch applied: https://github.com/input-output-hk/haskell.nix/blob/master/overlays/bootstrap.nix#L175

What actually went wrong?

**Comment by michaelpj** [comment]
Oh I see - perhaps the issue is that you *didn't* get the change for the patch because of the workaround, hence the need for a flag you can turn on. How irritating.

**Comment by sevanspowell** [comment]
I think it'll be best to approach upgrading the GHC version as part of it's own task. At the moment this is three layers deep on a rabbit hole for me, so I'll close this for now.

**Pull request closed without merging**
