### PR TITLE
SCP-2504: Use blake2_224 for address hashes

### PR DESCRIPTION
**Pull request by j-mueller**
We should use the same hash function that the ledger uses. This PR changes the hash functions for validators, minting policies and public keys to Blake2_224. This is important for the conversion functions in `Plutus.Contract.CardanoAPI`, because they fail if they encounter a hash of the wrong length (SHA256 has 32 bytes, Blake2_224 only has 28 bytes).

The next steps are
* Move the hashing functions from `plutus-ledger-api` to `plutus-contract`
* Change the emulator to use `cardano-api` key types

Which I'll add some Jira issues for.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [x] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
I imagine there is stuff for this in `cardano-api`, could we use that or would that require changing loads of stuff?

**Review by michaelpj — APPROVED** [review]

**Comment by j-mueller** [comment]
I just discovered that we also need to change the minting policy & validator script hashes, so I'll add that to this PR. As well as some other changes required to get the `export` function to run through without error.

> I imagine there is stuff for this in cardano-api

Yeah looks like we can use `Cardano.Api.Script.hashScript` for the scripts at least. The keys aren't straightforward because we need to use the proper key types in the emulator (which is generally a good idea!)

**Review by michaelpj — APPROVED** [review]

**Comment by j-mueller** [comment]
Darwin build are timing out but the rest seems to be fine

**Comment by michaelpj** [comment]
Yep, let's merge this to unbreak stuff.

**Pull request merged**
