### PR TITLE
Kwxm/cek variations note

### PR DESCRIPTION
**Pull request by kwxm**
Some experiments with various CEK evaluation strategies.

### CODE REVIEW

**Comment by michaelpj** [comment]
Looks plausible! Main issue is I guess what Roman raised.

> There are even different ideas of what one might consider 'saturation' - i.e., is arrow or forall allowed in the return type of a builtin?

I think saturation here depends on the builtin itself not just its type: so a builtin application should be considered saturated if it has all its arguments, regardless of what the result type is.

**Comment by kwxm** [comment]
> There are even different ideas of what one might consider 'saturation' - i.e., is arrow or forall allowed in the return type of a builtin?
en 
Yes!  We have to do both of these already.  We used to have builtins that returned Scott booleans, which are universally quantified, and the new built-in `ifThenElse` can return things of function type (after being instantiated suitably).  These issues were a bit of an annoyance in the implementation, since we can't tell from the type of a builtinλ how many arguments it has: both `add m n = m+n` and `plus n = λm.m+n` have type `int → int → int`, but the first requires two arguments to be fully applied and the second only one, so we need a specialised type representation to distinguish the two.   I don't know if there's any standard way of dealing with proper multi-argument functions in type theory.  Usually everything's just curried, which is OK in theory, but inefficient in practice.

**Comment by effectfully** [comment]
@jmchapman 

> I believe that the CK or reduction semantics might be slower but have ideal memory usage. Perhaps we should compare against one or both of them too? (I guess this one is a review comment and connected to the pruning/memory safety of (3)).

I agree it would be nice to include the CK machine in the comparison.

@michaelpj 

> Looks plausible! Main issue is I guess what Roman raised.

Just to mention it here: the problem is that the alternative version of the CEK machine still tries to iterate through arguments of a builtin trying to reduce at each step until reduction succeeds. But the alternative version does not need this nonsense, so I'm going to update it.

@kwxm 

> Usually everything's just curried, which is OK in theory, but inefficient in practice.

Note though that our practice is vastly different: we lambda-encode all data types and so we have way too many lambdas and their applications. Making only builtin functions saturated for efficiency reasons seems weird, I conjecture that optimizing lambda application would give us a more noticeable speedup (provided we fix the iteration through prefixes of the list of arguments thing). And note that we are not doing any kind of push/enter or eval/apply anyway, so I don't think that having saturated builtins is actually going to give us any substantial performance boost (but that is something that we need benchmarks for).

**Comment by kwxm** [comment]
4. I believe that the CK or reduction semantics might be slower but have ideal memory usage. Perhaps we should compare against one or both of them too? (I guess this one is a review comment and connected to the pruning/memory safety of (3)).

I did that, but I left it out of the graphs because it pushed all the CEK stuff down to the bottom.  I think the memory usage is much worse in general because substituting things bodily can give you huge intermediate terms.  I can generate those graphs again and add them.

**Comment by kwxm** [comment]
> Note though that our practice is vastly different: we lambda-encode all data types and so we have way too many lambdas and their applications. Making only builtin functions saturated for efficiency reasons seems weird, I conjecture that optimizing lambda application would give us a more noticeable speedup (provided we fix the iteration through prefixes of the list of arguments thing). 

I agree with that. It would be a bit unnatural to have multi-argument builtins but single-argument lambdas, and having multi-argument lambdas could speed things up a lot.  It'd be a lot of work though, and it'd really complicate things.  Maybe we can do that when we get to `(program 2.0.0 ...)`:  I guess it's always useful to have something up your sleeve for future improvements...

**Comment by kwxm** [comment]
>     4. I believe that the CK or reduction semantics might be slower but have ideal memory usage. Perhaps we should compare against one or both of them too? (I guess this one is a review comment and connected to the pruning/memory safety of (3)).

I've now added an appendix in CEK-variations-stats-appendix.md with graphs including the (unsaturated) CK machine.  The memory usage seems to be worse than the CEK machines except in the case of Fibonacci.  No idea why. These examples all use the Z combinator and I'm not really sure what the machines do with that (exercise for self: work through an example to see exactly what's going on).  I didn't look at the saturated CK machine, but I may do that and update the graphs later.  

When we have some better benchmarks we should take another look at CK machine performance.

**Comment by kwxm** [comment]
We're still experimenting with different builtin evaluation strategies, so let's not merge this just yet.

**Comment by kwxm** [comment]
Looks like we're going with the alternative CEK machine and unsaturated builtins.  I'm going to merge this now.

**Pull request merged**
