### PR TITLE
Update customised Criterion template for jchart (SCP 1963)

### PR DESCRIPTION
**Pull request by kwxm**
The Criterion graph-rendering stuff was reworked quite a bit in [this commit](https://github.com/haskell/criterion/commit/50eadc5679446b42c73385955343b6b95e93ad7e), and in particular it now uses `jchart` for rendering instead of `jflot` (?).  The plutus benchmarks use a modified template file which adds some more information to the report and that got broken by the refactoring, leading to a number of error messages at the end when Criterion was trying to produce `report.html`  This PR fixes that (so we now get the fancy new charts as well).  It now won't work with older versions of Criterion, but you can point it to `default-old.tpl` using the `-t` option to work around that.  See the comment near the top of the JavaScript in `with-iterations.tpl` for a complication that arose because of the way Criterion was refactored.

@bezirg had some problems with `plutus-benchmark` a while ago and this may fix that.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
I say: just kill the old template and put a lower bound on `criterion` in the cabal file.

**Review by michaelpj — APPROVED** [review]
I have no idea how these templates work, so I'm just going to assume they're right :sweat_smile:

**Comment by kwxm** [comment]
> I say: just kill the old template and put a lower bound on `criterion` in the cabal file.

Yeah, you're probably right.  I'll look at that later.

**Comment by bezirg** [comment]
I ran the following command both under `plutus` and `plutus/plutus-benchmark`:

```
$cabal bench plutus-benchmark:nofib --benchmark-options "clausify/formula2 -L1 --output /tmp/report.html"
```

and the report is generated correctly.

The `plutus-benchmark/README.md` says that `cabal run` can be used in place of `cabal bench`. When using `cabal run` however, I think the `--benchmark-options` are ignored and all the benches are run. This happens with 
```
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
```

This may be a problem of Cabal, because `--benchmark-options` is listed  in `cabal run --help`. Better to remove the mention of `cabal run`?

**Review by bezirg — APPROVED** [review]

**Comment by kwxm** [comment]
> I say: just kill the old template and put a lower bound on `criterion` in the cabal file.

I've done that now.  I just put the bound in `plutus-benchmark.cabal`.  Is that all that's required?

**Comment by kwxm** [comment]
> The `plutus-benchmark/README.md` says that `cabal run` can be used in place of `cabal bench`. When using `cabal run` however, I think the `--benchmark-options` are ignored and all the benches are run.

Hmm, you're right.  Thanks for pointing that out.  I thought I'd tried that and it worked, but as you say it seems to ignore the stuff in `--benchmark-options`.  However, I tried putting the options after `--` and that did work:

```
   cabal run plutus-benchmark:validation -- future --output ~/tmp.html -L10
```

I've updated `README.md` to mention that, although it does seem kind of random.  I guess the stuff after `--` must just be getting passed on to the benchmark executable like the arguments for another program, and the Criterion library code gets access to that somehow via `defaultMainWIth`.

**Comment by michaelpj** [comment]
> I've done that now. I just put the bound in plutus-benchmark.cabal. Is that all that's required?

Yep, I think that's fine.

**Comment by kwxm** [comment]
> > I've done that now. I just put the bound in plutus-benchmark.cabal. Is that all that's required?
> 
> Yep, I think that's fine.

In that case I'll merge it!  I was a bit suspicious that I didn't have to do anything nix-related.

**Pull request merged**
