### PR TITLE
Fix for #1448 (I think)

### PR DESCRIPTION
**Pull request by kwxm**
See #1448.  The redeemer has the wrong type.

### CODE REVIEW

**Comment by michaelpj** [comment]
This isn't quite right: we need to do something different depending on whether it's the last withdrawal or not. If it is the last then there is no ongoing data script so you need a different redeemer. See other examples (often the redeemers are called `redeemer0` etc.)

**Comment by kwxm** [comment]
Damn: you're right.  Everything's OK until you try to empty out the scheme altogether, then it fails.  I'll try to fix that.

**Comment by kwxm** [comment]
Let's try that again: now we choose one of two redeemers according to whether or not the scheme is empty.

You get a pretty exciting error message if you try to take too much money out, but at least that really is an error.

**Comment by kwxm** [comment]
I believe this is  now correct (modulo not actually doing anything with the contents of the datascripts).

**Pull request merged**
