### PR TITLE
SCP-1900: Build combined doc-index.json

### PR DESCRIPTION
**Pull request by silky**
Following this example: https://github.com/input-output-hk/ouroboros-network/blob/2068d091bc7dcd3f4538fb76f1b598f219d1e0c8/scripts/haddocs.sh#L87 we add a step after the haddock generation to write a combined `doc-index.json` so that searching works! Note that for searching to work locally, you need to open the HTML files through a webserver (if we wanted to serve the docs via a webserver I can look into that, perhaps as a separate item?).

Fixes SCP-1900

I'm just assuming this will work when the docs get pushed; I'm hoping I can check this via one of the CI actions?

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by j-mueller** [comment]
Nice. Unfortunately the `docs.site` doesn't get deployed anywhere for PRs. If you've checked the generated `doc-index.json` and it looks sensible, then I'd be willing to just merge it and see if it works on https://playground.plutus.iohkdev.io/tutorial/haddock/index.html ...

**Review by j-mueller — APPROVED** [review]

**Comment by michaelpj** [comment]
I look forward to the day we can finally use something like https://github.com/haskell/haddock/pull/1277...

**Comment by silky** [comment]
Indeed @michaelpj ; I was amused that when I was searching around for reasonable ways to solve this problem the code I found was from IO already :)

@j-mueller - sounds good :) Indeed I checked that it works (albeit takes a second to load the UI) and takes you to the right spot :) I'm happy to be hopeful it'll work!

image

**Comment by michaelpj** [comment]
Can we add a comment with where you got it from, so if it stops working we can go steal the updated version instead of trying to work out what that `jq` invocation is doing? :grin:

**Comment by silky** [comment]
@michaelpj added

**Comment by michaelpj** [comment]
:+1:

**Pull request merged**
