### PR TITLE
Relicense as Apache 2.0

### PR DESCRIPTION
**Pull request by michaelpj**
- Add `LICENSE` and `NOTICE` in the root.
    - This gets picked up by Github and covers things which aren't
      licensed separately (like docs).
- Add `LICENSE` and `NOTICE` to all Haskell packages.
    - Cabal doesn't like you referring to a file outside the source root
      in `license-files`, so we need to copy them.
    - I considered checking these in as symlinks, but those still don't work so
      well on some systems.
- Change Cabal `license` field to `Apache-2.0`.
- Remove Cabal `copyright` field.
    - There is a copyright notice in `NOTICE` which this would conflict
      with.

### CODE REVIEW

**Comment by michaelpj** [comment]
@nathankaiser can you check that this looks right?

**Comment by michaelpj** [comment]
Just waiting for a sign-off from @mchakravarty .

**Comment by mchakravarty** [comment]
@michaelpj Fine by me as long as @nathankaiser is happy with it.

**Comment by nathankaiser** [comment]
ok and green light from my side!

**Pull request merged**
