### PR TITLE
Update stackage snapshot to 12.14

### PR DESCRIPTION
**Pull request by michaelpj**
This gets us to the last major version of GHC, which seems like a good place to be. Also there are a few bits and pieces from some of the newer package versions that I've wanted to use, so that's nice.

I've tested that this evaluates properly, but I haven't built things yet since it needs to rebuild the deps, and I want to let the CI do that for me :)

@disassembler  I think the first commit here might be of particular interest to you - I imagine this will bite anywhere else we're using `stack2nix`, but the fix is straightforward. It manifested as me getting errors because on my host machine's version of `nixos-unstable` they've removed `ghc843`.

### CODE REVIEW

**Comment by michaelpj** [comment]
Okay, I get a conflicting dependency problem with `core-to-plc` that is completely baffling me...

**Comment by michaelpj** [comment]
[conflict.log](https://github.com/input-output-hk/plutus/files/2565869/conflict.log)

**Comment by michaelpj** [comment]
I also can't enter an environment from e.g. `localPackages.language-plutus-core.env`, it fails with
```
...
ghc-pkg: 5: Parse of field 'license' failed.
builder for '/nix/store/fm902lggmi83w9nh1vb9vkd0ayplh4fm-ghc-8.2.2-with-packages.drv' failed with exit code 1 
```
which is super weird.

**Comment by michaelpj** [comment]
Works like a charm now! Thanks!

**Comment by vmchale** [comment]
What is being used upstream by Cardano? I was under the impression we wanted to use the same stackage snapshot as them.

**Comment by michaelpj** [comment]
`cardano-chain` (which is now the relevant one for us) is on a 12 series snapshot, that's what prompted this.

**Comment by michaelpj** [comment]
Should have put that in the PR description, sorry. I've been trying to do this for a couple of weeks so I almost forgot the original reason :p

**Pull request merged**
