### PR TITLE
[Builtins] Replace a match on 'Refl' with a call to 'unsafeCoerce'

### PR DESCRIPTION
**Pull request by effectfully**
Just being curious how much that redundant match on `Refl` costs us.

### CODE REVIEW

**Comment by effectfully** [comment]
???

**Comment by effectfully** [comment]
A mystery.

**Comment by michaelpj** [comment]
I think `unsafeCoerce` probably inhibits a bunch of optimization, which might explain why this is worse.

**Comment by effectfully** [comment]
It's `unsafeCoerce` around a single variable and it doesn't end up in the Core from what I can tell, so I've no idea what's going on here. In any case, the match on `Refl` is gone in #4380.

**Pull request closed without merging**
