### PR TITLE
GitHub action to add "status: needs triage" label to new issues

### PR DESCRIPTION
**Pull request by kwxm**
This does what it says.  The YAML code is based on the example [here](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues).

### CODE REVIEW

**Comment by kwxm** [comment]
I'll have to merge this without review in order to test it.

**Comment by kwxm** [comment]
I tested this in https://github.com/input-output-hk/plutus/issues/5044 and it appeared to work.  A quick retrospective review might be worthwhile though.

**Comment by michaelpj** [comment]
The main alternative that I'm aware of is that you can add labels to issue templates so that they are created with those labels. The advantage is that you don't need an action, but the disadvantage is that if someone clicks "open a blank issue" it won't work.

**Review by thealmarty — COMMENTED** [review]
Thanks!

**Pull request merged**
