### PR TITLE
Add new config for environment Pablo

### PR DESCRIPTION
**Pull request by palas**

### CODE REVIEW

**Comment by michaelpj** [comment]
Just noticed the existence of `secrets`: should we stick this under `deployment`, since it's only related to our deployment environments?

**Comment by palas** [comment]
> Just noticed the existence of `secrets`: should we stick this under `deployment`, since it's only related to our deployment environments?

I imagine it will break something if I just move it, but I cannot find a single use of the word "secrets" outside of the `secrets` folder. @shmish111 what do you think?

**Comment by shmish111** [comment]
we can move it and just change https://github.com/input-output-hk/plutus/blob/master/shell.nix#L54 if you prefer. I meant that it could be used for other secrets in the future, if any ever exist.

**Comment by michaelpj** [comment]
I guess I am getting a mild preference for avoilding more top-level directories as we have a lot now, but absolutely not a big deal.

**Pull request merged**
