### PR TITLE
Kwxm/promote new specification 2

### PR DESCRIPTION
**Pull request by kwxm**
Another attempt at promoting the new version of the specification to be the main one and adding its source files.

### CODE REVIEW

**Comment by kwxm** [comment]
I maybe still need to tell nix about new latex packages ...

**Comment by michaelpj** [comment]
It's kind of weird, it's complaining about not recognizing the control sequence `\section`, I think, which is very odd... Lovely latex errors.

**Comment by kwxm** [comment]
> It's kind of weird, it's complaining about not recognizing the control sequence `\section`, I think, which is very odd... Lovely latex errors.

I can reproduce this if it type (in a standard shell) `latexmk` or `latexmk builtins-alonzo.tex` in `plutus-core-spec`.  If instead I type `latexmk plutus-core-specfication.tex` then it builds a `.dvi` file (without the index of notation at the end: `latexmk` maybe doesn't know that it needs to run `makeindex` to build that).  I think that nix is just trying to build the first tex file it sees and that doesn't contain a `\documentclass`, so it's failing.  Presumably nix needs to be told _what_ to build, but I can't see how to do that at the moment.

**Comment by kwxm** [comment]
OK, I found out how to make `latexmk` build the index of notation properly: see https://tex.stackexchange.com/questions/105943/latexmk-and-nomencl

**Comment by kwxm** [comment]
Success!

**Comment by michaelpj** [comment]
Well done!

**Review by michaelpj — APPROVED** [review]

**Pull request merged**
