### PR TITLE
nix: Docker image for development

### PR DESCRIPTION
**Pull request by j-mueller**
* A docker image that can be used to build the example in `example/`

Output:
```
jann@iohk-dev-vm:~/plutus-example$ sudo docker run -w /app -v "$(pwd)":/app -v ~/tmp:/tmp --name dev plutus-development:iwhhac55vfnwgqff1v29scc6g2gdw2dw cabal new-build .
Config file path source is default config file.
Config file //.cabal/config not found.
Writing default configuration to //.cabal/config
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
 - example-0.1.0.0 (lib) (first run)
 - example-0.1.0.0 (exe:example-exe) (first run)
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
Configuring executable 'example-exe' for example-0.1.0.0..
Preprocessing executable 'example-exe' for example-0.1.0.0..
Building executable 'example-exe' for example-0.1.0.0..
[1 of 1] Compiling Main             ( app/Main.hs, /app/dist-newstyle/build/x86_64-linux/ghc-8.6.4/example-0.1.0.0/x/example-exe/build/example-exe/example-exe-tmp/Main.o )
Linking /app/dist-newstyle/build/x86_64-linux/ghc-8.6.4/example-0.1.0.0/x/example-exe/build/example-exe/example-exe ...
```

### CODE REVIEW

**Comment by j-mueller** [comment]
After that I'm going to figure out how to use this image in VSCode

**Comment by shmish111** [comment]
Nice, when you manage to get it working with VSCode you can probably include more in the `CMD` so that the user has to do less to run it? What about haskell ide engine, this should run inside it I should think?

**Comment by j-mueller** [comment]
Yeah I'll add the haskell package for HIE engine.

After connecting to the container for the first time, VSCode actually installs something called VSCode Server in the container, and this VSCode Server then installs plugins such as the hie-engine plugin. So I imagine the way to use this is image is to start the container in the background, then [connect to it from VSCode](https://code.visualstudio.com/docs/remote/containers#_attaching-to-running-containers). I haven't found VSCode Server on nix though, so I'm not sure that we can automate this part.

**Comment by shmish111** [comment]
ah nice, yeah sorry I forgot this was what you were doing

**Pull request merged**
