### PR TITLE
Kwxm/core spec/remove sizes

### PR DESCRIPTION
**Pull request by kwxm**
This removes sizes from the spec and fixes some persistent annoyances wrt file names and things.

### CODE REVIEW

**Comment by kwxm** [comment]
The specification contains some builtins which aren't implemented: at least `quotInteger`, `modInteger`, and `intToByteString`.  I think the first two of these are supposed to correspond to Haskell's `quot` and `mod` operations, and I think they were added to the spec after some discussion during a Plutus call.  Annoyingly, it transpires that `quot` and `rem` don't implement the correct mathematical definition, and neither do `div` and `rem`. We should work out what we want to do here.

Also, is there a reason why we have `intToByteString` but not `byteStringToInt`?

**Comment by michaelpj** [comment]
`quot`, `rem` and`mod` are implemented as the Haskell versions, which might be wrong. `intToByteString` isn't, but I don't really know why it's there and nobody's ever wanted it.

**Comment by michaelpj** [comment]
Residual references in:
2.1 types
3 typing rules
4.1 type frames
Appendix A typing rules
Appendix B typing rules

Builtin signatures look weird, I guess because they don't have any type arguments now.
Arguments to verifySignature are missing.

**Comment by michaelpj** [comment]
Otherwise looks fine.

**Comment by kwxm** [comment]
> `quot`, `rem` and`mod` are implemented as the Haskell versions, which might be wrong. `intToByteString` isn't, but I don't really know why it's there and nobody's ever wanted it.

I'll take out `intToByteString` then.

**Comment by kwxm** [comment]
> Residual references in:
> 2.1 types
> 3 typing rules
> 4.1 type frames
> Appendix A typing rules
> Appendix B typing rules
> 
> Builtin signatures look weird, I guess because they don't have any type arguments now.
> Arguments to verifySignature are missing.

Fixed.

**Pull request merged**
