### PR TITLE
Cabal and Stack gardening part II

### PR DESCRIPTION
**Pull request by michaelpj**
Commits should make sense (but need squashing before merging). This fixes some oversights from the previous gardening, and gets rid of almost all of the flags and constraints that we set.

The other big change was bumping the Stackage snapshot, but this mostly just simplifies our lives a lot and lets us delete a bunch of `extra-packages`.

I'd appreciate it if a Stack user could check that this still actually works for them! I have checked that stack doesn't give solver errors, but not that it actually builds everything.

Also @shmish111 I moved away from our `servant-purescript` fork since upstream seems to work now.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by shmish111 — COMMENTED** [review]
LGTM but I can't approve until we are sure about purescript-servant

**Comment by michaelpj** [comment]
Hooray, it's green. Waiting on your OK, David.

**Comment by shmish111** [comment]
I am unable to build `cabal new-build marlowe-dashboard-server` or `stack build marlowe-dashboard-server`
```
➜  plutus git:(imp/servant-constraints) stack build plutus-ledger-api
plutus-ledger-api> configure (lib)
Configuring plutus-ledger-api-0.1.0.0...
plutus-ledger-api> build (lib)
Preprocessing library for plutus-ledger-api-0.1.0.0..
Building library for plutus-ledger-api-0.1.0.0..
[ 1 of 16] Compiling Data.Aeson.Extras

/Users/davidsmith/tweag/plutus/plutus-ledger-api/src/Data/Aeson/Extras.hs:27:13: error:
    • Couldn't match type ‘(BSS.ByteString, BSS.ByteString)’
                     with ‘Either String BSS.ByteString’
      Expected type: Text.Text -> Either String BSS.ByteString
        Actual type: Text.Text -> (BSS.ByteString, BSS.ByteString)
    • In the expression: Base16.decode . TE.encodeUtf8
      In an equation for ‘tryDecode’:
          tryDecode = Base16.decode . TE.encodeUtf8
   |
27 | tryDecode = Base16.decode . TE.encodeUtf8
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

<no location info>: warning: [-Wunused-packages]
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - template-haskell-2.16.0.0
      - prettyprinter-1.7.0
      - plutus-tx-0.1.0.0
      - plutus-core-0.1.0.0
      - newtype-generics-0.5.4
      - mtl-2.2.2
      - memory-0.15.0
      - lens-4.19.2
      - flat-0.4.4
      - deepseq-1.4.4.0
      - cryptonite-0.27
      - cardano-crypto-1.1.0


--  While building package plutus-ledger-api-0.1.0.0 (scroll up to its section to see the error) using:
      /Users/davidsmith/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:plutus-ledger-api --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```
```
➜  plutus git:(imp/servant-constraints) cabal new-build plutus-ledger-api
Warning: Requested index-state2021-02-01T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-01-31T23:42:25Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class
```

I can build with nix and am currently deploying to check that the servant stuff works ok

**Comment by michaelpj** [comment]
Hmm, weird. Is that in a nix-shell? The pkg-config issue seems like it's some weird system thing...

**Comment by shmish111** [comment]
this was with lorri, just trying a nix-shell now.

**Comment by michaelpj** [comment]
Sounds like we should put a bound on the bytestring-base16 package anyway for the first one.

**Comment by michaelpj** [comment]
I pushed a bound for the base16-bytestring package, and it needs an `extra-dep` since the version in the stackage snapshot is old.

**Comment by shmish111** [comment]
ok, cabal worked in nix-shell, trying stack after your push now. TIL: don't rely on lorri if something seems to be broken

**Comment by michaelpj** [comment]
Yeah, it's super annoying that there's no obvious way to tell if your lorri shell is stale, or if lorri is failing or something.

**Comment by michaelpj** [comment]
I wish it updated direnv with a `LORRI_STATUS` variable unconditionally, so e.g. it was set to something you could show in your PS1 if it failed.

**Comment by shmish111** [comment]
so I think lorri wasn't working because it had failed to build the nix shell a while ago and that had got it stuck somehow. cabal and stack  now building. I'm still trying to deploy to test the playground stuff but unfortunately my internet connection is _extremely_ asymmetric and it's taking a while to upload everything since I haven't deployed for a while.

**Comment by michaelpj** [comment]
:pray:

**Comment by raduom** [comment]
🙏

**Comment by shmish111** [comment]
restarting lorri fixed things. Almost done uploading `[8/427/788 copied (2677.2/4721.1 MiB)]` but going for lunch

**Review by shmish111 — APPROVED** [review]
ok deployed and tested, all good

**Comment by michaelpj** [comment]
Glory be

**Pull request merged**
