### PR TITLE
Plutus core/cgp 373

### PR DESCRIPTION
**Pull request by vmchale**
This fixes the `Eq` instance for `Term`s. It uses the same approach as the `Eq` instance for `Type`s, though it is slightly subtler since `Term`s can bind `Type`s and so we need to use `eqTypeSt` explicitly in `eqTermSt`.

### CODE REVIEW

**Comment by effectfully** [comment]
Although, I'd really prefer to have this in a separate file even though this means the `Eq` instances will be orphan. For a core module this is just mess.

**Comment by effectfully** [comment]
I see that you added and removed the `runQuote (rename t) == t` test. It doesn't pass? Could you explain what is wrong with the idea?

**Comment by effectfully** [comment]
> Well, it's not totally obvious that a non-renamed term and a renamed term are the same, without separating the names that are used multiple times... which is renaming.

Sorry, do you have an example? The approach Vanessa uses here avoids name capture and tracks scopes. We have tests for type equality like

```
(all x (type) (fun (all y (type) y) x)) ==
(all x (type) (fun (all x (type) x) x))
```

and

```
(all y (type) (all z (type) (fun y z))) ==
(all x (type) (all y (type) (fun x y)))
```

Since renaming doesn't change the meaning of a term, I'd expect `runQuote (rename t) == t` to hold, but maybe I'm just missing something.

In any case `runQuote (alphaRename t) == t` has to hold, because that what we need this equality for in the first place.

**Comment by michaelpj** [comment]
Okay, I've misunderstood then. It would be great if that test did work!

**Comment by vmchale** [comment]
@effectfully the approach we take to equality doesn't work when there are free variables. I think we can write a generator to filter out such free variables and then your approach is a good one.

The other approach would be to write golden tests, which is less appealing in my opinion, but also less work.

**Comment by michaelpj** [comment]
> the approach we take to equality doesn't work when there are free variables. 

It would be very nice if it did! I would like to compare terms with free variables for equality if I can.

**Comment by effectfully** [comment]
> the approach we take to equality doesn't work when there are free variables.

Wait, why?

> The other approach would be to write golden tests, which is less appealing in my opinion, but also less work.

Having golden tests is nice too, but we do want good property tests.

**Comment by vmchale** [comment]
I misspoke. The approach to renaming is I believe what causes failures with free variables.

**Comment by effectfully** [comment]
The renamer is not supposed to touch free variables at all. Have you spotted a bug somewhere?

**Comment by effectfully** [comment]
Could you please post a failing test?

**Comment by vmchale** [comment]
Sure. Suppose we have a file called `eq.plc` containing

```
(program 0.1.0
  (abs a (type) a)
)
```

Then we can run `cabal new-repl`

```
λ:> import qualified Data.ByteString.Lazy as BSL
λ:> file0 = fmap (prettyPlcClassicDebug . runQuote . rename . either undefined id . (parseScoped :: BSL.ByteString -> Either (Error AlexPosn) (Program TyName Name AlexPosn))) $ BSL.readFile "eq.plc"
λ:> file1 = fmap (prettyPlcClassicDebug . either undefined id . (parseScoped :: BSL.ByteString -> Either (Error AlexPosn) (Program TyName Name AlexPosn))) $ BSL.readFile "eq.plc"
λ:> file0
(program 0.1.0
  (abs a_0 (type) a_0)
)
λ:> file1
(program 0.1.0
  (abs a_1 (type) a_1)
)
```

As we can see, the free variable `a` was renamed from `a_1` to `a_0`. 

This example is all a bit convoluted but basically it works because the renamer seems to treat the second `a` as a bound variable, even though it is not, as it is a term.

**Comment by michaelpj** [comment]
Um, isn't `a` bound there by the `abs`?

**Comment by michaelpj** [comment]
Argh ignore me I can't read.

**Comment by effectfully** [comment]
Well yes, this is a bug and a severe one.

@vmchale, thank you for finding and showcasing the bug, I'll look into what has to be done to fix it. And also look whether the cloning machinery is affected, cause this part:

```haskell
        TyAbs a tn k ty     -> do
            addBound (tn ^. unique)
            tn' <- clone what tn
            TyAbs a tn' k <$> clone what ty
        LamAbs a n ty t     -> do
            addBound (n ^. unique)
            LamAbs a <$> clone what n <*> clone what ty <*> clone what t
```

looks like we have the same problem with cloning as well.

**Comment by michaelpj** [comment]
:+1: Thanks for looking into this. If only we shared the same code between the two... ;)

**Comment by vmchale** [comment]
Yes, the same problem appears in the new cloning machinery. I think that can be fixed by simply reverting https://github.com/input-output-hk/plutus/pull/200, and no longer exporting a function named `alphaRename` (it is not used directly anywhere; I will have to check it is not used indirectly either). 

I've set up a youtrac bug for the renamer and assigned myself for the time being.

**Comment by effectfully** [comment]
> Yes, the same problem appears in the new cloning machinery. I think that can be fixed by simply reverting #200, and no longer exporting a function named alphaRename (it is not used directly anywhere; I will have to check it is not used indirectly either).

Well, having a bug doesn't mean we should throw away a very well-written code. We just need to fix the bug.

**Comment by effectfully** [comment]
What's with this one? The bug is in the renamer and what's here should be fine. Do we have at least some tests similar to what we have with type equality? If yes, then let's merge.

**Pull request merged**
