### PR TITLE
Adding ghcid to our local dev toolset.

### PR DESCRIPTION
**Pull request by krisajenkins**

### CODE REVIEW

**Comment by reactormonk** [comment]
```
Error: Multiple files use the same module name:
       * PSGenerator found at the following paths
         * /home/tass/dev/iohk/plutus/marlowe-playground-server/app/PSGenerator.hs (marlowe-playground-server:exe:marlowe-playground-server)
         * /home/tass/dev/iohk/plutus/plutus-playground-server/app/PSGenerator.hs (plutus-playground-server:exe:plutus-playground-server)
       * Types found at the following paths
         * /home/tass/dev/iohk/plutus/marlowe-playground-server/app/Types.hs (marlowe-playground-server:exe:marlowe-playground-server)
         * /home/tass/dev/iohk/plutus/plutus-playground-server/app/Types.hs (plutus-playground-server:exe:plutus-playground-server)
       * Webserver found at the following paths
         * /home/tass/dev/iohk/plutus/marlowe-playground-server/app/Webserver.hs (marlowe-playground-server:exe:marlowe-playground-server)
         * /home/tass/dev/iohk/plutus/plutus-playground-server/app/Webserver.hs (plutus-playground-server:exe:plutus-playground-server)
* * * * * * * *
```

**Comment by michaelpj** [comment]
That seems unrelated?

**Comment by reactormonk** [comment]
That's the error message you get when running `ghcid` on toplevel. Apparently not how you're supposed to use it.

**Comment by michaelpj** [comment]
I have no idea how you use it, but I guess Kris knows!

**Pull request merged**
