### PR TITLE
Test Marlowe benchmarks in CI

### PR DESCRIPTION
**Pull request by kwxm**
Just checking whether the new Marlowe benchmarks work in CI.

### CODE REVIEW

**Comment by michaelpj** [comment]
I mean, those benchmark names are kind of terrible. Maybe we can do something about that @thealmarty ? Even just numbering them `role1` etc. would help

**Comment by thealmarty** [comment]
> I mean, those benchmark names are kind of terrible. Maybe we can do something about that @thealmarty ? Even just numbering them `role1` etc. would help

It *should* have the transaction ids like the semantics ones. I'll try fix it.

**Pull request closed without merging**
