### PR TITLE
[Bug] [PIR] [NameHandling] Fixed handling of non-recursive bindings in the PIR renamer

### PR DESCRIPTION
**Pull request by effectfully**
@jakzale this one should fix that bug in the PIR renamer (but no promises that it fixes all of them or doesn't introduce some new ones).

The code is mess, please nobody try to review it.

### CODE REVIEW

**Comment by effectfully** [comment]
@jakzale this now incorporates both of my recent fixes, try it again.

**Comment by jakzale** [comment]
So, I did test both of your fixes, (see 5c732c7b5afcd9b4d8dca71af8c18bcf4a1d0721) by increasing the number of simplifications on plutus-benchmark/nofib/src/Plutus/Benchmark/LastPiece.hs from 1 to 2.

https://github.com/input-output-hk/plutus/blob/5c732c7b5afcd9b4d8dca71af8c18bcf4a1d0721/plutus-benchmark/nofib/src/Plutus/Benchmark/LastPiece.hs#L2

And it still cause an error during typechecking of PLC.

Is this PR different from what is in 5c732c7b5afcd9b4d8dca71af8c18bcf4a1d0721?

**Comment by effectfully** [comment]
Yes, it's different.

**Comment by johnalotoski** [comment]
This pr has been failing eval on hydra since 2021-07-06.  Disabling automatic eval and build with the `hydra-dont-build` label to avoid unnecessary hydra resource consumption.  Please remove this label from the PR when you want hydra to resume eval and builds.

**Comment by jakzale** [comment]
@michaelpj has this been abandoned?

**Comment by effectfully** [comment]
@jakzale it was closed in favor of the already merged #3587.

**Pull request closed without merging**
