### PR TITLE
Plutus core tidy

### PR DESCRIPTION
**Pull request by michaelpj**
PLC core stuff now looks like this:
```
        plutus-core/src 
        plutus-core/stdlib 
        plutus-core/examples 
        plutus-ir/src 
        untyped-plutus-core/src 
        generators 
        prelude 
        common 
```

Also the cost model stuff went into its own subfolder.

I have some more tidying I want to do in the form of deleting some stuff, but I'll do that separately.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by kwxm — APPROVED** [review]
Bold, but a bit tricky to review.  Checking out the branch locally it looks OK (modulo the current test failures) and indeed a lot tidier. having a `src` directory for `untyped-plutus-core` makes things a bit more consistent: I always had trouble finding the typed/untyped versions of things in my editor because the paths were a bit different.

Is there any way to check this out and have git delete the directories that have been moved?  If I check it out, I get 

```
$ ls untyped-plutus-core/
Language/  src/  test/
```
The `Language` directory is left over from the previous state, which is pretty confusing. Presumably there'll be lots of similar cases.

While I'm here, what is `weigh` for?

**Review by effectfully — APPROVED** [review]
And now all links my browser remembers are invalid again.

While we're here, let's also move `generators/Language/PlutusCore` inside `plutus-core` and remove `plutus-core/generate-evaluation-test` (unless we need it for something, in which case that functionality should go into `exe`)? Seconding the question about `weigh`. Also, do we use `bench`? It seems pretty useless.

**Comment by effectfully** [comment]
BTW, I thought we needed that `src` folder for something? HLS or costing or I don't know. @reactormonk should know.

**Comment by kwxm** [comment]
> BTW, I thought we needed that `src` folder for something? HLS or costing or I don't know. @reactormonk should know.

You're right: that's where the cost model currently goes.  In `CreateCostModel.hs` we have
```
BSL.writeFile "plutus-core/src/costModel.json"
```
That json file can go somewhere else, but paths will need to be updated here and in other files.

**Comment by michaelpj** [comment]
Yeah, I killed that in the first commit, I don't think we need it any more. It finds the json file fine, and HLS is happy.

**Comment by michaelpj** [comment]
> plutus-core/generate-evaluation-test

What does this actually do? Do we care? I think you wrote it, Roman - is it useful?

> generators

This has some UPLC stuff in it too, which is why I left it where it is. Not sure what to do with it really.

> bench/weigh

`weigh` is supposed to be memory benchmarking, I think. I'm not sure whether either of these are that useful: and anyway, I think the locus of benchmarking has moved to `plutus-benchmark`. I think we should delete them: maybe Kenneth could have a look and say if any of it seems worth salvaging?

**Comment by effectfully** [comment]
> What does this actually do? Do we care? I think you wrote it, Roman - is it useful?

It generates a program and prints what that program should evaluate to. I wrote it for IELE people back in 2018. Dunno if it's useful for us right now.

**Comment by kwxm** [comment]
`weigh` does seem to be memory benchmarking, using [this](https://www.fpcomplete.com/haskell/library/weigh/).  All that the stuff in `weigh` is doing is applying that to two signature verification examples, one which succeeds and one which fails, but if fact it doesn't work because it's trying to read golden files which have disappeared.

 I think we can safely delete this and start from scratch if we want to look at memory usage some time.

**Comment by michaelpj** [comment]
I killed `bench`, `weigh` and `generate-evaluation-test`.

**Comment by kwxm** [comment]
`plutus-core:plutus-core-bench` is benchmarking things like parsing, typechecking, checking term equality and so on, together with evaluation times for a few small programs.  It's kind of interesting to know how long the internal things take, but nothing in the compilation process is anywhere near slow enough to be causing us problems (and I don't think we need detailed benchmarking times for those kinds of thing anyway).  Evaluation times are what we really care about, and they're well coveredd by `plutus-benchmark`.  I'm always reluctant to throw things out, but I think we could probably dispense with these particualr benchmarks.

**Comment by michaelpj** [comment]
Okay, let's do this before it bitrots further.

**Pull request merged**
