### PR TITLE
[Builtins] Drop 'val' from 'KnownType' stuff

### PR DESCRIPTION
**Pull request by effectfully**
Let's see if it's better this time around.

### CODE REVIEW

**Comment by effectfully** [comment]
Em?

**Comment by effectfully** [comment]
Eh.

**Comment by michaelpj** [comment]
Sad times.

**Comment by effectfully** [comment]
I have a bigger hammer, so let's see.

**Comment by effectfully** [comment]
Core looks promising for `readKnown` now (I haven't updated `makeKnown` yet, let's see how `readKnown` goes first).

**Comment by michaelpj** [comment]
Okay, I find it kind of offensive that even after making it a single-method typeclass, passing in just the function is better :(

**Comment by effectfully** [comment]
Here's a phrase you might want to use: "dad, we need to talk".

On a serious note though, it does kinda make sense. The inlined version has all the constraints explicitly discharged while the non-inlined one doesn't (the class methods have those constraints). For a different use case the constraints can be needed, it's just that we don't need to instantiate them in multiple ways and can hardcode a single instantiation into the constructors.

**Comment by effectfully** [comment]
-1.07% on average, maybe noise, maybe not.

@michaelpj should I finish this one off? I don't like that what's in here does not allow us to remove `val` from `TypeScheme` (it only needs to be in `RuntimeScheme`), however what I'm going to do in order to make deferred unlifting faster should solve the `val`-in-`TypeScheme` problem too. I'm not sure about the order of the PRs, though. I can work on deferred unlifting first or I can finish this one first, if you find what's in here reasonable.

**Comment by michaelpj** [comment]
> I can work on deferred unlifting first 

Yes, that's higher priority.

I also wonder if we should try inlining read/makeKnown into `TypeScheme` independently. That seems to have got us most of the speedup here, so I wonder if this PR is now a combination of an improvement and a regression, so the improvement masks the regression... perhaps better to just do the improvement independently.

**Comment by effectfully** [comment]
+0.9%. Sucks, I guess. Still gonna see if I can remove `val` from `TypeScheme` and `ToBuiltinMeaning`.

**Comment by effectfully** [comment]
Wait, I merged `master` in instead of rebasing :facepalm:

**Comment by effectfully** [comment]
I.e. it's probably even worse.

**Comment by effectfully** [comment]
Closing in favor of #4533.

**Pull request closed without merging**
