### PR TITLE
run tests with `plc-agda` in CI

### PR DESCRIPTION
**Pull request by jmchapman**

### CODE REVIEW

**Comment by jmchapman** [comment]
I am surprised that didn't put `plc` and `plc-agda` in the path. It works with `cabal v2-test`.

**Comment by jmchapman** [comment]
thanks @michaelpj! 

> but for now would it work to just import the plc-agda functionality and call it from Haskell rather than from the shell?

sounds like a plan.

**Comment by michaelpj** [comment]
Hm, the usage of `plc-agda` doesn't seem so bad - perhaps it would be simplest to just do the same thing for `plc-exe` and then we don't have to worry about shelling out at all?

**Comment by jmchapman** [comment]
This first step is working I think. It tests `plc-agda` by evaluating the examples (`plc example -a`) and checking that they evaluate successfully or fail as expected. The next step would be to check that `plc-agda` produces the same output as `plc`. I will do that in a separate pull request.

**Comment by jmchapman** [comment]
@michaelpj I added `metatheory` to `cabal.project` as otherwise the `cabal v2-` commands didn't seem to work. I notice you (I think) added a comment to `plc-agda.cabal`:

```
-- Note that this is *not* in cabal.project, since it requires rather special
-- setup to build.
```

Is this still relevant or can I remove the comment?

**Comment by jmchapman** [comment]
I decided to carry on with this pull request. I added another test suite which runs both `plc` and `plc-agda` on the same examples and checks that they produce identical output.

**Comment by jmchapman** [comment]
hmm, I am not sure why this isn't working. I thought it might not like having two test suites but disabling the first one doesn't seem to help. Does nix not like `detailed` test suites?

**Comment by michaelpj** [comment]
```
diff --git i/metatheory/plc-agda.nix w/metatheory/plc-agda.nix
index bb19b0fb..ee9fbf8c 100644
--- i/metatheory/plc-agda.nix
+++ w/metatheory/plc-agda.nix
@@ -17,6 +17,8 @@ mkDerivation {
     language-plutus-core memory optparse-applicative process text
   ];
   testToolDepends = [ plutus-exe ];
+  enableLibraryProfiling = false;
+  enableExecutableProfiling = false;
   homepage = "https://github.com/input-output-hk/plutus";
   description = "Command line tool for running plutus core programs";
   license = stdenv.lib.licenses.asl20;
```

**Comment by michaelpj** [comment]
(The reason is that we default to profiling off, but nixpkgs defaults to having it on. I'm not sure why this ever worked.)

**Comment by jmchapman** [comment]
Thanks for your help and explaining the cause. I wasn't able to make sense of the error messages.

**Pull request merged**
