### PR TITLE
Bump haskell.nix

### PR DESCRIPTION
**Pull request by andreabedini**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by zeme-iohk** [comment]
No objection to this, but why the bump?

**Comment by zeme-iohk** [comment]
No objection to this, but why the bump?

**Comment by andreabedini** [comment]
> No objection to this, but why the bump?

Marking it as draft doesn't spare me from explaining myself :laughing:

The bump is to support cabal file revisions on CHaP which are necessary to get our packages to build without all those manual constraints we have in cabal.project.

I opened a draft PR to test the waters and warm up the chaces ahead of time since it's relatively big change in haskell.nix. I'll make sure everything works and then mark it as ready.

**Comment by michaelpj** [comment]
`plutus` maybe isn't the most interesting project to try this on since we actually don't have a mess of constraints because we don't depend on that many cardano projects?

**Comment by andreabedini** [comment]
This seems to have gone smoothly so I am marking it as ready.

**Review by zeme-iohk — APPROVED** [review]

**Pull request merged**
