### PR TITLE
Marlowe playground refinements

### PR DESCRIPTION
**Pull request by palas**
Addresses issues #1530, #1531, and #1532, and applies small adjustments to the layout of the simulator.

### CODE REVIEW

**Comment by shmish111** [comment]
LGTM but you'll probably have to fo a `$(nix build -f default.nix dev.scripts.fixPurty)`

**Comment by palas** [comment]
Surprisingly, it seems to have no effect, the code must be all purty already

**Comment by shmish111** [comment]
Hydra couldn't compile your code though! :D

**Comment by palas** [comment]
Oops, the tests :man_facepalming:

**Pull request merged**
