### PR TITLE
Move static analysis into marlowe

### PR DESCRIPTION
**Pull request by nau**
- Move static analysis into marlowe
- Remove marlowe-hspec
- Move marlowe-tutorial into marlowe

### CODE REVIEW

**Comment by palas** [comment]
I think it would be good to have this reviewed by @shmish111 too, because my knowledge of nix is very limited

**Comment by michaelpj** [comment]
Any reason not to move the rest of `marlowe-symbolic` in as well? I guess that's just the lambda, but it could just be another executable component of `marlowe`?

**Comment by nau** [comment]
Yes, working on that.

**Comment by nau** [comment]
> Any reason not to move the rest of `marlowe-symbolic` in as well? I guess that's just the lambda, but it could just be another executable component of `marlowe`?

From lambda.nix:

> Because AWS Lambda uses an older version of glibc than nixpkgs, we need to build fully static
> binaries.
> 
> Unfortunately we cannot build a haskell static binary if the package uses template haskell.
> This is because haskell uses dynamically linked libraries to run template haskell at compile
> time, however we have passed the `-optl=-static` flag which is passed to all linker invocations
> causing these intermediate dynamically linked libraries to fail linking.
> 
> In order to get around this we make sure that the TH code is all in libraries and create a single haskell file that does nothing other than import the main function from the library.

Apparently, in this case HTTP service would be included into Marlowe library, which doesn't sound right to me. I guess we can live with marlowe-symbolic project on top level.

**Comment by michaelpj** [comment]
> In order to get around this we make sure that the TH code is all in libraries and create a single haskell file that does nothing other than import the main function from the library.

That's done in the nix itself, though, I don't think we need a separate package for that (David can correct me if I'm wrong there).

> Apparently, in this case HTTP service would be included into Marlowe library, which doesn't sound right to me.

Sure, but in a different component. You won't need it to build the main library, or anything that just depends on that. Seems fine to me, no weirder than depending on cli libraries for your cli executable component, or test libraries for your testsuite.

**Comment by nau** [comment]
> Sure, but in a different component. You won't need it to build the main library, or anything that just depends on that. Seems fine to me, no weirder than depending on cli libraries for your cli executable component, or test libraries for your testsuite.
What do you mean by different component? It should be a library to use TH for AWS lambda code generation, and afair we can't define multiple libraries in a cabal project.

**Comment by michaelpj** [comment]
Ah I see, we need to expose it as a library so the special static executable can link against it. Got it.

I do think we should be able to do something nicer with `haskell.nix`, but I'll leave that to David.

**Pull request merged**
