### PR TITLE
Hide hoist from Data.Functor.Foldable

### PR DESCRIPTION
**Pull request by vmchale**
Otherwise, compilation breaks as of `recursion-schemes` 5.1. 

Ideally, we'd just use `cata` in place of `hoist` but this is quicker.

### CODE REVIEW

**Comment by michaelpj** [comment]
The `hoist` from the new `Data.Functor.Foldable` is the same as our one, of course. But we can't really handle that gracefully across multiple versions without CPP, so seems okay.

**Comment by effectfully** [comment]
I think it's fine to have CPP in a dedicated compatibility module.

**Comment by vmchale** [comment]
We could also simply have `recursion-schemes < 5.1` in the cabal file if we wish to avoid CPP

**Comment by michaelpj** [comment]
That'll work until we update to a 13 series Stackage snapshot.

I think an explicit import list is the easiest thing to do - no CPP, and we know it will keep working.

**Pull request merged**
