### PR TITLE
PLT-1607: Propagate INLINE pragmas to PIR

### PR DESCRIPTION
**Pull request by michaelpj**
This is easy to do, and gives the user a bit more control over inlining.

As a bonus, it looks like GHC adds inline pragmas to some things like `DFun`s (dictionary selectors), which is also to our advantage.

### CODE REVIEW

**Comment by zliu41** [comment]
Looks good! Please rebase and see if it makes a difference on `anyCheap` etc.

**Comment by michaelpj** [comment]
No change to `anyCheap`, but I don't think we were expecting anything?

**Comment by zliu41** [comment]
> No change to anyCheap, but I don't think we were expecting anything?

Currently there's only `INLINALBE` pragma on `foldr` and `any`. It may make a difference if you change them to `INLINE`, but I'm fine if you don't want to do it in this PR.

**Comment by michaelpj** [comment]
> It may make a difference if you change them to INLINE, but I'm fine if you don't want to do it in this PR.

Yeah, I'll leave it for now.

**Pull request merged**
