### PR TITLE
Add an empty ci.nix to shut up hercules for now

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by reactormonk** [comment]
Looked good, but apparently it isn't - https://hercules-ci.com/github/input-output-hk/plutus/jobs/77

**Comment by michaelpj** [comment]
Hm, it seems to have stopped it posting to the PR, though :sweat_smile:

**Comment by michaelpj** [comment]
Hm indeed, seems to have only been this PR. I guess I'll try again with a trivial attribute.

**Comment by reactormonk** [comment]
I unticked "Build this repository" in https://hercules-ci.com/github/input-output-hk/plutus - seem to work as expected.

**Pull request merged**
