### PR TITLE
[Evaluation] Made the 'VCon' constructor strict in the CEK machine

### PR DESCRIPTION
**Pull request by effectfully**
My latest investigations. Mostly negative results, but one is positive. I double- and triple-checked, but I encourage somebody to recheck themselves.

### CODE REVIEW

**Review by michaelpj — APPROVED** [review]
I think I tried this before and it seemed marginal, but it seems like people see either nothing or a speedup, so I think it can't hurt at least.

**Comment by effectfully** [comment]
I've tried it in the past and it gave me a 1% speed-up back then.

**Comment by kwxm** [comment]
I tried this in my branch with the extra validation tests on the benchmarking machine and got a slowdown (just modifying VCon myself):
```
crowdfunding/crowdfunding-success-1      702.3 μs	 707.1 μs       +0.7%
crowdfunding/crowdfunding-success-2      701.0 μs	 707.3 μs       +0.9%
crowdfunding/crowdfunding-success-3      702.7 μs	 706.9 μs       +0.6%
currency/currency-1                      634.2 μs	 636.3 μs       +0.3%
currency/currency-2                      818.5 μs	 822.3 μs       +0.5%
escrow/escrow-redeem_1-1                 976.2 μs	 981.8 μs       +0.6%
escrow/escrow-redeem_1-2                 977.5 μs	 984.2 μs       +0.7%
escrow/escrow-redeem_2-1                 1.125 ms	 1.131 ms       +0.5%
escrow/escrow-redeem_2-2                 1.121 ms	 1.129 ms       +0.7%
escrow/escrow-redeem_2-3                 1.117 ms	 1.128 ms       +1.0%
escrow/escrow-refund-1                   486.4 μs	 489.5 μs       +0.6%
future/future-increase-margin-1          632.0 μs	 639.2 μs       +1.1%
future/future-increase-margin-2          817.5 μs	 825.9 μs       +1.0%
future/future-increase-margin-3          1.421 ms	 1.436 ms       +1.1%
future/future-increase-margin-4          1.422 ms	 1.434 ms       +0.8%
future/future-increase-margin-5          1.318 ms	 1.328 ms       +0.8%
future/future-increase-margin-6          1.947 ms	 1.956 ms       +0.5%
future/future-pay-out-1                  632.6 μs	 637.4 μs       +0.8%
future/future-pay-out-2                  815.5 μs	 823.4 μs       +1.0%
future/future-pay-out-3                  1.417 ms	 1.429 ms       +0.8%
future/future-pay-out-4                  1.418 ms	 1.428 ms       +0.7%
future/future-pay-out-5                  1.822 ms	 1.835 ms       +0.7%
future/future-settle-early-1             631.1 μs	 636.4 μs       +0.8%
future/future-settle-early-2             814.7 μs	 822.7 μs       +1.0%
future/future-settle-early-3             1.414 ms	 1.423 ms       +0.6%
future/future-settle-early-4             1.426 ms	 1.426 ms        0.0%
future/future-settle-early-5             1.452 ms	 1.461 ms       +0.6%
game-sm/game-sm-success-1                1.009 ms	 1.018 ms       +0.9%
game-sm/game-sm-success-2                544.7 μs	 550.7 μs       +1.1%
game-sm/game-sm-success-3                1.461 ms	 1.472 ms       +0.8%
game-sm/game-sm-success-4                757.3 μs	 762.2 μs       +0.6%
game-sm/game-sm-success_2-1              1.013 ms	 1.022 ms       +0.9%
game-sm/game-sm-success_2-2              543.3 μs	 548.2 μs       +0.9%
game-sm/game-sm-success_2-3              1.454 ms	 1.467 ms       +0.9%
game-sm/game-sm-success_2-4              758.4 μs	 764.2 μs       +0.8%
game-sm/game-sm-success_2-5              1.479 ms	 1.491 ms       +0.8%
game-sm/game-sm-success_2-6              757.5 μs	 761.9 μs       +0.6%
multisig-sm/multisig-sm-01               1.069 ms	 1.078 ms       +0.8%
multisig-sm/multisig-sm-02               1.077 ms	 1.086 ms       +0.8%
multisig-sm/multisig-sm-03               1.096 ms	 1.106 ms       +0.9%
multisig-sm/multisig-sm-04               1.108 ms	 1.125 ms       +1.5%
multisig-sm/multisig-sm-05               1.309 ms	 1.323 ms       +1.1%
multisig-sm/multisig-sm-06               1.166 ms	 1.181 ms       +1.3%
multisig-sm/multisig-sm-07               1.081 ms	 1.090 ms       +0.8%
multisig-sm/multisig-sm-08               1.102 ms	 1.113 ms       +1.0%
multisig-sm/multisig-sm-09               1.116 ms	 1.125 ms       +0.8%
multisig-sm/multisig-sm-10               1.312 ms	 1.322 ms       +0.8%
ping-pong/ping-pong-1                    839.1 μs	 845.1 μs       +0.7%
ping-pong/ping-pong-2                    838.8 μs	 844.7 μs       +0.7%
ping-pong/ping-pong_2-1                  533.0 μs	 536.6 μs       +0.7%
prism/prism-1                            503.7 μs	 505.5 μs       +0.4%
prism/prism-2                            1.108 ms	 1.111 ms       +0.3%
prism/prism-3                            995.1 μs	 1.002 ms       +0.7%
pubkey/pubkey-1                          443.2 μs	 445.3 μs       +0.5%
stablecoin/stablecoin_1-1                2.119 ms	 2.111 ms       -0.4%
stablecoin/stablecoin_1-2                638.5 μs	 640.9 μs       +0.4%
stablecoin/stablecoin_1-3                2.387 ms	 2.383 ms       -0.2%
stablecoin/stablecoin_1-4                691.1 μs	 699.9 μs       +1.3%
stablecoin/stablecoin_1-5                2.901 ms	 2.917 ms       +0.6%
stablecoin/stablecoin_1-6                728.0 μs	 737.4 μs       +1.3%
stablecoin/stablecoin_2-1                2.111 ms	 2.131 ms       +0.9%
stablecoin/stablecoin_2-2                637.3 μs	 644.9 μs       +1.2%
stablecoin/stablecoin_2-3                2.383 ms	 2.396 ms       +0.5%
stablecoin/stablecoin_2-4                690.0 μs	 699.5 μs       +1.4%
token-account/token-account-1            599.8 μs	 603.1 μs       +0.6%
token-account/token-account-2            702.7 μs	 708.3 μs       +0.8%
token-account/token-account-3            897.9 μs	 901.6 μs       +0.4%
vesting/vesting-1                        911.2 μs	 914.6 μs       +0.4%
marlowe/trustfund/trustfund-1            2.132 ms	 2.137 ms       +0.2%
marlowe/trustfund/trustfund-2            1.524 ms	 1.527 ms       +0.2%
marlowe/zerocoupon/zerocoupon-1          2.209 ms	 2.211 ms       +0.1%
marlowe/zerocoupon/zerocoupon-2          1.324 ms	 1.325 ms       +0.1%
```
I also tried it on the old benchmarks in `master` to see if I'd changed something else that affected the timings.
```
crowdfunding/1                           727.9 μs	 738.9 μs       +1.5%
crowdfunding/2                           730.1 μs	 740.0 μs       +1.4%
crowdfunding/3                           735.3 μs	 738.3 μs       +0.4%
crowdfunding/4                           257.3 μs	 259.7 μs       +0.9%
crowdfunding/5                           256.0 μs	 257.4 μs       +0.5%
future/1                                 354.3 μs	 357.4 μs       +0.9%
future/2                                 877.1 μs	 884.3 μs       +0.8%
future/3                                 876.7 μs	 882.4 μs       +0.7%
future/4                                 1.108 ms	 1.118 ms       +0.9%
future/5                                 1.376 ms	 1.385 ms       +0.7%
future/6                                 1.115 ms	 1.123 ms       +0.7%
future/7                                 1.374 ms	 1.382 ms       +0.6%
multisigSM/1                             731.3 μs	 736.0 μs       +0.6%
multisigSM/2                             730.9 μs	 733.8 μs       +0.4%
multisigSM/3                             749.4 μs	 759.1 μs       +1.3%
multisigSM/4                             767.6 μs	 777.0 μs       +1.2%
multisigSM/5                             937.6 μs	 945.8 μs       +0.9%
multisigSM/6                             734.1 μs	 739.7 μs       +0.8%
multisigSM/7                             734.8 μs	 737.0 μs       +0.3%
multisigSM/8                             756.4 μs	 757.5 μs       +0.1%
multisigSM/9                             774.3 μs	 773.9 μs       -0.1%
multisigSM/10                            934.0 μs	 939.0 μs       +0.5%
vesting/1                                710.7 μs	 711.9 μs       +0.2%
vesting/2                                589.0 μs	 586.7 μs       -0.4%
vesting/3                                709.7 μs	 708.8 μs       -0.1%
marlowe/trustfund/1                      2.130 ms	 2.140 ms       +0.5%
marlowe/trustfund/2                      1.533 ms	 1.546 ms       +0.8%
marlowe/zerocoupon/1                     2.216 ms	 2.236 ms       +0.9%
marlowe/zerocoupon/2                     1.332 ms	 1.338 ms       +0.5%
```

I ever tried the nofib ones just to make sure:
```
clausify/formula1                        41.36 ms	 41.90 ms       +1.3%
clausify/formula2                        51.43 ms	 52.23 ms       +1.6%
clausify/formula3                        143.0 ms	 144.5 ms       +1.0%
clausify/formula4                        201.9 ms	 204.6 ms       +1.3%
clausify/formula5                        925.1 ms	 934.8 ms       +1.0%
knights/4x4                              119.5 ms	 120.7 ms       +1.0%
knights/6x6                              330.0 ms	 335.9 ms       +1.8%
knights/8x8                              548.2 ms	 559.1 ms       +2.0%
primetest/05digits                       85.47 ms	 86.09 ms       +0.7%
primetest/08digits                       157.2 ms	 157.8 ms       +0.4%
primetest/10digits                       221.9 ms	 221.9 ms        0.0%
primetest/20digits                       439.4 ms	 440.6 ms       +0.3%
primetest/30digits                       635.6 ms	 637.6 ms       +0.3%
primetest/40digits                       849.2 ms	 850.6 ms       +0.2%
primetest/50digits                       839.8 ms	 838.8 ms       -0.1%
queens4x4/bt                             19.63 ms	 19.78 ms       +0.8%
queens4x4/bm                             25.62 ms	 25.81 ms       +0.7%
queens4x4/bjbt1                          24.06 ms	 24.34 ms       +1.2%
queens4x4/bjbt2                          25.70 ms	 26.06 ms       +1.4%
queens4x4/fc                             58.39 ms	 59.73 ms       +2.3%
queens5x5/bt                             265.7 ms	 268.3 ms       +1.0%
queens5x5/bm                             291.8 ms	 294.1 ms       +0.8%
queens5x5/bjbt1                          310.8 ms	 314.5 ms       +1.2%
queens5x5/bjbt2                          327.0 ms	 332.6 ms       +1.7%
queens5x5/fc                             742.4 ms	 753.2 ms       +1.5%
```
I didn't actually check out your branch for any of these, just added a `!` to the contents of `VCon`, but as far as I could see that's the only real change you made.  This defintely improved things in the past, so I have no idea why it doesn't seem to be helping now.

**Review by kwxm — COMMENTED** [review]
Not much to say, except that this unexpectedly seems to make things worse on all the examples I tried.

**Comment by effectfully** [comment]
@kwxm I really don't understand how I got a definite speed-up multiple times and you got a definite slowdown multiple times. I guess I shouldn't use my laptop for running the benchmarks anymore, given that I did everything right (killed every big program, ensured that no other process is actively running etc) and still got completely different results.

@michaelpj I guess we should revert this commit?

**Comment by michaelpj** [comment]
I don't know. I'm somewhat okay with it given that it seems to be ambiguous and maybe machine-dependent. This version makes sense to me and all else being equal I think it's better to have the version that makes more sense to the reader (and I think "data fields of `CekValue` are strict makes the most sense).

**Pull request merged**
