### PR TITLE
Remove caching of builtin runtimes

### PR DESCRIPTION
**Pull request by effectfully**
Don't look here yet.

### CODE REVIEW

**Comment by effectfully** [comment]
Nice :)
But worry not, that is to be expected. Let's try to revert that.

**Comment by effectfully** [comment]
Well, that is surprising to me. The code now is supposed to push all the thunks for meanings of builtins outside if the main loop, so that they're only created once, but either I've failed at that (I should try using some `trace` or something, it's hard to figure out what's going on from reading Core) or the cost of converting from BuiltinMeaning to BuiltinRuntime on the fly is just that high, which seems unlikely.

**Comment by effectfully** [comment]
Ok, I'm pretty clueless as to what's going on here. The thing is, we might be having the same problem at startup currently without knowing it. Whatever is slow here is quite likely also slow during the initial traversal where we compute the `BuiltinRuntime` for each builtin in `master`. This certainly needs to be investigated, but I'm gonna postpone that for now.

**Comment by michaelpj** [comment]
> The thing is, we might be having the same problem at startup currently without knowing it.

That's true. However, if that's the case we can certainly address it on the ledger side by ensuring that that is only done once and is then cached.

**Pull request closed without merging**
