### PR TITLE
SCP-2652 - Add more necessary Marlowe types to the frontend

### PR DESCRIPTION
**Pull request by merivale**
This PR makes some additional Haskell types available in the Marlowe Run frontend code. Some are added to the PAB's PSGenerator (@j-mueller please check you're happy with including these there). And others are added manually to `Marlowe.Semantics` and to a new `Marlowe.Client` module (to correspond to the `Marlowe.Client` module in the Haskell code).

This is a prerequisite to SCP-2594 (handling errors from the Marlowe Plutus contract) - this PR stops short of dealing with these properly, and adds a `FIXME` comment at the relevant point.

Having to write out duplicate types manually isn't ideal, but as things stand I couldn't see a way around this, because the types in question depend on types in `Marlowe.Semantics` (which are all duplicated manually and have custom encoding/decoding instances). Ideally we will find a way at some point to do without the custom serialization and just generate these types automatically - or maybe even get `Marlowe.Semantics` running in the browser with `ghcjs`. But for now, I think this is the best we can do.

### CODE REVIEW

**Comment by palas** [comment]
They can still be generated by using bridges that can be defined like this: https://github.com/input-output-hk/plutus/blob/master/fake-pab/app/PSGenerator.hs
You can see `CreateContractRequest` has `Contract` inside: https://github.com/input-output-hk/plutus/blob/master/fake-pab/src/API.hs and it is part of the API and the PureScript types are generated automatically

Is that what you were trying to do?

**Comment by merivale** [comment]
Aha, cool, I did not know that. Yes, that should work in this case. But then I we'd want a separate PSGenerator for Marlowe Run to generate the Marlowe.Client types in that way - which could be left for follow-up PR.

**Review by palas — APPROVED** [review]
Looks good 👍
Sorry, I had forgotten to mark it as approved

**Comment by merivale** [comment]
This introduces a front-end bug, but I'm 95% sure I know what the problem is. I don't have a fix yet, but fixing it will be easier at this point in another PR - so I'm going to go ahead and merge when it goes green.

**Pull request merged**
