### PR TITLE
Plutus Tx: define converter functions in Haskell rather than directly

### PR DESCRIPTION
**Pull request by michaelpj**
Currently, the Plutus Tx compiler defines its builtins in a somewhat odd way:
- We define the names for the builtins in `PlutusTx.Builtins`
- But these have the wrong types in some cases: they mention the Haskell `Bool`, which compiles to a perfectly good datatype, but not to the builtin Plutus Core `bool`.
- So we manually craft some adapters _inside the compiler_ in order to convert between the Haskell and builtin versions of some types. This causes much suffering, and was causing me even more in my branch trying to use builtin `data`, which requires much more complicated converters to deal with builtin lists and tuples.

Roman got me thinking: why can't I do all this in Haskell and use my compiler? The answer is: we can.

The steps:
- Define a new module `PlutusTx.Builtins.Internal` that contains Haskell types that map _directly_ to the builtin types in all cases, and Haskell functions that map directly to the builtin functions with the right types (with one exception for error).
- Provide some conversion functions in `PlutusTx.Builtins.Class`, making use of the fact that we now have an explicit definition for e.g. `ifThenElse` that we can actually use. I made a little typeclass too.
- Wrap up the builtins in `PlutusTx.Builtins` using the conversion functions to make sure the types line up.

This achieves more-or-less the same thing, but is *way* simpler. In particular, the compiler gets a lot simpler, which is a big deal. Now the builtins part deals *only* with builtins, which also means I was able to throw away some weird dependency tracking stuff I had in there.

Drawbacks:
- In order to write the wrapped builtins nicely, I gave them actual arguments, which means they no longer get inlined currently. This is mainly a deficit of the current inliner, I'm not too bothered (but I remember this bothering @kwxm before).
- In the search for consistency I renamed the Haskell version of builtin string type to `BuiltinString`. I think this is reasonable, and may make people less confused. I think maybe we should do the same in https://github.com/input-output-hk/plutus/pull/3327, but I'm not sure (thoughts, @ak3n ?).
- I'm not sure my typeclass totally makes sense. Possibly I should just use it for things that really do have a representation correspondence, and not the things that "represent" themselves. Not sure.

This is not finished, I need to deal with the fallout in downstream packages, but all of the interesting parts are reviewable.

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Huh, amazingly everything compiled, so I just needed to update test output. Looks like people only use `BuiltinString` via string literals, phew.

**Comment by michaelpj** [comment]
I added a new builtin, `chooseUnit :: () -> a -> a` which pattern-matches on unit. This is a dumb (but uncontroversial) thing in principle, but I was having a lot of difficulty with GHC throwing away the results of `trace`, and this allows me to make it more obvious that the result is "consumed".

**Review by ak3n — APPROVED** [review]
Looks good overall (from my perspective). 

>In the search for consistency I renamed the Haskell version of builtin string type to BuiltinString. I think this is reasonable, and may make people less confused.

I agree 👍  Would be nice to do the same for `ByteString`.

**Comment by michaelpj** [comment]
Nikos is on holiday and I have stuff to do on top of this, so in it goes.

**Pull request merged**
