### PR TITLE
add shell.nix with pinned 19.03 nixpkgs containing

### PR DESCRIPTION
**Pull request by disassembler**
* terraform
* aws_shell
* awscli

### CODE REVIEW

**Comment by michaelpj** [comment]
Excited to have our third nixpkgs pin in this repo ;)

**Comment by michaelpj** [comment]
I think I misunderstood - is the reason we're not using the main pin that the dependencies aren't built by CI? If so, then I think the right thing to do is just get them built. I already have a listing in `default.nix` for "dev packages" that we want to build on CI so they're cached, we could use that.

**Comment by shmish111** [comment]
@disassembler

**Comment by disassembler** [comment]
@michaelpj @shmish111 that is correct... Short stop-gap for the summit. We'll get this resolved afterwards. 19.03 just released 2 days ago, so we'll get the default pin bumped in the upcoming month. terraform/aws-shell could also be added to plutus release.nix to get CI building it, but we wanted to add more clutter to your release.nix.

**Pull request merged**
