### PR TITLE
SCP-2692: add reference page on the cost model paramteters

### PR DESCRIPTION
**Pull request by michaelpj**
Kenneth, there were a few where I didn't know what to say (marked `???`), help me out!

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by kwxm** [comment]
> there were a few where I didn't know what to say (marked ???)

I don't see any question marks.

**Comment by michaelpj** [comment]
Oh, I made them `TODO` because something didn't like the question marks. I'll ask you tomorrow.

**Comment by kwxm** [comment]
While we're looking at this, it might be worth having a link to the online version in the README file.

**Comment by michaelpj** [comment]
> While we're looking at this, it might be worth having a link to the online version in the README file.

It's literally the first link in the README :)

**Comment by kwxm** [comment]
> > While we're looking at this, it might be worth having a link to the online version in the README file.
> 
> It's literally the first link in the README :)

Not that README, the other one!

**Comment by kwxm** [comment]
I think the thing about the diagonal is the wrong way round.  I'll open a new PR to fix that. (Sorry for the late review...).

**Pull request merged**
