### PR TITLE
Merge marlowe tutorial into main docs

### PR DESCRIPTION
**Pull request by michaelpj**
This merges the Marlowe tutorials into the Sphinx doc site.

This has a few advantages:
- We can cross-reference between them more easily (there are a couple of
exmaples of this even in the docs to date), and share explanatory content.
- The Sphinx site makes it easier to structure the docs (as opposed to
with Asiidoctor where it was all one page).
- We can engage with documentation writers and infrastructure people
with a combined front.

I haven't touched the content and structure much, which could definitely do with work.

(I also optimized the PNG sizes with `optipng`, since otherwise it's
quite a lot of bytes even just moving them...)

-----------

It would be good for some people to eyeball the output. I've put a short README in the doc site since it didn't have instructions before.

Since the documentation now includes docs for both Plutus and Marlowe, I tweaked the nginx rules to direct people to the correct tutorial sub-path in each case. I'm not entirely sure how to test this, maybe @gilligan can let me know what to try?

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
BTW there's a generated preview link in the checks section!

**Comment by simonjohnthompson** [comment]
It all looks fine, but as you say, in need of refreshment!

**Review by simonjohnthompson — APPROVED** [review]
It all looks fine, but as you say, in need of refreshment!

**Comment by nau** [comment]
LGTM, the only worry I have is whether we have all the links valid from dashboard, playground etc to the tutorial?

**Comment by michaelpj** [comment]
Yeah, that's what I'm worried about too, I'm just not sure how to check if I got it right. I grepped through the codebase for references to `tutorial`, and I think I got them all...

**Comment by gilligan** [comment]
@michaelpj as for testing, the `all.nix` vm-test currently has the following:

```
    playgrounds.succeed("curl --silent http://plutus-playground:8080/ | grep  'plutus'")
    playgrounds.succeed("curl --silent http://plutus-playground:8080/tutorial/ | grep 'The Plutus Platform'")
    playgrounds.succeed("curl --silent http://marlowe-playground:9090/ | grep 'marlowe-playground'")
    playgrounds.succeed("curl --silent http://marlowe-playground:9090/tutorial/ | grep 'Marlowe Tutorial'")
```

So obviously just a smoke-test but better than nothing.

**Comment by michaelpj** [comment]
Okay, so what seemed to be the simplest way to make this work nicely was:
- Playgrounds now map `/doc` to the root of the docs site, rather than `/tutorial` going to the tutorial
- Links to the tutorial go to `/doc/marlowe/tutorials` or whatever as appropriate

VM tests now pass.

**Pull request merged**
