### PR TITLE
[PLC] [Test] [TypeCheck] Added 'Examples.Data.Vec'

### PR DESCRIPTION
**Pull request by effectfully**
This shows how to represent Church- and Scott-encoded vectors in Plutus Core.

### CODE REVIEW

**Comment by effectfully** [comment]
@michaelpj it's really annoying that now I need to reach for `nix` even if I only added a single new `*.hs` to the repo. Given that the CI knows how to update nix stuff to fix what it doesn't like:

> +          "Language/PlutusCore/Examples/Data/Vec"

is there any way to do that automatically?

**Comment by michaelpj** [comment]
> it's really annoying that now I need to reach for nix even if I only added a single new *.hs to the repo

This is annoying, but it's somewhat inherited from cabal, since the Nix stuff mirrors the cabal stuff. (It's pretty annoying you have to edit your cabal file every time you add a module too, but we're used to that...) 

> is there any way to do that automatically?

Yes, we can auto-generate this stuff - but it makes things slower. So in the end we opted to go for checking in the generated stuff and having to re-generate it. But that should be a single command these days.

**Comment by effectfully** [comment]
> (It's pretty annoying you have to edit your cabal file every time you add a module too, but we're used to that...)

It is annoying indeed, but at least I don't need to switch my build tool every time I add a new module, just edit the `.cabal` file. 

> Yes, we can auto-generate this stuff - but it makes things slower. So in the end we opted to go for checking in the generated stuff and having to re-generate it.

Not that our CI is particularly fast anyway. How much slower does autogenerating `nix` stuff make the CI?

> But that should be a single command these days.

For me it's:

1. commit & push
2. wait for CI to show an error
3. go turn on a different machine where I have `nix`
4. "what the heck that command was?" -- open the browser, go to `CONTRIBUTING.md`
5. call the command, wait for eternity until `nix` builds all its stuff, because it seems to change somewhat often and the binary cache doesn't work for me for whatever reason
6. commit & push

I could get used to it and try to set up `nix` on my main machine, but I'd been happily using `stack` for developing Plutus for two years until it suddenly became necessary to deal with `nix` whenever a file is added. Can we return these happy days? I don't mind dealing with `nix` when dependencies change, but imposing `nix` over potential contributors to our Haskell project when `cabal` or `stack` would do the job seems silly.

**Comment by michaelpj** [comment]
> Not that our CI is particularly fast anyway. How much slower does autogenerating nix stuff make the CI?

Not just the CI, but essentially every use of a `nix` command. I know you don't use it, but it affects those of us who do quite a lot.

> I could get used to it and try to set up nix on my main machine, but I'd been happily using stack for developing Plutus for two years until it suddenly became necessary to deal with nix whenever a file is added.

I *do* think that you need to have Nix installed. It is the tool we use for CI as well as integrating all our stuff. We go to some effort to make sure you can use `stack` or whatever most of the time, I don't think it's unreasonable to ask that you have Nix installed to run one or two commands every now and again!

> I don't mind dealing with nix when dependencies change

I agree it's more annoying in that way, but we've been through quite a number of ways of doing this and we ended up here because it's the least annoying so far (but maybe more annoying for you...).

And it is only one command! If you actually did it occasionally it probably wouldn't take hours either ;)

**Comment by michaelpj** [comment]
I will ask about the module listing thing, you never know, maybe we can improve that.

**Comment by michaelpj** [comment]
https://github.com/input-output-hk/haskell.nix/issues/696

**Comment by effectfully** [comment]
> Not just the CI, but essentially every use of a nix command. I know you don't use it, but it affects those of us who do quite a lot.

Ah, I did not realize if was affecting every `nix ` command.

> I do think that you need to have Nix installed. It is the tool we use for CI as well as integrating all our stuff. We go to some effort to make sure you can use stack or whatever most of the time, I don't think it's unreasonable to ask that you have Nix installed to run one or two commands every now and again!

Ok, I'll spend some time figuring out how to install `nix` on a machine with a small main partition.

> I will ask about the module listing thing, you never know, maybe we can improve that.

Thanks!

**Pull request merged**
