### PR TITLE
Add pre-commit to shell.nix

### PR DESCRIPTION
**Pull request by zliu41**
so that in the nix shell we have nix's pre-commit, not the one in your `.local/bin` installed from pip, which for some reason doesn't work in the nix shell.

### CODE REVIEW

**Comment by zliu41** [comment]
@michaelpj this makes nix's `pre-commit` appear earlier in PATH in the nix shell. Previously `pre-commit` was at the end of PATH, after `$HOME/.local/bin`, which means the wrong `pre-commit` is used if you have one in `.local/bin`.

**Comment by michaelpj** [comment]
Hmm, but that can't be true for all the stuff that goes in the shell? otherwise everyone's tools would be overriding the stuff in the shell. So why is pre-commit at the end?

**Comment by michaelpj** [comment]
I see: it's the `shellHook` from `pre-commit-hooks.nix` which appends it to the `PATH`: https://github.com/cachix/pre-commit-hooks.nix/blob/c3b4f94350b0e59c2546fa85890cc70d03616b9c/modules/pre-commit.nix#L322

Could you open an upstream issue and add a comment explaining why we need this?

**Comment by zliu41** [comment]
Done, nice diagnosis!

**Review by effectfully — APPROVED** [review]
Just checked, it fixes my problem. I love you.

**Pull request merged**
