### PR TITLE
Test commit

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by kwxm** [comment]
Will this let you add further arguments to the benchmark command?  The validation benchmarks have a `--quick` option that will just runs a smallish subset of the benchmarks, so I'm wondering if we'll be able to use that from PRs.

**Comment by michaelpj** [comment]
I think it should, it's basically just dropping whatever you put there after "cabal bench". I'll try that once I get this working.

**Comment by michaelpj** [comment]
Boom!

**Comment by michaelpj** [comment]
/benchmark plutus-benchmark:validation --benchmark-options="--quick"

**Comment by michaelpj** [comment]
Okay, that doesn't work just yet, probably need some more quoting...

**Pull request closed without merging**
