### PR TITLE
Kwxm/flat in plc exe (SCP-1323)

### PR DESCRIPTION
**Pull request by kwxm**
Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
   - [x] `$(nix-build default.nix -A dev.scripts.updateMaterialized)` to update the materialized Nix files
   - [x] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
   - [ ] `$(nix-shell shell.nix --run fix-stylish-haskell)` to fix any formatting issues
- If you changed any Purescript files:
   - [ ] `$(nix-shell shell.nix --run fix-purty)` to fix any formatting issues

Pre-merge checklist:
- [x] Someone approved it
- [ ] Commits have useful messages
- [x] Review clarifications made it into the code
- [x] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
> Useful pull request description

:thinking:

**Review by michaelpj — APPROVED** [review]

**Comment by kwxm** [comment]
This makes the `plc` command capable of handling Flat files: it can read, write, and execute typed and untyped Flat-encoded ASTs and convert them into other formats.  ASTs with Names and with de Bruijn indices are both handled.

**Comment by kwxm** [comment]
> > Useful pull request description
> 
> thinking

I think you typed that when I was typing in the useful pull request description. When I opened the PR I got the checklist and then I had to fill that in.  Are we supposed to write the description in the same place as the checklist?

**Comment by kwxm** [comment]
Also, I usually add the JIRA to the PR title.  Should we mention in in commit messages too?

**Comment by michaelpj** [comment]
The checklist is just a pre-populated part of the PR description. It's just some markdown. You can write a description above it. Maybe I should clarify the template!

I think putting the ticket in the commit is helpful, and I think JIRA may even pick that up (although I'm not 100% sure what it notices).

**Comment by kwxm** [comment]
> I think JIRA may even pick that up (although I'm not 100% sure what it notices).

Yes, that's what I was wondering about.  I thought it was supposed to spot that, but I don't recall ever seeing it doing anything in response.

**Comment by kwxm** [comment]
Right, I'll merge this while the going's good.  If @raduom wants to check that the Flat stuff's correct later then please do so. I have converted some programs to Flat and then successfully deserialised and run them, so I think it's OK.

**Review by raduom — APPROVED** [review]
LGTM

**Pull request merged**
