### PR TITLE
[PIR] [Docs] Added a doc about type checking PIR

### PR DESCRIPTION
**Pull request by effectfully**
[Rendered](https://github.com/input-output-hk/plutus/blob/ec1540a2da65280002f5877c64cda3480b81edef/language-plutus-core/docs/Typechecking%20PIR.md)

### CODE REVIEW

**Comment by effectfully** [comment]
I think we're not doing this, so I don't mind if the PR gets closed.

**Comment by jmchapman** [comment]
If you can define a type in a let perhaps you should be able to have lets in types.
The type of 
```let data Success :: * = MkSuccess in MkSuccess```
could be
```LET data Success :: * = MkSuccess IN Success```
or written together
```let data Success :: * = MkSuccess in MkSuccess :: Success```

One other nagging thing is that it seems to me that there are several issues at play here:
1. compiling from a sequence of definitions to a single expression.
2. the switch from a nominal setting (two different definitions of bool are different) to a structural setting (two different definitions of bool are the same). Borrowing nominal/structural terminology from Phil's featherweight go talk where he explains the difference between java subtyping (nominal) and go subtypting (structural).
3. Compiling from a langugage with lets to a language without.

Otherwise, I like the well explained plan to check all the bits. I think it's valuable and should be added to the docs, whether it's going to be implemented now or not.

**Comment by michaelpj** [comment]
> If you can define a type in a let perhaps you should be able to write a let in a type.

Cute. I don't know what that would look like in PLC though! Our type-lets are very much term-level (they're really type abstractions).

> the switch from a nominal setting (two different definitions of bool are different) to a structural setting

I think we don't actually *want* the structural setting. That's what I've been getting at with the `Data` problem: we *could* say it's all fine so long as your `Data` types are structurally the same it will all work. But this is a bit unspecified to my eye. So I'd like to just stay in the nominal setting the whole time (admittedly relying on an extra-theoretic nominal type-equality across different people's sets of builtins: my `Data` builtin would have to be "the same" as your `Data` builtin).

> compiling from a sequence of definitions to a single expression.
> Compiling from a langugage with lets to a language without.

These *are* currently treated separately, in that the first happens in the Plutus Tx compiler, and the second happens in the Plutus IR compiler. But they are *linked*, in that the design of Plutus IR is precisely to be a halfway house that lets us break apart these concerns a bit (in that Haskell has both lets and global definitions, and PLC has neither).

**Comment by effectfully** [comment]
I wanted to extend the doc with an approach that allows to handle

```
let x : Success =
  let data Success :: * = MkSuccess in
    MkSuccess
in x
```

but @michaelpj tells me we don't need any of that.

Feel free to merge the PR.

**Comment by effectfully** [comment]
@michaelpj anything preventing this from being merged?

**Comment by michaelpj** [comment]
Nope, for some reason I thought you were still looking at it

**Comment by effectfully** [comment]
> I wanted to extend the doc with an approach that allows to handle
> 
> ```
> let x : Success =
>   let data Success :: * = MkSuccess in
>     MkSuccess
> in x
> ```
> 
> but @michaelpj tells me we don't need any of that.
> 
> Feel free to merge the PR.

Future me, if you ever wonder what past me meant, I think he meant viewing `let`-expressions as implicitly creating modules, so that 

```
let x : Success =
  let data Success :: * = MkSuccess in
    MkSuccess
in x
```

means

```
module _1 where
  data Success :: * = MkSuccess

  result : Success
  result = MkSuccess

module _2 where
  x : _1.Success
  x = _1.result

  result : _1.Success
  result = x
```

This is a rather non-standard interpretation of a `let`-expression, but given that it's not nonsensical and allows us to type check what we can compile down to a well-typed PLC term (I don't really remember and don't want to reinvent this square wheel though), I think past me had a point.

**Pull request merged**
