### PR TITLE
[Builtins] Monomorphize 'makeKnown'

### PR DESCRIPTION
**Pull request by effectfully**
Don't look here yet.

### CODE REVIEW

**Comment by effectfully** [comment]
It does make sense that this is slower than the baseline. `makeKnown` does not normally contain any `>>=` to get inlined and in this PR we return a tuple, which does require some bookkeeping, plus we still want a monad, so we have to make a monoid out of the log messages, which is cheap, but still not as cheap as not doing it, because now we have to always call `traverse_` over the log messages, which is cheap but wasteful in the vast majority of cases, since we don't return log messages that often. Plus what's in `master` is kinda like a Church-encoded version of what we have here.

So overall, this is slower than `master` for valid reasons, so I'm closing the PR (I'll add some docs about this experiment in the [PR](https://github.com/input-output-hk/plutus/pull/4307) that does the same, but for `readKnown`).

**Comment by michaelpj** [comment]
Also the results are pretty close to the noise threshold! Do agree it's not worth it, though.

**Comment by michaelpj** [comment]
That said... I'd be somewhat tempted to do this anyway just to make it consistent with `readKnown` if we merge that!

**Comment by effectfully** [comment]
I'll split the `KnownTypeIn` class into two classes or do something even more drastic anyway, so let's not worry about consistency for now.

**Comment by effectfully** [comment]
This is also not the first time when a certain transformation affects `makeKnown` differently than what it does for `readKnown`. For example passing `throwError` from `MonadError` worked _better_ for `makeKnown` than it did for `readKnown`. I'm currently going after maximum performance, so I don't want to commit to any restricting design choices.

Plus I simply dislike this version of the code.

And yeah, 2+% slowdown is double the noise threshold.

**Pull request closed without merging**
