### PR TITLE
PLT-867: Remove plutus-errors package

### PR DESCRIPTION
**Pull request by bezirg**
This PR is of 2 patches:

1) removes the errorcode typeclass and plutus-errors package.
2) strictifies all error constructors' fields.

The (2) I did almost mechanically, so take a look if I put too much or too few bangs (especially those on the plutus-ledger-api).
I added bangs manually, if you prefer me to have StrictData instead let me know.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
I'm pretty in favour of `StrictData` tb.

**Comment by michaelpj** [comment]
But manual strictness is fine.

**Review by michaelpj — APPROVED** [review]

**Review by effectfully — COMMENTED** [review]
Requires running the benchmarks, we've seen cases where changing how errors are handled affected performance on the happy path too (since GHC may now decide to create a thunk for an error and throw it away every time a builtin is evaluated successfully).

**Comment by effectfully** [comment]
Try `plutus-benchmark:validation` instead of `validation`?

**Comment by bezirg** [comment]
@effectfully I don't think it is that, I think the benchmark failed for some reason (exhausted cpu or memory). I have a feeling I may have forced something I shouldn't

**Comment by effectfully** [comment]
> @effectfully I don't think it is that, I think the benchmark failed for some reason (exhausted cpu or memory). I have a feeling I may have forced something I shouldn't

You could check that by running the benchmarks locally on your machine, I guess.

**Comment by bezirg** [comment]
@effectfully benchmarks look ok I guess?

**Comment by effectfully** [comment]
> @effectfully benchmarks look ok I guess?

Yep, everything's good. We normally need to check the generated Core just in case, but I'm going to do that a lot in some near future and given that the benchmarks look good, let's ignore Core checking.

**Pull request merged**
