### PR TITLE
core-to-plc: big reorganization

### PR DESCRIPTION
**Pull request by michaelpj**
This reorganizes core-to-plc so there are more, smaller files. I've
wanted to do this for a while, but unfortunately there are some big
recursive cycles. I've just bitten the bullet and added `.hs-boot` files
for these.

Github doesn't deal well with this kind of change, probably best to just review the final state.

### CODE REVIEW

**Comment by michaelpj** [comment]
> Could we avoid them by combining just Type.hs and Expr.hs?

That's exactly what I'm trying to avoid, since those are the biggest files.

**Comment by mchakravarty** [comment]
> That's exactly what I'm trying to avoid, since those are the biggest files.

I do understand that, but the question is whether it is worth having boot files.

**Comment by michaelpj** [comment]
Seems to work fine so far :man_shrugging:

**Comment by michaelpj** [comment]
What problems do they cause?

**Pull request merged**
