### PR TITLE
EXPERIMENT: benchscopecheck

### PR DESCRIPTION
**Pull request by bezirg**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by effectfully** [comment]
I'm gonna try using a specialized version of the function doing scope checking this weekend just out of curiosity.

**Comment by michaelpj** [comment]
Sure, but we're going to get rid of it anyway, so it's not that important.

**Comment by effectfully** [comment]
> /benchmark plutus-benchmark:validation

Stupid me.

**Comment by effectfully** [comment]
Screenshot from 2022-02-19 05-49-01

Clearly not my day.

**Comment by effectfully** [comment]
Well, it seems out noise threshold is bigger now.

**Comment by effectfully** [comment]
Not bad, huh?

**Pull request closed without merging**
