### PR TITLE
[Docs] Constructing folds from PlutusIR-like data types

### PR DESCRIPTION
**Pull request by effectfully**
tl;dr: 

> basically the type language of a PlutusIR-like language is way too expressive and proving generic properties about PlutusIR-like data types does not look feasible without restricting the type language

### CODE REVIEW

**Comment by wadler** [comment]
How many times do you want folks to read and comment on the text? Currently there is a lot of test missing, so you'll need it reviewed again later. You need to beware reviewer fatigue.

I find the current text difficult to read, because there is no introduction. It just leaps into the semantics of types. There is a title about 'constructing folds', but is that the main thing we want to explain about IR and its translation to Plutus Core? Why?

On today's call, we talked a bit about using Agda as a presentation medium. I see that using Agda implies a DeBruijn encoding. That's ok, but then you need to help the reader by *always* showing the type or term with variables before showing the one without. Also, the presentation uses tricks like "Append the second environment to the first one in reverse order. _◁▷_" I think we should avoid this kind of trick if at all possible. My original presentation of F avoided such a trick (and I thinks James's does also), so we should be able to avoid it here. You will also need to write the text so that it can be read by someone not intimately familiar with Agda.

**Comment by effectfully** [comment]
> How many times do you want folks to read and comment on the text? Currently there is a lot of test missing, so you'll need it reviewed again later. You need to beware reviewer fatigue.

You have to be more specific about what text is missing, because I did my best writing this article and also spent a huge amount of time (both working and personal) which I could spend in a more useful way.

Since we agreed during the call that we're not going to write proofs in the paper, I'll just close this PR and forget about it.

> I find the current text difficult to read, because there is no introduction.

Not sure what you mean. There is this:

```
-- In this article we'll show how to define data types in a PlutusIR-like language and describe
-- the problem that arises when we try to construct a generic fold over such data types.
```

> There is a title about 'constructing folds', but is that the main thing we want to explain about IR and its translation to Plutus Core?

It's the minimal thing that we want to explain about the infeasibility of translating a PlutusIR-like language to System F-omega. This is elaborated in the article: 

```
  -- We're interested in whether it's possible to translate a data type described as a list of
  -- constructors to vanilla System Fω, take the denotation of that (i.e. just call `⟦_⟧ᵗ`) and
  -- prove that the resulting denotation is isomorphic to the denotation of the original description.
  -- But we do not even attempt doing that in this article, because we fail quickly without diving
  -- into any particular details of the translation.

  -- In order to define a translation we at the very least need a function that takes a value of the
  -- denotation of a list-of-constructors data type and turns it into a value of the denotation of
  -- this data type encoded as a vanilla System Fω type (we also need a function that works the
  -- other way around and proofs that those two functions are inverses of each other).
  -- Such function is basically a fold over a list-of-constructors data type. Arguments of this fold
  -- are constructors of the encoded data type. We do not have encoded data types in this article,
  -- but all this mapping mechanics remains the same everywhere and we can look at examples with
  -- native Agda data types instead:
  --
  -- 1) see `toList` for an inlined fold
  -- 2) see `toInterList` for an example with an actual fold
```

And then there is a high-level explanation of problems that arise and a low-level explanation of those problems (the latter can only be read by people who understand how this kind of generic programming works) and a proposed solution.

I cannot move those paragraphs to the intro, because they refer to the list-of-constructors representation and talk about denotations.

> That's ok, but then you need to help the reader by always showing the type or term with variables before showing the one without.

In the article de bruijnifed types mostly come together with their readable counterparts. There are exceptions:

1. the type of constructors of lists (which anybody knows anyway) are only in de bruijnifed form
2. a de bruijnifed type comes together with its meaning, but the meaning is normalized

But point taken, thank you, next time I'll do the right thing.

> Also, the presentation uses tricks like "Append the second environment to the first one in reverse order. ◁▷" I think we should avoid this kind of trick if at all possible. My original presentation of F avoided such a trick (and I thinks James's does also), so we should be able to avoid it here.

That's because neither your presentation nor the James' one does what mine does. I'm not reversing things, because it's fun, I'm reversing them, because I spent a day trying to figure out what's the best approach here and settled on the current one. This is explained as well:

```
-- A data type is defined in a reversed context, which we then reverse again and prepend an element
-- to it which denotes the variable responsible for recursion. There is no deep theoretical reason
-- why the contexts are reversed, it's simply much easier to deal with, otherwise computing the type
-- of the variable responsible for recursion is harder and extending the context with that variable
-- is harder as well. We could require the user to provide the full context of a pattern functor,
-- but then we would need to check whether the context is of the
--
-- > (k₁ ⇒ ... ⇒ kₙ ⇒ ⋆) ▻ k₁ ▻ ... ▻ kₙ
--
-- form, while here we have correct-by-construction contexts.
```

> You will also need to write the text so that it can be read by someone not intimately familiar with Agda.

I'm not writing a paper or a textbook. I wrote an internal document that contains quite a lot of text explaining one particular issue and the context around it. Why would I target people who are not intimately familiar with Agda, if I'm specifically targeting only people from our team who can read Agda? I have way too many other tasks to waste time making this local document look like it can be published in a journal.

**Comment by michaelpj** [comment]
@effectfully can you reopen this? I'd like to read and review it.

I think Phil is right that we need to be careful about reviewer fatigue. But obviously those of us who are planning to work in detail on the paper are going to be going through many iterations of similar material. So perhaps it makes sense to circulate these less widely (or more clearly marked "in progress, only read if actively interested), and save checking in with Phil and Manuel til later.

**Comment by effectfully** [comment]
> @effectfully can you reopen this? I'd like to read and review it.

I'm not able to reopen it, because apparently a force-push prevents this and the suggestions that I found on the web did not help.

> So perhaps it makes sense to circulate these less widely (or more clearly marked "in progress, only read if actively interested), and save checking in with Phil and Manuel til later.

This wasn't intended as work in progress, this was intended as an elaborated and definite answer to a particular question. If it looks like work in progress, in can as well just live in [my personal gist](https://gist.github.com/effectfully/1a563ea0c1aefdc4e14d4fb4a5d101ed#file-directfold-agda).

**Pull request closed without merging**
