### PR TITLE
Fix serialisation of symbolic execution result

### PR DESCRIPTION
**Pull request by palas**
Extend pretty printing to include `TransactionInput` and `TransactionWarning` and modify symbolic execution result to use pretty-printing.

### CODE REVIEW

**Comment by michaelpj** [comment]
Possibly stupid question: why not use a more standard serialization format? Then you wouldn't have to rely on making sure your pretty-printers are perfect inverses of your parsers...

**Comment by palas** [comment]
Do you have any in mind? We were using `Show` until this pull-request, but the `Show` instance of `PubKey` is not understood by the Purescript side parser anymore. Alex was saying that pretty-printer worked already together with Purescript parser, so it seemed like the path of least friction.

**Comment by michaelpj** [comment]
The Plutus Playground sends data between the server and client in JSON, and I believe it just uses derived instances somehow.

But I guess if you have completely independent AST definitions that might not work.

**Comment by palas** [comment]
I see, yes we cannot derive `PubKey` because we just care about its `String` representation, so going through `ByteString` could be problematic, we can only interpret a subset of that as valid Marlowe, we probably want to generalise Marlowe to handle actual `PubKey` first.

**Pull request merged**
