### PR TITLE
SCP-1685: PAB client interaction docs & API

### PR DESCRIPTION
**Pull request by j-mueller**
* Add a document explaining how an appliation such as the Marlowe dashboard can interact with the PAB
* Add a new API that supports this interaction

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `$(nix-build default.nix -A plutus.updateMaterialized)` to update the materialized Nix files
   - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
   - [x] `$(nix-shell shell.nix --run fix-stylish-haskell)` to fix any formatting issues
- If you changed any Purescript files:
   - [ ] `$(nix-shell shell.nix --run fix-purty)` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by j-mueller** [comment]
Rendered diagrams below (yeah there has to be a better way - I think we'll include this in the whitepaper)

## System description

grafik

## Structure of the PAB

grafik

## Starting a new instance of a contract

grafik

## Calling an endpoint

grafik

**Comment by j-mueller** [comment]
I'm going to add a section on the Marlowe dashboard app because some of the things we've discussed aren't included in this document yet @nau

**Comment by j-mueller** [comment]
## System description (marlowe dashboard)

grafik

## Typical usage (marlowe dashboard)

grafik

**Comment by j-mueller** [comment]
@michaelpj Should I convert to latex and move it to `plutus-report` ?

**Comment by michaelpj** [comment]
Up to you - the section on the PAB in general is pretty old and could do with being revisited. I'm happy to incrementally improve it by adding stuff like this, or to incorporate it all at a later date.

**Comment by michaelpj** [comment]
More generally: I think you should probably "own" the applications section of the report going forward, so if you think the content belongs in there, then the content belongs in there!

**Comment by j-mueller** [comment]
I had a quick look at the document. The apps section does need a bit of work so I'll schedule some time for that after the Marlowe dashboard.

**Review by shmish111 — APPROVED** [review]

**Pull request merged**
