### PR TITLE
Upgraded all dependencies to use node version 1.30.

### PR DESCRIPTION
**Pull request by raduom**
Update the dependencies to pull node version 1.30.

Note:
* I had to temporarily fork the cardano-ledger-specs to fix some compilation errors due to the different version of plutus that the cardano-ledger-specs is built against.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Review by j-mueller — APPROVED** [review]
Nice!

**Comment by michaelpj** [comment]
Hmmmmmmmmmmm. The `plutus-use-cases` scripts output job failed with some UTF-8 error, is this because they merged that commit about decoding asset names differently?

**Comment by raduom** [comment]
It's been failing consistently since yesterday. When was that commit merged?

**Comment by michaelpj** [comment]
i.e. https://github.com/input-output-hk/cardano-node/pull/3206

**Comment by j-mueller** [comment]
We don't use that encoding in our test cases AFAIK

**Comment by j-mueller** [comment]
Ah wait. Yes we do. And that is the reason why it fails. So I think we have to comment out those traces (auction) that cause it to fail.

**Comment by raduom** [comment]
This reproduces the problem. I will look into that binary to see where it actually comes from.

```
cabal exec plutus-use-cases-scripts -- tmp transactions
Writing transactions to: tmp
Writing partial transaction JSON: tmp/auction_1-1.json
Writing partial transaction JSON: tmp/auction_1-2.json
Writing partial transaction JSON: tmp/auction_1-3.json
plutus-use-cases-scripts: Cannot decode byte '\xe6': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

**Review by j-mueller — CHANGES_REQUESTED** [review]
It would be easier to just comment out the lines in `plutus-use-cases/scripts/Main.hs` (l. 85 / 86)

**Review by j-mueller — APPROVED** [review]

**Pull request merged**
