### PR TITLE
Update to LTS-15 and GHC 8.8

### PR DESCRIPTION
**Pull request by michaelpj**
8.10 is out, seems good to not stay too far behind.

Mostly minor changes and fixing new import warnings. Slightly more major
changes:
- Hedgehog has changed some stuff. In particular `filter` is a bit
strange now. I think that means we should change some things, but I just
switched to using a slightly different function which I think does the
right thing.
- Language feature warnings/errors now propagate from inside splices to
the code that uses them. In practice, this means that our Plutus Tx
splices started asking for `TypeApplications`. I refactored them to use
`Proxy` instead to avoid this.

There are a lot of ordering changes. I may investigate these, but I
think they're mostly due to things moving module inside GHC.

### CODE REVIEW

**Comment by j-mueller** [comment]
The build page is showing an error: https://hydra.iohk.io/jobset/Cardano/plutus-pr-1944#tabs-errors

**Comment by michaelpj** [comment]
Yeah, I'm working on it.

**Comment by reactormonk** [comment]
Can confirm, HIE still works (but you'll have to create your own 8.3.3 file). But when compiling with stack, it only works with `LANG=en_US.UTF-8`, but not with `LANG=en_GB.UTF-8`.

With `en_GB.UTF-8`:

```
all tests
  example programs:                                  OK
  parser round-trip:                                 OK (2.81s)
      language-plutus-core-test: <stdout>: commitBuffer: invalid argument (invalid character)
```

**Comment by michaelpj** [comment]
Hmm, I can't reproduce the locale issue with cabal, can you?

**Comment by michaelpj** [comment]
There are a bunch of Stack issues relating to locale settings, with "just set `LANG=en_US.UTF-8`" being a common suggestion. I'm inclined to chalk this up to a Stack  bug.

**Comment by j-mueller** [comment]
FYI, I just tried this in WSL and it worked fine, no problems at all.

**Comment by michaelpj** [comment]
Okay, let's go with this.

**Pull request merged**
