### PR TITLE
Avoid non-optimized PNGs

### PR DESCRIPTION
**Pull request by michaelpj**
Checking images into git repositories has a big impact over time, since images don't diff well. In some cases we can use things like SVGs which do diff better, but we can't really avoid it for screenshots etc. However, we can ensure that any PNGs are optimized, which makes a big difference for essentially no quality cost.

But it's easy to forget, so this adds:
- A Hydra test; and
- A script to automatically fix the issues

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by gilligan — APPROVED** [review]
LGTM - would be nice if we could also add a pre-commit-hook for this. Should be straight forward?

**Comment by michaelpj** [comment]
Oh yeah, I forgot to mention: I left out the pre-commit hook because it's a *little* bit slow, and I thought it would be annoying to have it in a hook. But now that you mention it, pre-commit hooks only run on changed files that match a prefix, right? so maybe it's fine.

**Comment by gilligan** [comment]
@michaelpj yes, only whenever you actually add/modify a .png in your commit. I suppose this shouldn't be too often and if that is slow it's not all that bad. Overall you still lose them then when you get the feedback from CI

**Comment by michaelpj** [comment]
Added a pre-commit hook, seems to work.

**Pull request merged**
