### PR TITLE
Update to GHC 8.6.4

### PR DESCRIPTION
**Pull request by michaelpj**
Putting this up in case the GHCJS folks are interested. I'm getting 8.6.4 into `iohk-nix`, then I'll bump to that, then it's probably worth merging.

### CODE REVIEW

**Comment by michaelpj** [comment]
Okay, I got the 8.6.4 commit through, so this now goes to 8.6.4, but will almost certainly be broken. I'm pushing here so hydra will build GHC for me :laughing:

**Comment by vmchale** [comment]
Is this compatible with the upstream? I thought there was some reason we didn't want to use a later snapshot.

**Comment by michaelpj** [comment]
I'm not sure what you mean by "the upstream"? If you mean the new cardano, they're already on a 8.6 snapshot (although an 8.6.3 snapshot), so I think this is fine.

In addition, I think it no longer seems so important to match versions with them. If we're going to communicate with everyone over HTTP APIs, then it doesn't matter unless it turns out there are libraries we want to share.

**Comment by vmchale** [comment]
I was talking about Cardano, yeah. As long as we're using the same snapshot I think it's correct. 

And I think the HTTP stuff is just for the Rust core nodes.

**Comment by michaelpj** [comment]
Here we go!

**Pull request merged**
