### PR TITLE
plutus-tx: add numeric hierarchy

### LINKED ISSUE #1386: Non-standard numeric hierarchy?
Plutus Tx currently has no numeric typeclasses. We have a couple of options:
- Add `Num`
- Add our own numeric typeclasses.

Why do the second? A few reasons:
- `Num` is kind of a bad typeclass, and we don't want most of it.
- We do have some slightly unusual types around: `Value` is a group and an `Integer`-module.

### PR DESCRIPTION
**Pull request by michaelpj**
In particular, we add:
- `Group`.
- `Additive` and `Multiplicative` `Semigroup`, `Monoid`, and `Group`.
    - These exist to be "structures with a numerical interpretation". It
wouldn't make sense for the general group operation to use `+`, but it
is nice to have classes that do that so we can e.g. make `Value` an
`AdditiveGroup`. This is not too bad with `DerivingVia`.
- `Semiring`, `Ring`.
    - These mostly exist to define `Module`.
- `Module`.
    - This characterises `Value`.

We then purge all the special-cased functions.

I don't have a symbolic operator for `Moudle`'s scaling operation.
Perhaps something like `*|` could do?

When in doubt, I've just imported things qualified to fix issues. We can tidy later. Finally, we get back to being able to use `+` for numbers!

Fixes #1386 .

### CODE REVIEW

**Comment by kwxm** [comment]
Is this level of generality really necessary?  Are there likely to be any cases where the ring of scalars for a `Module` isn't `Integer`, for example?  Modules over the integers are precisely the same thing as abelian groups. If you have an abelian group then you get multiplication by integers for free: n*m = m+...+m (n times), and that's the _only_ possible (unital) Z-module structure.

**Comment by brunjlar** [comment]
I like it. True, all modules right now are simply abelian groups, but I don't think the generality does any harm.

**Comment by kwxm** [comment]
I also find the idea of non-commutative currencies a bit disturbing!

**Comment by michaelpj** [comment]
I don't think the generality costs us much. And, for example, we *might* want to have `Value` contain fixed-point numbers instead of integers, at which point the abelian group formulation won't work whereas the module one will.

I agree that currencies should be commutative, but the Haskell way seems to be to only introduce classes for things that have actual new operations, and not for ones that are refinements of existing ones with properties like commutativity. So yeah, currencies should be abelian groups, but I don't think we need to reify that in the class hierarchy.

**Comment by kwxm** [comment]
> And, for example, we _might_ want to have `Value` contain fixed-point numbers instead of integers, at which point the abelian group formulation won't work whereas the module one will.

... because we might want to multiply two fixed-point numbers together?

> So yeah, currencies should be abelian groups, but I don't think we need to reify that in the class hierarchy.

Can we warn users about that in the documentation somewhere?  If someone has the brilliant idea of implementing a nonabelian currency then they'll find themselves in trouble.  Value preservation wouldn't make sense any more, and neither would modules.

**Comment by michaelpj** [comment]
> ... because we might want to multiply two fixed-point numbers together?

You might want to use other fixed-point numbers as the scalars.

> If someone has the brilliant idea of implementing a nonabelian currency then they'll find themselves in trouble.

They don't get to define the operations so there's no way they can do this. The `Value` type is a commutative group no matter what users do.

**Comment by kwxm** [comment]
> They don't get to define the operations so there's no way they can do this. The `Value` type is a commutative group no matter what users do.

In that case I'm confused (possibly because there was a previous discussion about generalising the Value type).  You talked about changing the Value type to be fixed point, but that's something that _we_ would do, not users.  Is there anything that users might want to use `Module` for, for example?  If not, then it seems a bit of overkill to introduce extra typeclasses to support a change that we're probably never going to make.

Anyway, all of this is just quibbling on my part.  Please don't let me stop you merging this!

**Comment by michaelpj** [comment]
No, users aren't going to change that. We might. My point is really: `Module` expresses what's going on better, and I think it makes us more robust to changes to do it that way. And I think it's clearer.

**Pull request merged**
