### PR TITLE
Kwxm/bench compare markdown

### PR DESCRIPTION
**Pull request by kwxm**
Just testing.

Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by kwxm** [comment]
@gilligan @michaelpj 

There seems to be something strange going on here.  I modified `ci-plutus-benchmark.sh` to print out the branches it was using:

```
PR_BRANCH_REF=$(git show-ref -s HEAD)
echo "### PR_BRANCH_REF=$PR_BRANCH_REF"
```
and then later
```
git checkout "$(git merge-base HEAD master)"
BASE_BRANCH_REF=$(git show-ref -s HEAD)
echo "### BASE_BRANCH_REF=$BASE_BRANCH_REF"
```
and in the [log](https://buildkite.com/input-output-hk/plutus-benchmark/builds/31#7e55a899-93c9-4543-850b-590f8fb13149) it said

```
[ci-plutus-benchmark]: Processing benchmark comparison for PR 3471
### PR_BRANCH_REF=f37f9cca5662fede7c334dfbf839d836a2926eaa
...


ci-plutus-benchmark]: Running benchmark for PR branch ...
--
[ci-plutus-benchmark]: Switching branches ...
Previous HEAD position was 204a1cb80 Make branches more obvious
HEAD is now at f37f9cca5 Fix contract placeholders to work with LocalStorage. (#3401)
### BASE_BRANCH_REF=f37f9cca5662fede7c334dfbf839d836a2926eaa
[ci-plutus-benchmark]: Running benchmark for base branch 
```
Now f37f9cca is [this commit](https://github.com/input-output-hk/plutus/commit/f37f9cca5662fede7c334dfbf839d836a2926eaa) by Amyas from the 21st of June.  I have no idea what that's doing there!  I'm also not sure if that's the commit that's actually checked when it's running the tests.

**Comment by kwxm** [comment]
It seems to be doing the same thing with Michael's PR #3340 (see the log here: https://github.com/input-output-hk/plutus/pull/3340).

```


[ci-plutus-benchmark]: Running benchmark for PR branch ...
[ci-plutus-benchmark]: Switching branches ...
Previous HEAD position was 655fe6060 SCP-2289: Try making a special "for evaluation" term type
HEAD is now at f37f9cca5 Fix contract placeholders to work with LocalStorage. (#3401)
[ci-plutus-benchmark]: Running benchmark for base branch ...
```

If it really is running the benchmarks in f37f9cc then that contains the old versions of the validation scripts (before @bezirg changed the flat encoding) which could have some bearing on the [weird regression](https://github.com/input-output-hk/plutus/pull/3340#issuecomment-869866437) that I couldn't reproduce manually.

**Comment by michaelpj** [comment]
Ah, I know what's up! Is anything updating the checkout? If it has a very old version of `master` then `git merge-base HEAD master` will give you the wrong answer.

**Comment by michaelpj** [comment]
I don't know how that checkout is even created, though.

**Comment by kwxm** [comment]
> I don't know how that checkout is even created, though.

Me neither.  I have enough trouble with git on my own machine, so when it's being automatically run on a remote machine by a system I don't understand I'm lost. 

Can we just get it to pull master before it does anything else?

**Comment by kwxm** [comment]
Experimenting a bit with the comparison automation script. 

/bench

**Comment by michaelpj** [comment]
Also note there are conflicts with master now.

**Comment by kwxm** [comment]
The last lot failed because of a problem with builtins in the flat format.  Let's try again.

/benchmark

**Comment by kwxm** [comment]
Hmmm.  Getting lots of this in the output
```


Previous HEAD position was 84fb35a4c Merge branch 'master' into kwxm/bench-compare-markdown
--
  | Switched to branch 'master'
  | Your branch is up to date with 'origin/master'.
  | remote: Enumerating objects: 2427, done.
  | remote: Counting objects: 100% (2411/2411), done.
  | remote: Compressing objects: 100% (831/831), done.
  | remote: Total 2427 (delta 1494), reused 2303 (delta 1451), pack-reused 16
  | Receiving objects: 100% (2427/2427), 1.07 MiB \| 6.61 MiB/s, done.
  | Resolving deltas: 100% (1494/1494), completed with 446 local objects.
  | From github.com:input-output-hk/plutus
  | f37f9cca5..679db73c5  master                  -> origin/master
  | * [new branch]          SCP-2045-bis            -> origin/SCP-2045-bis
  | b29d7aae3..4136cfc67  actus-test-framework    -> origin/actus-test-framework
  | * [new branch]          benchmarking-ci         -> origin/benchmarking-ci
```
Then lots of this:
```


plutus-core/plutus-core/test/TypeSynthesis/Spec.hs \|    3 +-
--
  | plutus-core/plutus-ir/src/PlutusIR/Compiler.hs     \|    8 +-
  | .../plutus-ir/src/PlutusIR/Transform/DeadCode.hs   \|   10 +-
  | .../plutus-ir/src/PlutusIR/Transform/Inline.hs     \|   15 +-
  | .../plutus-ir/src/PlutusIR/Transform/Rename.hs     \|    6 +-
  | plutus-core/plutus-ir/test/TransformSpec.hs        \|    5 +-
  | .../plutus-ir/test/datatypes/listMatchEval.golden  \|    2 +-
  | .../plutus-ir/test/recursion/even3Eval.golden      \|    2 +-

```
Looks like it's replaying lots of changes when it does 
```
git checkout master
git pull
git checkout "$PR_BRANCH_REF" 
```
I have no idea if that's sensible or not.

**Comment by kwxm** [comment]
Got a variable name wrong the last time.

/benchmark

**Comment by kwxm** [comment]
This looks like it maybe kind of works, but it seems to be doing an awful lot of git stuff and I'm not convinced that it's using the correct commit for the base.  I'm sure that can be improved, but my ignorance of git is too profound for me to have any idea of what the right thing to do is.  Also, it still keeps going back to `a761044`.

**Comment by michaelpj** [comment]
Do we still need this?

**Comment by kwxm** [comment]
> Do we still need this?

I think the underlying issue hasn't been resolved yet, so let's keep it for the time being.

**Comment by kwxm** [comment]
I think the issues this was exploring have been fixed in #3611 and #3651, so I'm going to close it.

**Pull request closed without merging**
