### PR TITLE
aarch64-darwin CI

### PR DESCRIPTION
**Pull request by michaelpj**
Unsure if this will actually work.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by zeme-iohk** [comment]
So close...

**Comment by michaelpj** [comment]
That's a very concerning failure.

**Comment by michaelpj** [comment]
Okay, got it. So the difference is somehow the prettyprinting???

**Comment by michaelpj** [comment]
Extremely weird. Somehow the layout options we were using were platform specific, go figure.

**Comment by michaelpj** [comment]
We were using `maxBound`, maybe that's different? although that seems like it would be a bug...

**Pull request merged**
