### PR TITLE
Make `genConstant` return `SomeGen`

### PR DESCRIPTION
**Pull request by zliu41**
The existing `genConstant :: forall a. TypeRep a -> Gen a` does not generate terms/constants of the correct type in the `Opaque` and `SomeConstant` cases - it generates arbitrary terms and Integer constants, respectively. I don't seen an easy way to correct this given the type of `genConstant`, so I reverted it back to `genConstant :: forall k (a :: k). TypeRep a -> Gen (Some (ValueOf DefaultUni))`.

### CODE REVIEW

**Comment by effectfully** [comment]
> The existing `genConstant :: forall a. TypeRep a -> Gen a` does not generate terms/constants of the correct type in the `Opaque` and `SomeConstant` cases - it generates arbitrary terms and Integer constants, respectively. I don't seen an easy way to correct this given the type of `genConstant`, so I reverted it back to `genConstant :: forall k (a :: k). TypeRep a -> Gen (Some (ValueOf DefaultUni))`.

It it's hard (I can see how it is), we may as well just not do it. We never use `Opaque val <rep>` for a monomorphic `<rep>` in the default set of built-in functions and the same applies to `SomeConstant`.

So we can use my `genConstant` (which is your `genTypeable` minus `Term`, `Opaque` and `SomeConstant` cases) +

```haskell
genArg
    :: term ~ Term TyName Name DefaultUni DefaultFun ()
    => MakeKnownIn DefaultUni term a => TypeRep a -> Gen term
genArg (matchTyCon @Opaque -> Just _)       = AST.runAstGen AST.genTerm
genArg (matchTyCon @SomeConstant -> Just _) = AST.runAstGen AST.genTerm
genArg tr                                   = genConstant tr >>= reoption . makeKnownOrFail
```

and that should be sufficient for testing those builtins that we actually care about as long as `runAstGen` generates values of the polymorphic built-in types, which I understand it can't, so we can introduce another generator, which generates either an arbitrary constant (using your generator) or an arbitrary term using `runAstGen`.

**Comment by zliu41** [comment]
@effectfully So you are proposing that we don't specifically generate well-typed inputs, if I understand correctly. I'm fine with that, but for functions like `MkCons`, the probability of generating well-typed inputs that way is pretty low, right? If the first argument is of type `a`, then the second argument must be of type `[a]` for the evaluation to succeed.

**Comment by effectfully** [comment]
> @effectfully So you are proposing that we don't specifically generate well-typed inputs, if I understand correctly. I'm fine with that, but for functions like `MkCons`, the probability of generating well-typed inputs that way is pretty low, right? If the first argument is of type `a`, then the second argument must be of type `[a]` for the evaluation to succeed.

You're right once again, I haven't thought of this builtin. Let's go with a [simpler](https://github.com/input-output-hk/plutus/commit/5665fb43aba3d32a8554a72095f576edd9778548) version that doesn't require quantifying over arbitrary kind `k` and `unsafeCoerce`?

**Comment by zliu41** [comment]
> Let's go with a [simpler](https://github.com/input-output-hk/plutus/commit/5665fb43aba3d32a8554a72095f576edd9778548) version that doesn't require quantifying over arbitrary kind k and unsafeCoerce?

Nice approach! Let me think about whether it is easy to extend this such that we generate more types rather than just integer in the `TyVarRep` case. I'm not very sure.

**Comment by zliu41** [comment]
> Let me think about whether it is easy to extend this such that we generate more types rather than just integer in the TyVarRep case.

I guess it's not too bad - we can produce a `[SomeGen]` and randomly select one element of it, and we'd also need to remember which type var has been instantiated to which type. So that means `genConstant` will need to run in `StateT IO` or `ReaderT IO`, but it's manageable.

**Comment by effectfully** [comment]
> > Let's go with a [simpler](https://github.com/input-output-hk/plutus/commit/5665fb43aba3d32a8554a72095f576edd9778548) version that doesn't require quantifying over arbitrary kind k and unsafeCoerce?
> 
> Nice approach! Let me think about whether it is easy to extend this such that we generate more types rather than just integer in the `TyVarRep` case. I'm not very sure.

It should be. Just generate a bool and then `genConstant (typeRep @Integer)` on `True` and `genConstant (typeRep @Bool)` on `False`. Although we probably want to generate one monomorphic type and one polymorphic one, so on `True` we could instead construct the type representation of the same `TyVarRep` except wrapped in the `[]` type this time and recurse.

We probably don't want to generate more than two types for type variables, so that the `a` and `[a]` arguments are likely to end up with the same `a` inside?

**Comment by effectfully** [comment]
> Just generate a bool

Ah, we're not in `Gen` of course. Well, we could make it `Gen SomeGen`.

**Comment by effectfully** [comment]
> we'd also need to remember which type var has been instantiated to which type.

I think we can sacrifice some type safety here? It's enough for us to know that well-typed programs do get generated, we may say that `genConstant` mostly generates things respecting the type, but occasionally generates something else that is useful too.

**Comment by effectfully** [comment]
> Ah, we're not in `Gen` of course. Well, we could make it `Gen SomeGen`, I guess.

Or generate a long list of booleans outside of the function and peel elements off of it. Or have another argument mutating in a pseudo-random way.

**Comment by zliu41** [comment]
@effectfully Adopted your `SomeGen` approach - it's really nice. Thanks!

Not too sure if it's worth doing the "instantiate to more types than integer" thing, but if it is, it will be done in a separate PR.

**Comment by effectfully** [comment]
> @effectfully Adopted your SomeGen approach - it's really nice. Thanks!

Thank you for coping with all my "it should be fine -- oh-oh, you're right, it's not".

> Not too sure if it's worth doing the "instantiate to more types than integer" thing, but if it is, it will be done in a separate PR.

Yeah, if we're doing it, it definitely deserves a separate PR.

Ready for another review?

**Pull request merged**
