### PR TITLE
SCP-2372: Uniswap trace and scripts

### PR DESCRIPTION
**Pull request by j-mueller**
* Add a trace for the uniswap contract: Set up a liquidity pool and add some liquidity to it
* Add uniswap scripts to `plutus-use-cases-scripts`
  * This produces 8 applied validators in total
    * the first 4 are for setting up the tokens (so not part of Uniswap itself)
    * the other validators are from two transactions, each with a script validator and an MPS. I'm assuming the validator is the larger of the two.
* I deactivated the auction scripts - for some reason the process hangs when it gets to them. It's odd because the same traces are run as part of the test suite

Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Amazing, thanks!

**Comment by michaelpj** [comment]
seems like genuine compilation errors?

**Comment by j-mueller** [comment]
Yes I need to update the `plutus-pab` module, am currently rebuilding `cardano-api`...

**Review by silky — APPROVED** [review]
LGTM! :)

**Comment by kwxm** [comment]
Excellent! Thanks for that!  I've added these to the validation benchmarks: see #3378.  This gives us validation times for some quite complicated contracts now, so that should keep the people up the food chain happy.

**Pull request merged**
