### PR TITLE
SCP-1066 reorganizing `plc-agda`

### PR DESCRIPTION
**Pull request by jmchapman**
- [x] reduce number of times the list of modules appears in the cabal file

~~The list appears in a common stanza. It is listed twice as everthing in `autogen-modules` has to appear again in `other-modules`.~~

Created a library in the cabal file and a common stanza for the usual stuff you put in a common stanza.

- [x] Split into a library and executable (not 100% sure this will work)
- [ ] Sort out naming of components

- [ ] ~~Potentially refactor existing `plc-agda` tests to call `plutus-core` functions directly rather than calling out to `plc`.~~

Arguing with CI expected.

### CODE REVIEW

**Comment by michaelpj** [comment]
Now it's just failing on the Haddock... tbh I'm not sure how that ever worked. I think I should maybe make the generation run as a `postConfigure` hook rather than `preBuild` :thinking:

**Comment by michaelpj** [comment]
Ah, there was no library so there was no Haddock!

**Comment by jmchapman** [comment]
> Now it's just failing on the Haddock... tbh I'm not sure how that ever worked. I think I should maybe make the generation run as a `postConfigure` hook rather than `preBuild` 🤔

I can do that. Do you still think it might work?

**Comment by michaelpj** [comment]
I'm just checking it out now.

**Comment by michaelpj** [comment]
Okay, it's a bit awkward to do this because you're moving things, but just steal this commit: https://github.com/input-output-hk/plutus/commit/155bee88f73a2f273c4f4c73684c24640d278f26

**Comment by jmchapman** [comment]
Thanks @michaelpj that now passes CI. However, github seems to think that CI is still failing.

**Comment by michaelpj** [comment]
Yep, it's just confused. Let's go ahead and merge it!

**Comment by michaelpj** [comment]
Oh, it's caught up. Maybe turning it off from being a draft helped?

**Comment by jmchapman** [comment]
thanks!

**Pull request merged**
