### PR TITLE
Make nix work with MacOS Big Sur

### PR DESCRIPTION
**Pull request by raduom**
Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `$(nix-build default.nix -A plutus.updateMaterialized)` to update the materialized Nix files
   - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
   - [ ] `$(nix-shell shell.nix --run fix-stylish-haskell)` to fix any formatting issues
- If you changed any Purescript files:
   - [ ] `$(nix-shell shell.nix --run fix-purty)` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Looks generally good, but something has broken in the latex builds. I can have a look later, unless anyone else beats me to it.

**Comment by michaelpj** [comment]
Fixed the latex issue, I think.

**Comment by raduom** [comment]
No new build has started. Does it need a poke?

**Comment by michaelpj** [comment]
It's getting there.

**Comment by michaelpj** [comment]
Let's go with this. I built everything fine on Linux, Hydra is happy, maybe there are still some odd things on Darwin but it's certainly less-broken than it was!

**Pull request merged**
