### PR TITLE
wip: factor out the papers

### PR DESCRIPTION
**Pull request by blaggacao**

### CODE REVIEW

**Comment by michaelpj** [comment]
What does this do? Why is it desirable? Esp given it apparently needs some hacks? Do we have linked issues for the todos?

**Comment by blaggacao** [comment]
Tested:
```console
nix-repl> :lf .
warning: Git tree '/home/blaggacao/src/github.com/input-output-hk/plutus' is dirty
Added 17 variables.

nix-repl> __std.actions.x86_64-linux.plutus.papers.utxoma-paper.build
«derivation /nix/store/11gh3biry6fqiwkwdpb39s4hzbjad9ay-build.drv»

nix-repl> :b __std.actions.x86_64-linux.plutus.papers.utxoma-paper.build

This derivation produced the following outputs:
  out -> /nix/store/qyn4b1zr6625cbsawvpa8chg46ii6na6-build
  
$ /nix/store/qyn4b1zr6625cbsawvpa8chg46ii6na6-build
$ ❯ ls -T result/
result
├── nix-support
│  └── hydra-build-products
└── utxoma.pdf
```

**Comment by blaggacao** [comment]
Restaggering (& squasing) this on https://github.com/input-output-hk/plutus/pull/5055. Thanks for the feedback Michael!!

**Comment by michaelpj** [comment]
I'm still not sure I follow, but "build" seems like a sensible action for these PDFs, so I'm not sure what the issue is :thinking:

**Comment by blaggacao** [comment]
Yes, that is absolutly the case! With this change it is also concise implements "build" (and only "build").

**Pull request closed without merging**
