### PR TITLE
contracts: Add plutus-contract-tasty package

### PR DESCRIPTION
**Pull request by j-mueller**
* Move `Language.Plutus.Contract.Test` to a separate package
* Get rid of the `tasty` and `tasty-hunit` dependencies in `plutus-contract`

### CODE REVIEW

**Comment by j-mueller** [comment]
Rebased it, the package set was already updated (generate.sh didn't make any changes)

**Comment by michaelpj** [comment]
> Rebased it, the package set was already updated (generate.sh didn't make any changes)

That seems very strange: there's now a new package!

**Comment by j-mueller** [comment]
Sorry, I meant "changes to the previous commit on this branch" (I had already run it after adding the package and changing the deps., but I ran it again just to be sure)

**Comment by michaelpj** [comment]
Oh, there are indeed changes in this PR, I somehow failed to find them.

**Pull request merged**
