### PR TITLE
Show (Token "" "") as Ada in Marlowe Playground.

### PR DESCRIPTION
**Pull request by nau**

### CODE REVIEW

**Comment by shmish111** [comment]
I think this needs to be changed in Holes.purs as well...

**Comment by nau** [comment]
> I think this needs to be changed in Holes.purs as well...

Good point. Fixed.

**Comment by shmish111** [comment]
I'm surprised this passes the tests, I would have thought this would break the parsers? Have you tried running the playground locally and checked that it works correctly?

**Comment by palas** [comment]
It seems it broke the blockly conversion to code. It is strange because it says the deployment failed

**Pull request merged**
