### PR TITLE
expose Lexer and Parser in language-plutus-core

### PR DESCRIPTION
**Pull request by jmchapman**
To allow plutus-metatheory to use the language-plutus-core lexer and
parser the following additional modules need to be exposed:

Language.PlutusCore.Type
Language.PlutusCore.Lexer
Language.PlutusCore.Lexer.Type
Language.PlutusCore.Parser

### CODE REVIEW

**Comment by effectfully** [comment]
> We should think about haddocks for this as well if these modules are to be public.

I think it's a good strategy to have proper documentation regardless of whether modules are public or not (cutting a few corners in tests is fine I'd say).

**Comment by jmchapman** [comment]
I need access to the the datatypes for syntax: Program, Term, Type, Kind, Builtin etc which are in these files I believe:

`Language.PlutusCore.Type`
`Language.PlutusCore.Lexer.Type`

I need to parse things so I need access to `parse` in `Language.PlutusCore.Parser` and the parser spits out syntax that refers to lexical stuff (which I drop) but nevertherless I think I need access to `Language.PlutusCore.Lexer.AlexPosn` which is in `Language.PlutusCore.Lexer`.

**Comment by effectfully** [comment]
> `Program`, `Term`, `Type`, `Kind`, `Builtin`

Aren't those exported from `Language.PlutusCore`?

**Comment by jmchapman** [comment]
> > `Program`, `Term`, `Type`, `Kind`, `Builtin`
> 
> Aren't those exported from `Language.PlutusCore`?

Yes. thanks. updated.

**Comment by jmchapman** [comment]
exports reduced to:

`Language.PlutusCore.Lexer`
`Language.PlutusCore.Parser`

**Comment by jmchapman** [comment]
is this ok to merge now?

**Comment by effectfully** [comment]
Yep.

**Pull request merged**
