### PR TITLE
Update cost model for Vasil release

### PR DESCRIPTION
**Pull request by kwxm**
This updates the Plutus Core cost model to include some new builtins (`serialiseData`, `verifyEcdsaSecp256k1Signature`, `verifySchnorrSecp256k1Signature`; a couple of existing builtins have also been renamed); it also recalibrates the cost model for the version of the evaluator in this branch.

The basic cost files can be found [here](https://github.com/input-output-hk/plutus/blob/kwxm/vasil/update-cost-model/plutus-core/cost-model/data/builtinCostModel.json) (builtins) and [here](https://github.com/input-output-hk/plutus/blob/kwxm/vasil/update-cost-model/plutus-core/cost-model/data/cekMachineCosts.json) (CEK machine costs). There's a file with these combined into a single set and flattened out [here](https://github.com/input-output-hk/plutus/blob/kwxm/vasil/update-cost-model/plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json).  The CPU parameters have changed significantly since previous versions but memory parameters are pretty much the same.

Here's a table showing how the predictions of the model compare with real execution times of our validation benchmarks on our reference machine (time predictions are got by dividing the CPU budget by 1e6); none of these actually use any of the new builtins, but they do use most of the rest:
<details> 
<summary>Validation predictions</summary>

Comparison of times as predicted by cost model with actual execution times.
(+ means that the model's prediction exceeds the actual time, - means that
the model's prediction is less than the actual time).

```
Script                                      actual       predicted       accuracy
---------------------------------------------------------------------------------
auction_1-1                                216.0 μs	 239.913 μs       +11.1% 
auction_1-2                                829.2 μs	 877.536 μs       +5.8%  
auction_1-3                                822.4 μs	 882.395 μs       +7.3%  
auction_1-4                                275.7 μs	 308.544 μs       +11.9% 
auction_2-1                                215.5 μs	 239.913 μs       +11.3% 
auction_2-2                                829.0 μs	 877.536 μs       +5.9%  
auction_2-3                                1.051 ms	   1.164 ms       +10.8% 
auction_2-4                                819.8 μs	 882.395 μs       +7.6%  
auction_2-5                                275.1 μs	 308.544 μs       +12.2% 
crowdfunding-success-1                     251.5 μs	 277.940 μs       +10.5% 
crowdfunding-success-2                     251.8 μs	 277.940 μs       +10.4% 
crowdfunding-success-3                     251.9 μs	 277.940 μs       +10.3% 
currency-1                                 305.3 μs	 356.567 μs       +16.8% 
escrow-redeem_1-1                          441.4 μs	 479.441 μs       +8.6%  
escrow-redeem_1-2                          442.7 μs	 479.441 μs       +8.3%  
escrow-redeem_2-1                          519.0 μs	 561.429 μs       +8.2%  
escrow-redeem_2-2                          517.8 μs	 561.429 μs       +8.4%  
escrow-redeem_2-3                          517.5 μs	 561.429 μs       +8.5%  
escrow-refund-1                            189.4 μs	 206.006 μs       +8.8%  
future-increase-margin-1                   306.2 μs	 356.426 μs       +16.4% 
future-increase-margin-2                   694.9 μs	 753.429 μs       +8.4%  
future-increase-margin-3                   693.3 μs	 753.429 μs       +8.7%  
future-increase-margin-4                   651.2 μs	 655.235 μs       +0.6%  
future-increase-margin-5                   1.025 ms	   1.048 ms       +2.2%  
future-pay-out-1                           307.3 μs	 356.426 μs       +16.0% 
future-pay-out-2                           689.9 μs	 753.429 μs       +9.2%  
future-pay-out-3                           690.5 μs	 753.429 μs       +9.1%  
future-pay-out-4                           1.023 ms	   1.046 ms       +2.2%  
future-settle-early-1                      306.6 μs	 356.426 μs       +16.3% 
future-settle-early-2                      689.1 μs	 753.429 μs       +9.3%  
future-settle-early-3                      689.0 μs	 753.429 μs       +9.4%  
future-settle-early-4                      781.6 μs	 758.484 μs       -3.0%  
game-sm-success_1-1                        498.5 μs	 513.400 μs       +3.0%  
game-sm-success_1-2                        236.1 μs	 268.107 μs       +13.6% 
game-sm-success_1-3                        824.0 μs	 877.543 μs       +6.5%  
game-sm-success_1-4                        274.1 μs	 311.658 μs       +13.7% 
game-sm-success_2-1                        499.5 μs	 513.400 μs       +2.8%  
game-sm-success_2-2                        234.8 μs	 268.107 μs       +14.2% 
game-sm-success_2-3                        821.2 μs	 877.543 μs       +6.9%  
game-sm-success_2-4                        275.3 μs	 311.658 μs       +13.2% 
game-sm-success_2-5                        826.3 μs	 877.573 μs       +6.2%  
game-sm-success_2-6                        275.8 μs	 311.658 μs       +13.0% 
multisig-sm-1                              515.2 μs	 527.390 μs       +2.4%  
multisig-sm-2                              502.9 μs	 510.369 μs       +1.5%  
multisig-sm-3                              507.6 μs	 516.116 μs       +1.7%  
multisig-sm-4                              511.5 μs	 521.863 μs       +2.0%  
multisig-sm-5                              729.6 μs	 757.682 μs       +3.8%  
multisig-sm-6                              512.0 μs	 527.390 μs       +3.0%  
multisig-sm-7                              499.4 μs	 510.369 μs       +2.2%  
multisig-sm-8                              506.8 μs	 516.116 μs       +1.8%  
multisig-sm-9                              510.5 μs	 521.863 μs       +2.2%  
multisig-sm-10                             727.4 μs	 757.682 μs       +4.2%  
ping-pong-1                                422.3 μs	 442.775 μs       +4.8%  
ping-pong-2                                421.6 μs	 442.775 μs       +5.0%  
ping-pong_2-1                              249.2 μs	 268.295 μs       +7.7%  
prism-1                                    194.9 μs	 224.444 μs       +15.2% 
prism-2                                    539.7 μs	 551.457 μs       +2.2%  
prism-3                                    454.4 μs	 512.354 μs       +12.8% 
pubkey-1                                   167.1 μs	 190.188 μs       +13.8% 
stablecoin_1-1                             1.135 ms	   1.058 ms       -6.8%  
stablecoin_1-2                             230.0 μs	 261.839 μs       +13.8% 
stablecoin_1-3                             1.293 ms	   1.254 ms       -3.0%  
stablecoin_1-4                             243.7 μs	 277.733 μs       +14.0% 
stablecoin_1-5                             1.619 ms	   1.656 ms       +2.3%  
stablecoin_1-6                             302.3 μs	 342.616 μs       +13.3% 
stablecoin_2-1                             1.133 ms	   1.058 ms       -6.6%  
stablecoin_2-2                             228.7 μs	 261.839 μs       +14.5% 
stablecoin_2-3                             1.287 ms	   1.254 ms       -2.6%  
stablecoin_2-4                             243.9 μs	 277.733 μs       +13.9% 
token-account-1                            232.1 μs	 261.994 μs       +12.9% 
token-account-2                            411.5 μs	 482.909 μs       +17.4% 
uniswap-1                                  518.7 μs	 621.510 μs       +19.8% 
uniswap-2                                  273.9 μs	 306.370 μs       +11.9% 
uniswap-3                                  2.081 ms	   2.435 ms       +17.0% 
uniswap-4                                  401.9 μs	 448.712 μs       +11.6% 
uniswap-5                                  1.436 ms	   1.571 ms       +9.4%  
uniswap-6                                  387.1 μs	 432.709 μs       +11.8% 
vesting-1                                  441.0 μs	 482.553 μs       +9.4%  
```
</details>

... and a similar table for our `nofib` examples: these are much longer-running than anything that should be running on the chain.  The cost model overestimates the running time quite severely, but this is good because we want to discourage things that consume too many resources.

<details>
<summary>`nofib` predictions</summary>

```
Script                                      actual       predicted       accuracy
---------------------------------------------------------------------------------
clausify/formula1                          22.41 ms	  37.578 ms       +67.7% 
clausify/formula2                          27.56 ms	  46.067 ms       +67.2% 
clausify/formula3                          75.35 ms	 126.577 ms       +68.0% 
clausify/formula4                          123.2 ms	 198.159 ms       +60.8% 
clausify/formula5                          476.8 ms	 811.634 ms       +70.2% 
knights/4x4                                63.58 ms	  86.974 ms       +36.8% 
knights/6x6                                168.2 ms	 251.370 ms       +49.4% 
knights/8x8                                278.0 ms	 423.074 ms       +52.2% 
primetest/05digits                         38.87 ms	  52.806 ms       +35.9% 
primetest/08digits                         71.48 ms	  97.907 ms       +37.0% 
primetest/10digits                         100.4 ms	 137.805 ms       +37.3% 
primetest/20digits                         201.8 ms	 278.376 ms       +37.9% 
primetest/30digits                         292.5 ms	 407.461 ms       +39.3% 
primetest/40digits                         391.3 ms	 546.541 ms       +39.7% 
primetest/50digits                         386.9 ms	 536.130 ms       +38.6% 
queens4x4/bt                               10.50 ms	  14.094 ms       +34.2% 
queens4x4/bm                               14.90 ms	  19.800 ms       +32.9% 
queens4x4/bjbt1                            13.11 ms	  17.716 ms       +35.1% 
queens4x4/bjbt2                            13.90 ms	  19.029 ms       +36.9% 
queens4x4/fc                               32.92 ms	  48.580 ms       +47.6% 
queens5x5/bt                               140.0 ms	 190.055 ms       +35.8% 
queens5x5/bm                               172.6 ms	 229.005 ms       +32.7% 
queens5x5/bjbt1                            167.0 ms	 225.664 ms       +35.1% 
queens5x5/bjbt2                            175.4 ms	 240.011 ms       +36.8% 
queens5x5/fc                               418.8 ms	 625.502 ms       +49.4% 
```
</details>

Finally, here's a comparison of the CPU costs for the validation examples according to the parameters in [alonzo/rc-2](https://github.com/input-output-hk/plutus/tree/alonzo/rc-2), which were deployed in the Alozno HF and are still the parameters in use on the chain.  The costs are down by 20-30%.  There will also be other improvements due to things like faster deserialisation and improved compilation that aren't reflected in these figures.

<details>
<summary>CPU cost changes from Alonzo to Vasil</summary>

```
Script                               Alonzo            Vasil         Change
-----------------------------------------------------------------------------
auction_1-1                         337872501	     239912593       -29.0% 
auction_1-2                        1154882220	     877535859       -24.0% 
auction_1-3                        1166631046	     882395004       -24.4% 
auction_1-4                         437431232	     308543570       -29.5% 
auction_2-1                         337872501	     239912593       -29.0% 
auction_2-2                        1154882220	     877535859       -24.0% 
auction_2-3                        1525694668	    1163571168       -23.7% 
auction_2-4                        1166631046	     882395004       -24.4% 
auction_2-5                         437431232	     308543570       -29.5% 
crowdfunding-success-1              392714814	     277940031       -29.2% 
crowdfunding-success-2              392714814	     277940031       -29.2% 
crowdfunding-success-3              392714814	     277940031       -29.2% 
currency-1                          479275536	     356567123       -25.6% 
escrow-redeem_1-1                   650264752	     479440897       -26.3% 
escrow-redeem_1-2                   650264752	     479440897       -26.3% 
escrow-redeem_2-1                   760080962	     561428612       -26.1% 
escrow-redeem_2-2                   760080962	     561428612       -26.1% 
escrow-redeem_2-3                   760080962	     561428612       -26.1% 
escrow-refund-1                     289673100	     206006293       -28.9% 
future-increase-margin-1            479088957	     356426174       -25.6% 
future-increase-margin-2           1010576445	     753429438       -25.4% 
future-increase-margin-3           1010576445	     753429438       -25.4% 
future-increase-margin-4            874588150	     655235010       -25.1% 
future-increase-margin-5           1363547205	    1048238081       -23.1% 
future-pay-out-1                    479088957	     356426174       -25.6% 
future-pay-out-2                   1010576445	     753429438       -25.4% 
future-pay-out-3                   1010576445	     753429438       -25.4% 
future-pay-out-4                   1360949173	    1045865103       -23.2% 
future-settle-early-1               479088957	     356426174       -25.6% 
future-settle-early-2              1010576445	     753429438       -25.4% 
future-settle-early-3              1010576445	     753429438       -25.4% 
future-settle-early-4               994881342	     758483562       -23.8% 
game-sm-success_1-1                 691893810	     513399723       -25.8% 
game-sm-success_1-2                 379567295	     268107219       -29.4% 
game-sm-success_1-3                1166611032	     877542976       -24.8% 
game-sm-success_1-4                 441081262	     311657956       -29.3% 
game-sm-success_2-1                 691893810	     513399723       -25.8% 
game-sm-success_2-2                 379567295	     268107219       -29.4% 
game-sm-success_2-3                1166611032	     877542976       -24.8% 
game-sm-success_2-4                 441081262	     311657956       -29.3% 
game-sm-success_2-5                1166640207	     877573458       -24.8% 
game-sm-success_2-6                 441081262	     311657956       -29.3% 
multisig-sm-1                       707384004	     527389709       -25.4% 
multisig-sm-2                       686082341	     510369348       -25.6% 
multisig-sm-3                       693636607	     516116111       -25.6% 
multisig-sm-4                       701190873	     521862874       -25.6% 
multisig-sm-5                      1001287979	     757681905       -24.3% 
multisig-sm-6                       707384004	     527389709       -25.4% 
multisig-sm-7                       686082341	     510369348       -25.6% 
multisig-sm-8                       693636607	     516116111       -25.6% 
multisig-sm-9                       701190873	     521862874       -25.6% 
multisig-sm-10                     1001287979	     757681905       -24.3% 
ping-pong-1                         593127344	     442774533       -25.3% 
ping-pong-2                         593127344	     442774533       -25.3% 
ping-pong_2-1                       368782179	     268294970       -27.2% 
prism-1                             316968424	     224444131       -29.2% 
prism-2                             745897182	     551456816       -26.1% 
prism-3                             696256803	     512353523       -26.4% 
pubkey-1                            269917606	     190188102       -29.5% 
stablecoin_1-1                     1325230151	    1058133489       -20.2% 
stablecoin_1-2                      371028546	     261839313       -29.4% 
stablecoin_1-3                     1555171649	    1254182078       -19.4% 
stablecoin_1-4                      393911162	     277732552       -29.5% 
stablecoin_1-5                     2024280042	    1656202009       -18.2% 
stablecoin_1-6                      485948764	     342615551       -29.5% 
stablecoin_2-1                     1325230151	    1058133489       -20.2% 
stablecoin_2-2                      371028546	     261839313       -29.4% 
stablecoin_2-3                     1555171649	    1254182078       -19.4% 
stablecoin_2-4                      393911162	     277732552       -29.5% 
token-account-1                     358051789	     261994130       -26.8% 
token-account-2                     652984079	     482909214       -26.0% 
uniswap-1                           815535557	     621509806       -23.8% 
uniswap-2                           423484013	     306369664       -27.7% 
uniswap-3                          3033528775	    2435063052       -19.7% 
uniswap-4                           634300522	     448711721       -29.3% 
uniswap-5                          2000108558	    1570570366       -21.5% 
uniswap-6                           607778728	     432709065       -28.8% 
vesting-1                           646456348	     482553388       -25.4% 
```
</details>

### CODE REVIEW

**Comment by kwxm** [comment]
Of course I forgot to update all the test results...

**Comment by kwxm** [comment]
### Cost model predictions versus execution time on different systems

The Plutus Core cost model produces a number which is supposed to indicate the CPU time to execute a program.  The cost model itself is constructed using the results of small benchmarks (run on a reference machine) which determine the costs of the primitive operations of the Plutus Core evaluator; these are then aggregated to produce an overall cost model which assigns a total CPU cost to a given Plutus Core program.  The cost model is calibrated so that the CPU cost assigned to a program should be an approximate upper bound for the actual execution time of the program on our reference machine.

We can't demand that all Cardano nodes run on hardware identical to our reference machine, but we assume that for a given machine script execution times will be approximately proportional to execution times on our reference machine. This is arguaby an optimistic assumption, so we tested it by measuring the exeuction times of realistic validation scripts (the same ones used above) on several different machines: our reference machine ("Server" below), a desktop machine and a laptop (both running Linux and both quite old), and a Mac M1 Pro. The processors and CPU times for these are given below (I'm not sure of the details for the Mac).

   * Server:  Intel Xeon E3-1240 v5 @ 3.50GHz
   * Desktop: Intel E8400 @ 3.00GHz          
   * Laptop:  Intel i5-4200U @ 1.60GHz     
   * Mac M1 Pro: Rosetta emulation

A table of execution times as multiples of the CPU budget predcited by the cost model appears below, followed by a graph of the figures. We see that for each machine we do indeed get execution times which are quite consistent multiples of the CPU budget.  We don't expect to get straight lines here because the cost model is using worst-case models for Plutus Core's built-in functions, and not all programs will be using worst-case data.  Not also that the ratio for the server are generally less than 1 (ie, actual execution times are less than predicted times) because the cost model is calibrated to generally give a conservative _over-approximation_ to execution times on the server (see the tables of actual benchmark times in an earlier comment).  Also, although the execution times on different machines are fairly consistent multiples of those on the server, the multiplicative factor isn't just the ratio of the respective CPU frequencies.  For example the CPU frequency of the server is 2.19 times that of the laptop, but execution times on the server are only about 1.68 times as fast as those on the laptop. Nevertheless, the overall consistency of the figures is very encouraging.

<details> <summary>Detailed table of figures (click to expand)</summary>
Script                          | Server | Desktop| Laptop | Mac M1 |
|:------------------------------|--------|--------|--------|--------|
| auction_1-1                   |  0.90  |  1.89  |  1.47  |  0.80  | 
| auction_1-2                   |  0.94  |  1.98  |  1.59  |  0.82  | 
| auction_1-3                   |  0.93  |  1.97  |  1.55  |  0.81  | 
| auction_1-4                   |  0.89  |  1.92  |  1.48  |  0.79  | 
| auction_2-1                   |  0.90  |  1.90  |  1.47  |  0.77  | 
| auction_2-2                   |  0.94  |  1.98  |  1.59  |  0.81  | 
| auction_2-3                   |  0.90  |  1.95  |  1.53  |  0.78  | 
| auction_2-4                   |  0.93  |  1.97  |  1.57  |  0.81  | 
| auction_2-5                   |  0.89  |  1.92  |  1.47  |  0.78  | 
| crowdfunding-success-1        |  0.90  |  1.90  |  1.51  |  0.79  | 
| crowdfunding-success-2        |  0.91  |  1.90  |  1.51  |  0.79  | 
| crowdfunding-success-3        |  0.91  |  1.90  |  1.51  |  0.79  | 
| currency-1                    |  0.86  |  1.84  |  1.43  |  0.71  | 
| escrow-redeem_1-1             |  0.92  |  1.94  |  1.54  |  0.79  | 
| escrow-redeem_1-2             |  0.92  |  1.94  |  1.57  |  0.79  | 
| escrow-redeem_2-1             |  0.92  |  1.95  |  1.55  |  0.79  | 
| escrow-redeem_2-2             |  0.92  |  1.95  |  1.55  |  0.79  | 
| escrow-redeem_2-3             |  0.92  |  1.95  |  1.55  |  0.79  | 
| escrow-refund-1               |  0.92  |  1.90  |  1.52  |  0.79  | 
| future-increase-margin-1      |  0.86  |  1.84  |  1.40  |  0.72  | 
| future-increase-margin-2      |  0.92  |  1.97  |  1.58  |  0.79  | 
| future-increase-margin-3      |  0.92  |  1.97  |  1.58  |  0.79  | 
| future-increase-margin-4      |  0.99  |  2.05  |  1.66  |  0.85  | 
| future-increase-margin-5      |  0.98  |  2.07  |  1.62  |  0.85  | 
| future-pay-out-1              |  0.86  |  1.84  |  1.40  |  0.71  | 
| future-pay-out-2              |  0.92  |  1.97  |  1.57  |  0.79  | 
| future-pay-out-3              |  0.92  |  1.96  |  1.56  |  0.79  | 
| future-pay-out-4              |  0.98  |  2.08  |  1.62  |  0.86  | 
| future-settle-early-1         |  0.86  |  1.84  |  1.41  |  0.71  | 
| future-settle-early-2         |  0.91  |  1.96  |  1.58  |  0.79  | 
| future-settle-early-3         |  0.91  |  1.96  |  1.58  |  0.79  | 
| future-settle-early-4         |  1.03  |  2.16  |  1.71  |  0.91  | 
| game-sm-success_1-1           |  0.97  |  1.98  |  1.61  |  0.84  | 
| game-sm-success_1-2           |  0.88  |  1.90  |  1.46  |  0.78  | 
| game-sm-success_1-3           |  0.94  |  1.98  |  1.56  |  0.80  | 
| game-sm-success_1-4           |  0.88  |  1.91  |  1.46  |  0.78  | 
| game-sm-success_2-1           |  0.97  |  1.98  |  1.62  |  0.84  | 
| game-sm-success_2-2           |  0.88  |  1.90  |  1.46  |  0.78  | 
| game-sm-success_2-3           |  0.94  |  1.97  |  1.56  |  0.80  | 
| game-sm-success_2-4           |  0.88  |  1.91  |  1.46  |  0.78  | 
| game-sm-success_2-5           |  0.94  |  1.97  |  1.56  |  0.80  | 
| game-sm-success_2-6           |  0.88  |  1.91  |  1.47  |  0.78  | 
| multisig-sm-1                 |  0.98  |  1.98  |  1.62  |  0.83  | 
| multisig-sm-2                 |  0.99  |  1.98  |  1.62  |  0.83  | 
| multisig-sm-3                 |  0.98  |  1.99  |  1.70  |  0.84  | 
| multisig-sm-4                 |  0.98  |  1.99  |  1.62  |  0.83  | 
| multisig-sm-5                 |  0.96  |  1.99  |  1.61  |  0.83  | 
| multisig-sm-6                 |  0.97  |  1.98  |  1.76  |  0.83  | 
| multisig-sm-7                 |  0.98  |  1.98  |  1.63  |  0.83  | 
| multisig-sm-8                 |  0.98  |  1.99  |  1.63  |  0.84  | 
| multisig-sm-9                 |  0.98  |  1.99  |  1.63  |  0.83  | 
| multisig-sm-10                |  0.96  |  1.99  |  1.61  |  0.84  | 
| ping-pong-1                   |  0.95  |  1.95  |  1.57  |  0.81  | 
| ping-pong-2                   |  0.95  |  1.95  |  1.57  |  0.81  | 
| ping-pong_2-1                 |  0.93  |  1.90  |  1.52  |  0.79  | 
| prism-1                       |  0.87  |  1.90  |  1.47  |  0.77  | 
| prism-2                       |  0.98  |  2.01  |  1.62  |  0.84  | 
| prism-3                       |  0.89  |  1.91  |  1.48  |  0.76  | 
| pubkey-1                      |  0.88  |  1.88  |  1.47  |  0.78  | 
| stablecoin_1-1                |  1.07  |  2.21  |  1.81  |  0.98  | 
| stablecoin_1-2                |  0.88  |  1.90  |  1.47  |  0.77  | 
| stablecoin_1-3                |  1.03  |  2.16  |  1.74  |  0.95  | 
| stablecoin_1-4                |  0.88  |  1.91  |  1.47  |  0.80  | 
| stablecoin_1-5                |  0.98  |  2.11  |  1.67  |  0.90  | 
| stablecoin_1-6                |  0.88  |  1.91  |  1.47  |  0.79  | 
| stablecoin_2-1                |  1.07  |  2.21  |  1.82  |  0.98  | 
| stablecoin_2-2                |  0.87  |  1.90  |  1.47  |  0.78  | 
| stablecoin_2-3                |  1.03  |  2.17  |  1.75  |  0.97  | 
| stablecoin_2-4                |  0.88  |  1.90  |  1.46  |  0.78  | 
| token-account-1               |  0.89  |  1.86  |  1.77  |  0.75  | 
| token-account-2               |  0.85  |  1.86  |  1.76  |  0.74  | 
| uniswap-1                     |  0.83  |  1.86  |  1.39  |  0.72  | 
| uniswap-2                     |  0.89  |  1.88  |  1.49  |  0.77  | 
| uniswap-3                     |  0.85  |  1.90  |  1.47  |  0.77  | 
| uniswap-4                     |  0.90  |  1.95  |  1.50  |  0.81  | 
| uniswap-5                     |  0.91  |  1.96  |  1.54  |  0.81  | 
| uniswap-6                     |  0.89  |  1.95  |  1.51  |  0.80  | 
| vesting-1                     |  0.91  |  1.91  |  1.53  |  0.77  | 
</details>

cost-model-comparison

**Comment by michaelpj** [comment]
Great, thanks!

I think we should maybe also forward-port this to master? At least then master would be closer-to-accurate (of course it'll be inaccurate because Roman has made things faster).

**Review by michaelpj — APPROVED** [review]
LGTM, merge when you're happy!

**Comment by kwxm** [comment]
> I think we should maybe also forward-port this to master? At least then master would be closer-to-accurate (of course it'll be inaccurate because Roman has made things faster).

Good idea.  I have an issue to do a full cost model update at SCP-3930, but we can just copy the data files to master for a quick update.

**Pull request merged**
