### PR TITLE
Fix broken link to validator script tutorial.

### PR DESCRIPTION
**Pull request by tensafefrogs**
Found a broken link in the docs. I think this fixes it but I don't know how to actually test this, so feel free to adjust as needed.

### CODE REVIEW

**Comment by tensafefrogs** [comment]
Sorry for the multi-commit, please squash when merging.

**Comment by j-mueller** [comment]
Thank you! (Build currently broken due to an unrelated issue, I'll merge when it's fixed)

**Review by j-mueller — APPROVED** [review]

**Comment by j-mueller** [comment]
> I don't know how to actually test this, so feel free to adjust as needed.

You can do `nix build -f default.nix docs.build-and-serve-docs`. Then open the docs at localhost:8002. I did that and it looked ok.

**Comment by tensafefrogs** [comment]
> You can do `nix build -f default.nix docs.build-and-serve-docs`.

👍 Will do in the future, thanks!

**Comment by j-mueller** [comment]
@tensafefrogs Can you rebase onto the master branch? I think that should fix the CI issue

**Comment by tensafefrogs** [comment]
This should be all set now.

**Comment by j-mueller** [comment]
ok, sorry there seems to be another conflict, you can just merge when that's resolved

**Pull request merged**
