### PR TITLE
Renormalize to LF line endings

### PR DESCRIPTION
**Pull request by bezirg**
Getting rid of all CRLF line endings

### CODE REVIEW

**Comment by michaelpj** [comment]
Eeeh, this sort of things is a bit annoying, so I'm inclined to prefer that people just fix this for the files that they edit, which should happen so long as the .editorconfig is working...

**Comment by michaelpj** [comment]
Or we could do it in one go. A lot of this stuff is random copied in files, so it probably won't conflict much.

**Comment by bezirg** [comment]
I think they are just old files,leftovers. The git `autocrlf` setting or editorconfig will not fix them, unless somebody updates something inside them and commits

**Comment by michaelpj** [comment]
> I think they are just old files,leftovers.

If nobody looks at them, do we care? :)

**Comment by bezirg** [comment]
There are no other non-LF endings, this was done with `git add --renormalize .` and `.gitattributes * text=lf`

**Comment by michaelpj** [comment]
Okay, seems fine, but perhaps we should check in the `.gitattributes` change too?

**Comment by bezirg** [comment]
I also thought of that but I got worried if it will mess any binary files. So i added the .giattributes change just manually, ran `git add --renormalize .` and threw away the gitattributes change.

**Pull request merged**
