### PR TITLE
PlutusTx: two final renames

### PR DESCRIPTION
**Pull request by michaelpj**
These are I think the last things I want to rename before the conference.

- `PlcCode` -> `CompiledCode`
    - I want to avoid mentioning PLC as much as possible.
    - The more "opaque" the name here the better, since in future we may end up stuffing even more things in here (like additional debug information).
    - Alternatives:
        - `Code` (too generic IMO)
        - `StagedCode`
- `plutus` -> `compile`
    - This makes it much clearer what is actually happening, IMO.
    - Fits nicely with `CompiledCode`: `compile :: TH.TExp a -> CompiledCode`
    - Alternatives:
       - `plutusTx` (I was originally going to use this, but then I thought of `compile`)

The `plutus` rename is the most user-facing one, so I'd like some opinions on that.

### CODE REVIEW

**Comment by mchakravarty** [comment]
I think, the embedding is more important aspect. If we'd change it tomorrow to embed the source code, it'd still be accurate, whereas the fact that we are compiling it to PLC is more of an artefact of our specific approach.

Also, I am pretty sure that more people are comfortable with `embed` than `compile`. Take somebody whole learnt Javascript from reading some online tutorials (probably the most widespread form of developer these days). That person would have embedded stuff, but think about compilation as something done by these other devs who constantly go on about how much better they are.

**Comment by mchakravarty** [comment]
(Anyway, this is just a mild preference. @j-mueller @krisajenkins @shmish111 Any opinion on this one?)

**Comment by michaelpj** [comment]
> If we'd change it tomorrow to embed the source code, it'd still be accurate, whereas the fact that we are compiling it to PLC is more of an artefact of our specific approach.

This is a great point. I'm convinced - the embedding is the fundamental bit here, the compilation is indeed incidental.

My only question now is whether we should use  "stage" rather than "embed" if we're going to talk about "staged programming" rather than "embedded programming"?

**Comment by shmish111** [comment]
just that "embedded programming" seems better than "staged programming"

**Comment by michaelpj** [comment]
I'm worried that "embedded programming" sounds like we're doing hardware.

**Comment by j-mueller** [comment]
I definitely prefer that `compile`.

> Also, I am pretty sure that more people are comfortable with embed than compile. Take somebody whole learnt Javascript from reading some online tutorials (probably the most widespread form of developer these days). That person would have embedded stuff, but think of compilation as something done by these other devs who constantly go on about how much better they are.

There are some compilers in the JavaScript world, for example the Google Closure Compiler. (There are also quite a few "transpilers" in JS land so maybe that's what we should call it ;) )

**Comment by j-mueller** [comment]
On the other hand, I don't want to block this PR indefinitely, so `embed` is ok as well. Although I do share @michaelpj's concerns about embedded programming.

**Comment by mchakravarty** [comment]
Actually, `stage` and `StagedCode` is great, too, and more accurate.

I don't think, somebody will confuse it with "embedded programming" if we use `embed` and `EmbeddedCode`. (Embedding stuff is common place.)

Ok, I leave the final choice to you @michaelpj. For me `stage`/`StagedCode` > `embed`/`EmbeddedCode` > `compile`/`CompiledCode`.

**Comment by nau** [comment]
I'd leave it as `plutus`.
It directly indicates that's the code is a Plutus code. 
I don't think users would care if it's staged or compiled or whatever, and what's the precise name of it.
Tomorrow we might have a `marlowe` plugin/quasiquoter, btw.

**Comment by michaelpj** [comment]
Okay, so we have:
- `plutus` (although at least it should be `plutusTx`): @nau @effectfully 
- `stage`: @mchakravarty 
- `compile`: @j-mueller 
- `embed`: @shmish111 

What a glorious consensus :laughing:

**Comment by mchakravarty** [comment]
> I'd leave it as `plutus`.

The problem with `plutus` is that it is wrong. If anything, but is `plutusTx` (which we want to de-emphasis as a name). Also what about the code, then? `PlutusCode` is also wrong.

**Comment by mchakravarty** [comment]
What I am trying to say, I am not very fussed about it being `stage`, `embed, or `compile`, but I don't want to keep `plutus` and `PlcCode`.

**Comment by michaelpj** [comment]
I also don't like `plutusTx` because it's not a verb, and this is a function that *does* something.

**Comment by nau** [comment]
> What I am trying to say, I am not very fussed about it being `stage`, `embed`, or `compile`, but I don't want to keep `plutus`and`PlcCode`.

I'm just saying that people tend to not care about these technicalities, but like Brands™, i.e. `Plutus` (not PlutusTx), `Marlowe` etc. That's why those have logos as well.

If it's not `plutus`, then I vote for `compile`.
Anyway, people would just copy-paste whatever from tutorial/examples.

**Comment by michaelpj** [comment]
Hydra just doesn't seem to be reporting statuses today...

**Pull request merged**
