### PR TITLE
SCP-2107: JSON encoding bug

### PR DESCRIPTION
**Pull request by j-mueller**
* We have types that help us get the encoding right, we should actually use them.

Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by j-mueller** [comment]
I tested this with the currency contract in `plutus-pab-demo-scripts`.

**Comment by michaelpj** [comment]
Unsure if this is a genuine failure, restarted just to see.

**Comment by michaelpj** [comment]
Hmm, it was transient :(

**Comment by gilligan** [comment]
I suppose this is related to the runtime error that @merivale was reporting on the frontend - is there any way we can encode this in a test to make sure this won't be happening again going forward?

**Review by merivale — APPROVED** [review]
Spot on, thanks!

**Comment by j-mueller** [comment]
I'll add a test for it.

**Pull request merged**
