### PR TITLE
[Builtins] Pull 'DefaultMachineParameters' into 'plutus-core'

### PR DESCRIPTION
**Pull request by effectfully**
This is so that I can look into the Core for builtins without waiting a ridiculous amount of time whenever I change something.

### CODE REVIEW

**Comment by effectfully** [comment]
Err, benchmarked the wrong thing.

**Review by michaelpj — APPROVED** [review]
Maybe add a module comment explaining why these functions are in their own module.s

**Comment by effectfully** [comment]
Screenshot from 2022-06-06 14-57-47
Screenshot from 2022-06-06 14-58-07
Screenshot from 2022-06-06 14-58-13

I'll add the comments of course :slightly_smiling_face:

**Comment by effectfully** [comment]
^ just being paranoid

**Review by michaelpj — APPROVED** [review]

**Pull request merged**
