### PR TITLE
WIP Cross Everything

### PR DESCRIPTION
**Pull request by angerman**
The massive cross compilation. Let's try ghcjs and windows for now.
Windows *will* fail due to no plugin logic, but we can see how far we get without plugins.
GHCJS will also fail, so we'll be playing whack-a-mole for a while.

### CODE REVIEW

**Comment by angerman** [comment]
We have:
- quite a bit of vendored stuff in contrib; this will eventually turn into patches in the haskell module.
- quite a few changes in the cabal.project, which I think we can move into the cabal.project.local file that's generated on the fly for ghcjs.
- a cardano-base bump, to get rid of the zlib dependency via digest (it's gone in cardano-base now...)
- Killing of `ANN` HLint instructions replacing them with `HLINT`; this does *not* trigger the TH pipeline, which `ANN` does.

**Comment by angerman** [comment]
I intent to graft fixes required to get larger hydra coverage on top of this.

**Comment by angerman** [comment]
Really annoying that hydra wants to eval *every* damn attribute. Even though quite a bit is working hydra is choking on a lot.

**Comment by angerman** [comment]
I don't think we have realistic options to cross compile agda, so we'll need to disable that outright for cross compilation.

**Comment by michaelpj** [comment]
Maybe we should start trying to cross compile a few things and work up, rather than trying everything and working down? :sweat_smile: 

Especially since we really don't need to cross-compile everything e.g. we definitely don't need to cross-compile `plutus-metatheory`.

**Comment by angerman** [comment]
> Maybe we should start trying to cross compile a few things and work up, rather than trying everything and working down? 😅
> 
> Especially since we really don't need to cross-compile everything e.g. we definitely don't need to cross-compile `plutus-metatheory`.

@michaelpj I'm not going for *all*, but having all in there is showing systemic challenges :-)

**Comment by angerman** [comment]
Lovely, now we have cardano-api in the dependencies of plutus-pab

**Comment by angerman** [comment]
Closed in favour of #3800

**Pull request closed without merging**
