### PR TITLE
Fix build breaking regression

### PR DESCRIPTION
**Pull request by runexec**
Took me a few days to figure it out; a crime against humanity, but this should fix it. See for reference https://github.com/NixOS/nixpkgs/issues/118722#issuecomment-814881823

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by runexec** [comment]
> Thanks @runexec - what error was this causing?

Doesn't build because trying to modify read-only filesystem.

**Comment by silky** [comment]
@runexec - can you please try this branch - https://github.com/input-output-hk/plutus/pull/3167

And if that doesn't work, can you please let me know what OS you're seeing this issue on?

Just to clarify, you're getting this error when you run:
```
docker load < $(nix-build default.nix -A devcontainer)
```
?

**Comment by luigy** [comment]
I'm also on nixos and this fixes building `devcontainer`
verified with: `nix-build default.nix -A devcontainer`

**Comment by luigy** [comment]
@silky  #3167 fixes building `devcontainer` as well on nixos

Also, anything blocking from putting `devcontainer` on ci?

**Comment by silky** [comment]
Thanks for this @luigy ; interesting, I'll merge #3167.

And re: the devcontainer on CI; if I understand you correctly, then this is already in progress in https://github.com/input-output-hk/plutus/pull/3155.

**Comment by michaelpj** [comment]
The devcontainer is large and will be rebuilt every commit, we don't want to clog up the nix store with a copy of it for every single commit.

**Pull request closed without merging**
