### PR TITLE
deployment shell

### PR DESCRIPTION
**Pull request by gilligan**
## Summary
This PR introduces a reworked _deployment shell_ for working deploying plutus/marlowe using terraform/morph.

The basic premise is that anyone who has been making deployments before _SHOULD_ still be able to deploy without having to do any extra/repeated setup steps with gpg/pass or anything else. The commands for triggering deployments *did* change however. The basic workflows is as follows:

## Workflow

**(1)** Log in to your aws account using `aws-mfa-login` which is provided by the top-level shell.nix:
```
# Assuming you are already inside the shell or are using something like lorri/direnv etc
$ eval $(aws-mfa-login <username> <mfa-code>)
```

**(2)** Inside the `deployments` directory start a shell for the environment you want to work on:
```
$ nix-shell -A alpha
```
This will run some init code (you will need to unlock your gpg key) and provide an overview of the available commands 

```
---------------------------------------------------------------------
deployment shell for 'alpha'
---------------------------------------------------------------------
Available commands:

        * provision-infra:  provision infrastructure
        * destroy-infra:    destroy the infrastructure completely
        * deploy-nix:       deploy nix configuration to infrastructure
        * deploy:           provision infrastructure and deploy nix configuration

Key handling

        * import-gpg-keys:  import all relevant gpg keys
        * init-keys-alpha:   allow configured keys access to this environment

Notes:

- Being logged in to aws via 'aws-mfa-login' is a prerequisite to all infrastructure commands
- The './terraform' dir has to be specified to run arbitrary terraform commands (e.g. 'terraform plan ./terraform')
- The './morph/configurations.nix' file has to be specified to run arbitrary morph commands (e.g. 'morph build ./morph/configurations.nix)
```

**(3)** Inside this shell you can use the commands listed above to deploy/destroy etc

### Running commands directly
Instead of entering the shell environment as described above you can also specify a command directly: The following command will execute terraform *and* morph deployment in sequence for the `alpha` environment

```
$ nix-shell -A alpha --command deploy
```
## TODOs
The README needs to be adjusted containing accurate information about how to set up new users and configure keys etc. At this point however the focus needs to be on ensuring that people who are currently already using the existing setup can continue to do so.

## Rationale
This PR doesn't per se provide drastic improvements to users but the way the shell works and some of the changes in the nix/shell code avoid inconsistencies that could occur before between terraform and morph. Changes that have more impact on the usability and efficiency (*especially* on how long it takes to run deployments) will follow.

----
Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `nix-shell shell.nix --run updateMaterialized` to update the materialized Nix files
    - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
    - [ ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
- If you changed any Purescript files:
    - [ ] `nix-shell shell.nix --run fix-purty` to fix any formatting issues

Pre-merge checklist:
- [x] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Review by palas — APPROVED** [review]
Very nice. I like the explanation when you enter the shell, very handy to have it there :)

I used it to deploy to the `testing` environment and worked fine for me.

It didn't work straightaway because `marlowe-dashboard` was broken and that brought me to realise it was not checked by the CI. So I added a commit to fix this and ensure it doesn't happen in the future, hope that is ok

**Comment by gilligan** [comment]
@palas thanks!

**Comment by merivale** [comment]
That's alarming... Good catch @palas. (Also, nice work on this @gilligan.) Do we know what was broken in the dashboard, or should I be looking into that?

**Comment by merivale** [comment]
Ah, I've just looked at your commit message. Was it just the need to run spago2nix? In which case, that was my fault. I thought something was funny there, but hydra didn't complain, so I merged anyway. This would explain all that.

**Comment by palas** [comment]
Thank you. Yes, precisely, maybe "it was broken" was an overstatement :)

**Pull request merged**
