### PR TITLE
SCP-3935: rename verifySignature

### PR DESCRIPTION
**Pull request by kwxm**
This renames the `verifySignature` builtin to `verifyEd25519Signature` for clarity now that we have [multiple signature verification functions](https://github.com/input-output-hk/plutus/blob/3644b6e7fa66c01cf4669f848f59a2be1bacefd4/plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs#L70).

* The only place this matters is in the protocol parameters and I have no idea what to do there. Presumably the name has to remain `verifySignature` in the old parameters, but is it safe to update it in the new ones? What should I do [here](https://github.com/input-output-hk/plutus/blob/0e80a922317cf8c74091cf5048555302a1f2a68b/plutus-ledger-api/src/Plutus/ApiCommon.hs#L114)?

* I see some occurrences of `verifySignature` in `plutus-apps`, so merging this would break that; would we make a separate PR to fix that if/when this gets merged?

* @jmchapman I modified quite a lot of stuff in `plutus-metatheory` just by searching and replacing, but you should probably check that it's OK.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
Has conflicts now, sorry.

**Comment by michaelpj** [comment]
Based on discussion with Jared, I think this is safe.

**Comment by kwxm** [comment]
It seems that what's important for the ledger is the _order_ of the cost model parameters, not the names.  But the order _where_ exactly?  I've tried to keep the order the same, but in some places automatically-produced output arranges things in alphabetical order (in`builtinCostModel.json`, for example (although I think this used to be output in apparently random order, but changed a while ago)).  

At the end of an aphabetical list, we used to have 
```
  unListData
  unMapData
  verifySignature
```
but with this renaming and the introduction of the SCEP256k1 functions we now have
```
  unListData
  unMapData
  verifyEcdsaSecp256k1Signature
  verifyEd25519Signature  -- new name for verifySignature
  verifySchnorrSecp256k1Signature
```
Annoyingly the new name for `verifySignature` puts it right between the two new functions.

It would be good to make sure that in places where these things need to be in a specific order, they always are in that order.  Maybe we could add a numeric prefix or something.

**Comment by michaelpj** [comment]
@kwxm There's a ticket for taming the order-dependence: https://input-output.atlassian.net/browse/SCP-2696

In the case that you pointed out, it only matters for Plutus V2, where the ledger does not (yet) have fixed opinions about the order. And in V1 it doesn't change the order.

That said, it would make it annoying to actually backport these functions to V1... ugh. I think it's fine, though, unless there's a natural name that puts it before the other two.

**Comment by michaelpj** [comment]
Has conflicts.

**Comment by kwxm** [comment]
> unless there's a natural name that puts it before the other two.

`verifyEd25519Signature` -> `verifyAnEd25519Signature` ...

**Comment by kwxm** [comment]
> Has conflicts.

That was because of `blake2b_256`.  It should be fixed now.

**Comment by kwxm** [comment]
> Or maybe Hydra is lagging?

Maybe.  It seems to be OK now and I haven't done anything.

**Pull request merged**
