### PR TITLE
SCP-2543: Move core chain index to plutus-contract

### PR DESCRIPTION
**Pull request by j-mueller**
The dependency between `plutus-contract` and `plutus-chain-index` was the wrong way around. We need the chain index effect and the emulator implementation in `plutus-contract`. The real chain index implementation should go into `plutus-chain-index`, which should depend on `plutus-contract`.

Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

**Comment by michaelpj** [comment]
Why does `plutus-chain-index` depend on `plutus-contract`? I would have thought that `plutus-contract` depending on `plutus-chain-index` was the right way around?

**Comment by j-mueller** [comment]
`plutus-chain-index` is going to get a bunch of new dependencies soon (database, node client, etc) so I thought it would be better to have those upstream of `plutus-contract`

**Comment by michaelpj** [comment]
Okay, I'll leave it to your judgement :)

**Comment by j-mueller** [comment]
Hm, I suppose we could add the dependencies to the executable target only. But then the tests get a bit harder to write. I'll think about it a little more.

**Comment by j-mueller** [comment]
okay, let's leave it as it is. `plutus-contract` is already pretty big.

**Pull request closed without merging**
