### PR TITLE
[Uniques] Do not rename booleans

### PR DESCRIPTION
**Pull request by effectfully**
Kenneth figured out that renaming of booleans might caused a noticeable slowdown. Since this renaming is not actually needed, we can just remove it.

### CODE REVIEW

**Comment by michaelpj** [comment]
Can we have a note in the code about why we don't rename here, please.

**Comment by effectfully** [comment]
> Can we have a note in the code about why we don't rename here, please.

Yes, but I'll add it once it's clear there is indeed a noticeable slowdown.

Most of the CI checks show "The log file is not available", do I need to perform some brute-force search in order to figure out what is wrong?

**Comment by effectfully** [comment]
Ah, well, uniques again:

```
    even2:                                      FAIL
      Test output was different from 'test/Evaluation/even2.plc.golden'. It was: "(abs a_6 (type) (lam x_7 a_6 (lam y_8 a_6 x_7)))"
    even3:                                      FAIL
      Test output was different from 'test/Evaluation/even3.plc.golden'. It was: "(abs a_9 (type) (lam x_10 a_9 (lam y_11 a_9 y_11)))"
```

But in any case, it would be nice to see some actual response of CI rather than a bunch of "The log file is not available".

**Comment by michaelpj** [comment]
Huh, I found that in the log easily enough, not sure why you couldn't see them.

**Comment by kwxm** [comment]
Compared to the current version in the master branch, this change reduces the execution time of fib(31) from to 12.14s to 8.21s (-32%) and tri(2000000) from 13.34s to 10.52s (-21%). I'd say that justifies the change.

**Comment by kwxm** [comment]
Should we do the same thing elsewhere, for example for the unit value?  That's probably used much less  often than booleans, but I suppose we should be consistent.

**Comment by effectfully** [comment]
Great, thank you.

While we're here, there is another thing to test: whether having booleans as CAFs (i.e. no `Quote` at all while evaluating things) gives a speedup or no. `Quote` is rather deeply incorporated into evaluation and we can't just remove it, because many things that use the same constant application machinery, that the machines use, do require unique names, but I think we can do some parameterization here. Let's keep this PR open, so that I feel enough pressure to actually implement this.

**Comment by effectfully** [comment]
> Here's a fancy PDF. Good results.

Cool, thanks.

If I'm reading this correctly, my recent changes (the "[Eval] Made built-in names application violate the global uniqueness condition" commit) had basically no effect and the only noticeable speed-up we get by just not renaming booleans.

It would be great if you could generate the same PDF, but with the 731fe50c and 58d55c42 commits from this PR tracked separately. But if it takes more than, say, 20 minutes, then don't bother, it's not too important.

> Incidentally, are you also not renaming units?

I'm renaming them here, but the plan is to remove all renamings completely from the stdlib. I'll do this once #580 is merged. But we can probably do something even better, but that's irrelevant here. Anyway, all calls to `rename` from the stdlib are going to disappear.

**Comment by kwxm** [comment]
I can do that tomorrow.  It's just a matter of changing a script and then leaving the machine alone for an hour or so while it runs the tests.

**Comment by effectfully** [comment]
Thank you, this confirms that there is not much performance difference.

> What exactly happens in commit `58d55c4`?

I remove `Quote` entirely from the evaluation engine (i.e. from the constant application machinery and all the abstract machines) which allows to turn generated booleans into CAFs, so that they are shared rather than generated over and over again.

Memory consumption differs between the two commits, but memory consumption of the latest one closely follows the pattern seen on master, which is no surprise: I merged master in. So compared to master, the change does not affect anything.

**Comment by effectfully** [comment]
Closing in favor of #621.

**Pull request closed without merging**
