### PR TITLE
[Release] 1.11.0.0

### PR DESCRIPTION
**Pull request by bezirg**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
I suggest we delay this until https://github.com/input-output-hk/plutus/pull/5481 is in, so then when we update the ledger to this version they can start doing integration.

**Comment by zliu41** [comment]
@bezirg #5481 is merged.

**Comment by bezirg** [comment]
> @bezirg #5481 is merged.

Ok I rebase this release PR.

**Comment by bezirg** [comment]
> > @bezirg #5481 is merged.
> 
> Ok I rebase this release PR.

Actually I will start clean

**Comment by bezirg** [comment]
@michaelpj did u happen to restart the CI?

**Comment by michaelpj** [comment]
Yes, but it failed again? not sure

**Comment by bezirg** [comment]
@michaelpj is it related to this? https://github.com/input-output-hk/plutus/blob/1e03cbd46a2d96a166053614a8947904e89b9eb4/plutus-tx/src/PlutusTx/Lift/TH.hs#L462-L465

**Comment by zliu41** [comment]
This is super weird.

**Comment by michaelpj** [comment]
Probably. I remember this turning up before, it was super weird. I don't know why it is turning up now...

**Comment by michaelpj** [comment]
I would really like to avoid debugging this lol :sweat_smile:

**Comment by michaelpj** [comment]
And it's green, go figure.

**Comment by michaelpj** [comment]
Oh, you changed something. I'm unsure if that's safe...

**Comment by michaelpj** [comment]
I think you can just rebase for Ziyang's fix now

**Comment by bezirg** [comment]
I rebased, if pass lgtm

**Pull request merged**
