### PR TITLE
Try collapsing multiple application frames.

### PR DESCRIPTION
**Pull request by michaelpj**
Pretty sure this is going to be worse, but benchmarking for curiosity. Wasn't discernably different locally.

### CODE REVIEW

**Comment by michaelpj** [comment]
These results seem very unlikely. I fear we are indeed not going to get reliable numbers out of this.

**Comment by kwxm** [comment]
First lot of results:
```
stablecoin_1-5 | 1.989 ms | 1.987 ms | -0.1%
-- | -- | -- | --
stablecoin_1-6 | 361.0 μs | 359.7 μs | -0.4%
stablecoin_2-1 | 1.370 ms | 1.364 ms | -0.4%

uniswap-4 | 489.2 μs | 471.0 μs | -3.7%
-- | -- | -- | --
uniswap-5 | 1.722 ms | 2.119 ms | +23.1%
uniswap-6 | 463.3 μs | 456.0 μs | -1.6%
```

Second lot:
```
stablecoin_1-5 | 1.962 ms | 1.962 ms | 0.0%
-- | -- | -- | --
stablecoin_1-6 | 354.8 μs | 579.9 μs | +63.4%
stablecoin_2-1 | 1.341 ms | 1.336 ms | -0.4%

uniswap-4 | 472.3 μs | 478.0 μs | +1.2%
-- | -- | -- | --
uniswap-5 | 1.731 ms | 1.743 ms | +0.7%
uniswap-6 | 454.8 μs | 461.8 μs | +1.5%
```

:(

**Pull request closed without merging**
