### PR TITLE
[WIP] link to published paper DOIs

### PR DESCRIPTION
**Pull request by jmchapman**
The two MPC 2019 papers have now been published:

https://link.springer.com/book/10.1007/978-3-030-33636-3

- [X] link to published versions of papers in top level readme.
- [X] update cross-references in papers.
- [ ] update version on IOHK website.

### CODE REVIEW

**Comment by michaelpj** [comment]
Do we need to put any prose in the paper itself, like "this is a final version of the paper <DOI>`?

**Comment by jmchapman** [comment]
It is supposed to be the 'accepted manuscript' so I think we should leave it as is. I think the important thing is to ensure that there are no old versions lurking around. I will contact Mirjam about updating the version on the IOHK website.

**Comment by michaelpj** [comment]
Great!

**Comment by kwxm** [comment]
Any suggestions as to what we should do with the versions in the `plutus-papers` repository? I think the public versions of both papers have some revisions that aren't included in the private versions, so maybe we should add README files in `plutus-papers` directing people to the final versions.  We could also just delete the private versions.

**Comment by jmchapman** [comment]
I would vote for adding a README.

**Comment by michaelpj** [comment]
I vote for just deleting them. Or ignoring them. It's a WIP repo, I don't think anyone is likely to be confused.

**Comment by kwxm** [comment]
I just added links to the new version in the README files.  I've also added publication information and links in the README files in the public repository.

**Pull request merged**
